### ISSUE TITLE
caractéristiques hydrogéologiques 

### ISSUE THREAD

**Issue by matthieuBAI** [BRGM/hubeau#10]
Bonjour, 

existe t 'il un outil dans l'API pour récupérer à partir d'un code BSS, toutes les infos stockée dans un point BSS eau (code masse d'eau, nom de la masse d'eau ….. )

merci 

Matthieu

**Comment by tvilmus** [comment]
Bonjour,

L'opérations "stations" de L'API Qualité des eaux souterraines vous permet d'avoir des informations sur les points d'eau délivrant des données de qualité d'eau souterraines.
Voir http://hubeau.eaufrance.fr/page/api-qualite-nappes#!/qualite-nappes/stations
Par exemple, en interrogeant le code BSS BSS000XUUM, vous avez les infos suivantes :

{
  "count": 1,
  "first": "http://hubeau.eaufrance.fr/api/v1/qualite_nappes/stations?bss_id=BSS000XUUM&format=json&page=1&size=20",
  "last": null,
  "prev": null,
  "next": null,
  "api_version": "1.1.0",
  "data": [
    {
      "bss_id": "BSS000XUUM",
      "code_bss": "03195X0015/HY",
      "urn_bss": "http://services.ades.eaufrance.fr/pointeau/BSS000XUUM",
      "date_debut_mesure": "1983-05-18",
      "date_fin_mesure": "2014-05-26",
      "longitude": -1.076111596,
      "latitude": 48.081871278,
      "altitude": "125.0",
      "code_insee": "35217",
      "nom_commune": "PERTRE(LE)",
      "num_departement": "35",
      "nom_departement": "ILLE-ET-VILAINE",
      "nom_region": "BRETAGNE",
      "circonscriptions_administrative_bassin": [
        "LOIRE-BRETAGNE"
      ],
      "bassin_dce": "La Loire, les cours d'eau côtiers vendéens et bretons",
      "urn_bassin_dce": "http://www.sandre.eaufrance.fr/geo/BassinDCE/FRG",
      "code_nature_pe": 4,
      "nom_nature_pe": "Drain",
      "uri_nature_pe": "http://id.eaufrance.fr/NSA/149#4",
      "libelle_pe": "DRAINS DE LA FORET DU PERTRE - MOULIN DU BOIS",
      "code_caracteristique_aquifere": null,
      "nom_caracteristique_aquifere": null,
      "uri_caracteristique_aquifere": null,
      "code_etat_pe": null,
      "nom_etat_pe": null,
      "uri_etat_pe": null,
      "code_mode_gisement": 1,
      "nom_mode_gisement": "Libre",
      "uri_mode_gisement": "http://id.eaufrance.fr/NSA/81#1",
      "profondeur_investigation": 5,
      "commentaire_pe": null,
      "codes_entite_hg_bdlisa": [
        "174AA01"
      ],
      "noms_entite_hg_bdlisa": [
        "Socle métamorphique dans les bassins versants de la Vilaine, la Seiche et le Don de leurs sources à la mer"
      ],
      "urns_bdlisa": [
        "http://reseau.eaufrance.fr/geotraitements/bdlisa/files/entite/174AA01.pdf"
      ],
      "codes_masse_eau_rap": [
        "GG015"
      ],
      "noms_masse_eau_rap": [
        "Vilaine"
      ],
      "urns_masse_eau_rap": [
        "http://www.sandre.eaufrance.fr/geo/MasseDEauSouterraine/GG015"
      ],
      "codes_masse_eau_edl": [
        "GG015"
      ],
      "noms_masse_eau_edl": [
        "Bassin versant de la Vilaine"
      ],
      "urns_masse_eau_edl": [
        "http://www.sandre.eaufrance.fr/geo/MasseDEauSouterraine/GG015"
      ],
      "codes_reseau": [
        "0000000028"
      ],
      "noms_reseau": [
        "Réseau national de suivi au titre du contrôle sanitaire sur les eaux brutes utilisées pour la production d'eau potable"
      ],
      "uris_reseau": [
        "http://id.eaufrance.fr/DC/0000000028"
      ],
      "geometry": {
        "type": "Point",
        "crs": {
          "type": "name",
          "properties": {
            "name": "urn:ogc:def:crs:OGC:1.3:CRS84"
          }
        },
        "coordinates": [
          -1.0761115958343,
          48.0818712782975
        ]
      }
    }
  ]
}

Vous avez ainsi accès aux informations sur tous les points d'eau de type qualitomètre présents dans la base ADES.
Actuellement, l'API Piézométrie qui fournit les informations sur les piézomètres et leurs mesures de niveaux d'eau donne moins d'information sur les points d'eau (entités bd Lisa mais pas encore les masses d'eau).
N'hésitez pas à préciser les informations dont vous avez besoin en mentionnant bien sur quel type de donnée (piézométrie ou qualité).

Cordialement,
Thierry

**Comment by matthieuBAI** [comment]
merci de votre retour !
