### ISSUE TITLE
Superficie du Bassin Versant

### ISSUE THREAD

**Issue by DthOrleans** [BRGM/hubeau#100]
Comment obtenir les superficies des bassins Versants associés aux stations hydrométriques sélectionnées ?

**Comment by PBirchen** [comment]
on retrouve la superficie au niveau du site, pas de la station il me semble

**Comment by antonio-andrade** [comment]
Effectivement, la surface en km2 du bassin versant associé à un site hydrométrique (cf. https://www.sandre.eaufrance.fr/definition/HYD/2.0/BassinVersantSiteHydro) est fournie dans l'attribut `surface_bv`

![image](https://user-images.githubusercontent.com/63242934/156160851-865809af-c753-46ae-8db5-b96f75f3d4af.png)
