### ISSUE TITLE
Utilisation de Wildcards * dans les recherches (un classic)

### ISSUE THREAD

**Issue by lerio29** [BRGM/hubeau#101]
Bonjour,

il serait intéressant et pratique de pouvoir utiliser des wildcard dans les paramètres de recherches tels que les libellés.

exemple :
hubeau.eaufrance.fr/api/vbeta/surveillance_littoral/lieux_surv&libelle_lieusurv=*Morgat*

**Comment by tvilmus** [comment]
Bonjour, 
Les wildcards sont disponibles dans certains champs de type code (par exemple les codes entités de l'API hydrométrie) mais ne sont pas systématiquement implémentés.
