### ISSUE TITLE
[Qualité physico-chimique des cours d'eau] bug

### ISSUE THREAD

**Issue by PBirchen** [BRGM/hubeau#103]
quand je veux générer l'url en indiquant un code_station, il faut mettre celui-ci entre quotes, sinon le bouton `Execute` n'est pas actif. Mais la requête générée ne renvoie aucune donnée. Il faut enlever manuellement dans la requête les %22
exemple d'url générée:
https://hubeau.eaufrance.fr/api/v1/qualite_rivieres/operation_pc?code_station=%2204102400%22&size=5000&date_debut_prelevement=2019-01-01&date_fin_prelevement=2019-12-31&exact_count=true&format=json

**Comment by antonio-andrade** [comment]
Effectivement, il s'agit d'un bug de l'interface Swagger qui sera corrigé dans la prochaine version de l'API.
