### ISSUE TITLE
[API Hydrobiologie] Erreurs 500 / 406 dans les réponses de l'API

### ISSUE THREAD

**Issue by tbesse-oeb** [BRGM/hubeau#106]
Le serveur semble HS ?

https://hubeau.eaufrance.fr/api/vbeta/hydrobio/indices?code_departement=35&format=json&page=1&size=20 : Erreur 500

https://hubeau.eaufrance.fr/api/vbeta/hydrobio/stations_hydrobio.csv?size=20 : Erreur 406

**Comment by AnthonyDEBUR** [comment]
Je confirme le message de Timothée. Ces problèmes de serveur inaccessible sont récurrents (puis quelques minutes / heures après, la situation se rétabli).
