### ISSUE TITLE
[API Hydrobiologie] pb de date dans l'url

### ISSUE THREAD

**Issue by PBirchen** [BRGM/hubeau#107]
je souhaite extraire des indices dans un département donné. J'ai généré cette url:
`https://hubeau.eaufrance.fr/api/vbeta/hydrobio/indices?code_departement=53&code_indice=1000&fields=code_indice%2Ccode_station_hydrobio%2Cdate_prelevement%2Cresultat_indice%2Cunite_indice%2Ccode_departement%2Ccode_support%2Clibelle_support%2Ccode_qualification&format=json&page=1&size=1`
Le résultat me donne les données disponibles sans tenir compte de la date.
Si je veux ajouter une période pour les prélèvements (après 01/01/2019)
`https://hubeau.eaufrance.fr/api/vbeta/hydrobio/indices?code_departement=53&code_indice=1000&date_debut_prelevement=2019-01-01&fields=code_indice%2Ccode_station_hydrobio%2Cdate_prelevement%2Cresultat_indice%2Cunite_indice%2Ccode_departement%2Ccode_support%2Clibelle_support%2Ccode_qualification&format=json&page=1&size=1`
L'API me renvoie un message d'erreur.
```
<ErrorResource>
<code>Internal server error</code>
<message/>
</ErrorResource>
```
 Bug?

**Comment by tvilmus** [comment]
Bonjour, 
Merci pour ce signalement. 
Dans le courant du mois de juillet, nous passerons l'API en v1 et corrigerons ce bug.

**Comment by tvilmus** [comment]
Bonjour,  
L'API a été passée en v1, avec correction du problème :   
https://hubeau.eaufrance.fr/api/v1/hydrobio/indices?code_departement=53&code_indice=1000&fields=code_indice%2Ccode_station_hydrobio%2Cdate_prelevement%2Cresultat_indice%2Cunite_indice%2Ccode_departement%2Ccode_support%2Clibelle_support%2Ccode_qualification&format=json&page=1&size=1&date_debut_prelevement=2007-01-01  
renvoie 32 enregistrements.
