### ISSUE TITLE
[API hydrobiologie] profondeur d'accès aux résultats

### ISSUE THREAD

**Issue by AnthonyDEBUR** [BRGM/hubeau#109]
Bonjour,

Alors que la documentation de l'API fait mention d'une limitation de la profondeur d'accès aux résultats de 20 000 enregistrements, il me semble que la limitation réelle est de 10 000 enregistrements.

Exemple : 
https://hubeau.eaufrance.fr/api/vbeta/hydrobio/taxons?code_departement=&code_station_hydrobio=04195400&code_station_hydrobio=04195700&code_station_hydrobio=04195950&code_station_hydrobio=04196000&code_station_hydrobio=04196100&format=json&size=20

renvoie un code 206 avec seulement 11843 enregistrements

![image](https://user-images.githubusercontent.com/66001626/157418147-c7c37003-cbae-496f-a836-cdd903d93899.png)

**Comment by tvilmus** [comment]
Effectivement, la taille a été réduite à 10000 enregistrements maxi pour éviter les timeouts. Nous changeons la documentation.
