### ISSUE TITLE
[API Temperature] pas de données

### ISSUE THREAD

**Issue by fifphil** [BRGM/hubeau#110]
Bonjour,

Quand j'utilise les API, tout fonctionne bien.
Cependant, l'API Temperature n'a plus de données depuis longtemps.
Cela va-t-il changée ou est-elle abandonnée ?

Merci et bravo pour votre travail

**Comment by GrandFelix** [comment]
Bonjour,

les données sur le lien mentionné sont obsolètes. Existe-t-il une autre source pour connaître la température de l'eau en France ?

**Comment by fifphil** [comment]
J'allais dire la même chose. 
Les données du lien qui sont censées être les plus à jour datent de 2021 !

Où trouver des informations sur les températures de l'eau ?
