### ISSUE TITLE
[API hydrométrie] : Internal server error

### ISSUE THREAD

**Issue by AlainEaucea** [BRGM/hubeau#112]
Bonjour,
depuis hier (14/04/2022), certaines requêtes auprès de l'API renvoient la même erreur. Voici deux exemples testés avec l'interface du site Hub'eau :

sites hydrométriques - https://hubeau.eaufrance.fr/api/v1/hydrometrie/referentiel/sites?code_site=O200001*&format=json&size=20
liste des observations - https://hubeau.eaufrance.fr/api/v1/hydrometrie/observations_tr?code_entite=K003002010&date_debut_obs=2022-04-01&date_fin_obs=2022-04-05&grandeur_hydro=Q&size=20&timestep=60

La même réponse est :
{
  "code": "Internal server error",
  "message": "",
  "field_errors": null
}

**Comment by claustres** [comment]
A priori doublon de https://github.com/BRGM/hubeau/issues/94#issuecomment-1099912186.

**Comment by kab29** [comment]
Bonjour,
Erreur identique de mon côté depuis ce jour (a minima) sur un autre site :
https://hubeau.eaufrance.fr/api/v1/hydrometrie/observations_tr?code_entite=K003002010&date_debut_obs=2022-04-01&date_fin_obs=2022-04-05&grandeur_hydro=Q&size=20&timestep=60

**Comment by EmilieEPLoire** [comment]
Bonjour,
Je constate une erreur 500 sur l'API des stations depuis hier : 
https://hubeau.eaufrance.fr/api/v1/hydrometrie/referentiel/stations?code_station=K5712310&format=geojson&size=20

**Comment by tvilmus** [comment]
Bonjour, 
Le endpoint stations est de nouveau accessible.  
Toutes nos excuses pour ces dysfonctionnements dont nous recherchons activement les causes.

**Comment by vcloarec** [comment]
Bonjour,
Les requêtes que j'effectue auprès de l'API hydrométrie échoue.
Par exemple, une requête test : https://hubeau.eaufrance.fr/api/v1/hydrometrie/referentiel/stations?bbox=0,0,1,1&format=json&pretty&page=1&size=20

**Comment by tvilmus** [comment]
Bonjour,
Cela fonctionne chez moi...

**Comment by vcloarec** [comment]
Il s'avère que cela refonctionne... Peut-être a-t-il eu lieu une interruption temporaire ?

**Comment by claustres** [comment]
Nous observons sur nos serveurs des interruptions temporaires mais récurrentes du service depuis plusieurs semaines https://github.com/BRGM/hubeau/issues/94#issuecomment-1099912186. Notamment durant les weekends, c'est peut-être aussi lié à des surcharges temporaires.

**Comment by EmilieEPLoire** [comment]
Bonjour,
il semblerait que le service ne réponde pas ce matin.

Emilie

**Comment by kab29** [comment]
Bonjour, Je confirme.
