### ISSUE TITLE
[API Qualité de l'eau] Error: Internal Server Error

### ISSUE THREAD

**Issue by MAMECHE-Hamza** [BRGM/hubeau#113]
/vbeta/qualite_eau_potable/resultats_dis is down.

**Comment by axel584** [comment]
Bonjour,
L'adresse https://hubeau.eaufrance.fr/api/vbeta/qualite_eau_potable/resultats_dis?size=20 semble fonctionner de mon côté. Pouvez vous réessayer ?

Merci,

Axel Rousseau

**Comment by MAMECHE-Hamza** [comment]
Bonjour,

Effectivement, et je crois et le problème manifeste qu'on utilise le sort "asc" comme https://hubeau.eaufrance.fr/api/vbeta/qualite_eau_potable/resultats_dis?page=1&size=1&sort=asc

Merci,
Hamza Mameche

**Comment by tvilmus** [comment]
Bonjour, 
Fonctionnement normal de mon côté, même avec sort=asc. 
Je clos le ticket
