### ISSUE TITLE
Stations from referentiel not found in observations_tr

### ISSUE THREAD

**Issue by gutzbenj** [BRGM/hubeau#114]
Dear all,

I am currently trying to implement Hubeau into our library at [1]

My idea was to take the refentiel stations as basis to select from and then query observations_tr to get the corresponding values.

However when taking the first station from [2] which has the code_station "1011000101" and is also marked as  en_service and put that into the observations api like [3] I don't get any values. 

Can you tell me how the code_station from the stations listing is mapped to the code_entite that is used to query observations?

Thanks in advance!

Cheers
Benjamin

[1] https://github.com/earthobservations/wetterdienst
[2] https://hubeau.eaufrance.fr/api/v1/hydrometrie/referentiel/stations?format=json&pretty
[3] https://hubeau.eaufrance.fr/api/v1/hydrometrie/observations_tr?grandeur_hydro=Q&pretty&code_entite=1011000101

**Comment by bobeal** [comment]
Hi @gutzbenj,

It works if you use the `code_station` parameter instead. e.g., https://hubeau.eaufrance.fr/api/v1/hydrometrie/observations_tr?grandeur_hydro=Q&pretty&code_station=1011000101

**Comment by gutzbenj** [comment]
Dear @bobeal ,

thanks for the answer.

It appears to me that this doesn't work! If you check the results you will notice that they contain datasets wtih `code_station` being e.g. E635140201, Y011541001 or Y023401001, all but not the requested station 1011000101.

Am I doing something wrong?

Cheers
Benjamin

**Comment by bobeal** [comment]
This is strange.

I tried other stations (E640600202, 4030000201) and I get the expected results when querying with https://hubeau.eaufrance.fr/api/v1/hydrometrie/obs_elab?grandeur_hydro=Q&pretty&code_entite={code_station}

Don't know what is the problem with the first stations found in the results ... this is unfortunately beyond my knowledge of the API :(

**Comment by kab29** [comment]
Hi,
Internal server error (this day) on https://hubeau.eaufrance.fr/api/v1/hydrometrie/referentiel/stations
+
"Fetch error
Service Unavailable https://hubeau.eaufrance.fr/api/v1/hydrometrie/api-docs"
here : https://hubeau.eaufrance.fr/page/api-hydrometrie#console
It seems that the server is really unstable. Could you ask someone to work on it ? (more capacities, automatic alerts and reboots, log analysis, mirroring etc.)

**Comment by tvilmus** [comment]
Hi @kab29, 
You are using a free service that offers no guarantee of availability. We invite you to read the "[Conditions générales d'utilisation](https://hubeau.eaufrance.fr/page/conditions-generales)" and to use a service that better meets your expectations if Hub'Eau does not suit yours.

**Comment by gutzbenj** [comment]
Hi
> You can locate stations with data on a map here : https://hubeau.eaufrance.fr/sites/default/files/api/demo/hydro_tr.htm

Thanks for the answer! Is there also a way to get stations that have data via the stations api endpoint?

**Comment by tvilmus** [comment]
Unfortunately no...
The field 'en_service' shows if the station is still running but it does not guarantee that the station has real-time data (it can have other types of data)
