### ISSUE TITLE
[API Piézométrie] Absence de chronique depuis début juin

### ISSUE THREAD

**Issue by Lumkas** [BRGM/hubeau#116]
Bonjour,

Certaines stations ne renvoies plus de chroniques depuis début juin 2022.

Exemple : 
- https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques?code_bss=06995C0208/S1&date_debut_mesure=2022-05-01&sort=desc
- https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques?code_bss=06995C0271%2FS&date_debut_mesure=2022-05-01&sort=desc
- https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques?code_bss=07224X0102%2FS&date_debut_mesure=2022-05-01&sort=desc

Bien à vous
Lucas

**Comment by tvilmus** [comment]
Bonjour, 
Je vois des mesures au 30 juin et 1er juillet. Les données ne sont pas toujours disponibles immédiatement. Constatez-vous toujours un manque de données ?

**Comment by tvilmus** [comment]
Je clôt le ticket. N'hésitez pas à le ré-ouvrir si besoin
