### ISSUE TITLE
[API Hydrométrie] Comparaison HydroPortail et données élaborées API

### ISSUE THREAD

**Issue by francoistilmant** [BRGM/hubeau#118]
Bonjour,
Je compare les débits moyens journaliers de la station Y412204001 récupérés sur : 
- l'HydroPortail (en rouge sur la figure) : https://hydro.eaufrance.fr/stationhydro/Y412204001/series
- l'API Hydrométrie (données élaborées QmJ) (en vert sur la figure) : http://hubeau.eaufrance.fr/api/v1/hydrometrie/obs_elab?code_entite=Y412204001&size=20000&date_debut_obs_elab=2022-07-01&grandeur_hydro=QmJ&fields=code_station,date_obs_elab,resultat_obs_elab&sort=asc
- l'API Hydrométrie (observations temps réel (instantané) puis calcul du QmJ par nos soins) (en bleu sur la figure) : http://hubeau.eaufrance.fr/api/v1/hydrometrie/observations_tr?code_entite=Y412204001&size=20000&date_debut_obs=2022-07-01&grandeur_hydro=Q&fields=code_station,date_obs,resultat_obs&sort=asc

![Y412204001](https://user-images.githubusercontent.com/38126364/180840324-dd11b66b-b2f1-476b-a7c0-92bcd3e86dee.png)

Est-il normal d'observer des différences entre les courbes rouge (HydroPortail) et verte (API Hydro - données élaborées) ?
La source de données n'est-elle pas la même ? 

Merci d'avance de votre aide et encore merci pour la mise en place et la diffusion de ces outils.
François

**Comment by tvilmus** [comment]
Bonjour,  
Merci pour ce signalement.  
Non ces différences ne sont pas normales.  
L'API hydro_tr dispose maintenant des données corrigées affichant les mêmes valeurs que l'hydroportail (pic bas autour de 0,76 m3/s le 10 juillet).
![image](https://user-images.githubusercontent.com/28749963/183042529-58498bd7-8f10-49c3-9ad0-dc18465749fd.png)

Par contre l'API hydro_elab n'a pas pris en compte les corrections et continue d'afficher 0,82 m3/s le 10 juillet.  
Il y a sans doute un problème de prise en compte de certaines valeurs corrigées, nous investiguons de ce côté.

Bien cordialement,
Thierry

**Comment by francoistilmant** [comment]
Bonjour,
Merci de votre retour et pour la correction dans l'API.
La correction de données dans l'HydroPortail est-elle reportée immédiatement dans l'API Hydrométrie ou y a-t-il un délai pour que la correction soit prise en compte ?

Pour votre information, j'ai refait l'exercice de comparaison suite à votre message.
J'ai l'impression que les données élaborées sont désormais correctes (courbes rouge et verte confondues) mais que ce sont les données temps réel qui sont erronées (voir graphique ci-dessous) :

![Sans titre](https://user-images.githubusercontent.com/38126364/183054413-2fa03e7f-ffa9-489c-9734-4fc06df92f76.png)

Bien cordialement,
François

**Comment by tvilmus** [comment]
En effet, les données d'observations élaborées viennent d'être réinitialisées d'où leur correspondance avec les données de l'hydroportail
![image](https://user-images.githubusercontent.com/28749963/183050316-50acb430-5025-47a4-8add-63da6a806249.png)

Nous allons réinitialiser les données temps réel également. 

Les données temps réel sont mises à jour toutes les 2 minutes dans Hub'Eau (nouvelles données et données corrigées). On n'est pas toujours certain que les données corrigées soient tagguées comme telles dans la source de données, dans ce cas Hub'Eau ne voit pas qu'il y a eu une correction. C'est un point qu'il nous reste à discuter avec le SCHAPI.

**Comment by francoistilmant** [comment]
J'ai relancé une seconde fois ce jour mon exercice de comparaison et j'observe de légères différences entre API élaborée et HydroPortail (voir graphique ci-dessous).

Pourtant, lors de la comparaison de ce matin (voir mon précédent commentaire), les données étaient parfaitement superposées. Y a-t-il une explication à ce comportement ?  

![Sans titre2](https://user-images.githubusercontent.com/38126364/183079261-8e756652-aff3-43f2-a6f1-2dd8f1160970.png)

A quelle fréquence les données d'observations élaborées sont-elles réinitialisées ?

Encore merci pour votre temps et vos explications.
Bien cordialement,
François

**Comment by tvilmus** [comment]
Les données de débit temps réel ont été ré-initialisées pour la période avant le 19 juillet. 

C'est curieux qu'après ré-initialisation des données élaborées, elles deviennent légèrement différentes de celles d'Hydroportail...
Hub'eau interroge la PHYC deux fois par jour pour les observations élaborées : à 8h45 et 23h45.
