### ISSUE TITLE
[API QUALITÉ DE L'EAU POTABLE]

### ISSUE THREAD

**Issue by LYZOFR** [BRGM/hubeau#119]
Bonjour,

J'utilise le paramètre "fields" pour avoir uniquement certaines données pour resultats_dis.csv,  exemple : 

https://hubeau.eaufrance.fr/api/vbeta/qualite_eau_potable/resultats_dis.csv?code_prelevement=08000115068&fields=libelle_parametre_maj%2Cresultat_alphanumerique%2Climite_qualite_parametre%2Creference_qualite_parametre%2Clibelle_unite

**Export du fichier CSV :** 
"libelle_parametre_maj";"resultat_alphanumerique";"libelle_unite";"limite_qualite_parametre";"reference_qualite_parametre"
"CHLORE TOTAL";"0,92";"mg(Cl2)/L";"";""
"PH ";"7,6";"unité pH";"";">=6,5 et <=9 unité pH"
"CHLORE LIBRE";"0,91";"mg(Cl2)/L";"";""
"BACT. AÉR. REVIVIFIABLES À 36°-44H";"<1";"n/mL";"";""

J'ai constaté que le fichier CSV généré est différent sur l'ordre des colonnes par rapport à l'ordre du champ "fields" (exemple le libelle_unite se retrouve en 3ieme position dans le fichier CSV).
Dans mon code, j'ai pris l'ordre du fichier CSV et non l'ordre du paramètre "fields" pour le traitement des données.
Est ce que cet ordre restera stable ? quelle est la logique de l'ordre du fichier CSV sur le paramètre "fields" ? 

Merci pour votre aide.
Cyril

**Comment by tvilmus** [comment]
Bonjour Cyril, 
Les colonnes du fichier CSV apparaissent toujours dans le même ordre et ne tiennent pas compte de l'ordre indiqué dans le paramètres fields. Ce paramètre fields ne sert qu'à préciser les champs que l'on veut voir apparaître, mais n'a pas d'impact sur leur ordre.  
Il n'est pas prévu de modifier les champs lors du prochain passage de l'API en version 1 donc l'ordre des colonnes des réponses CSV devrait rester stable. Il semble préférable tout de même de se baser sur l'entête de colonne plutôt que sur le numéro de colonne...

Bien cordialement,  
Thierry

**Comment by LYZOFR** [comment]
Bonjour Thierry,

Merci pour ta réponse et tes conseils.

Bien cordialement

Cyril

Le 2022-07-28 10:17, Thierry Vilmus a écrit :

> Bonjour Cyril,
> Les colonnes du fichier CSV apparaissent toujours dans le même ordre et 
> ne tiennent pas compte de l'ordre indiqué dans le paramètres fields. Ce 
> paramètre fields ne sert qu'à préciser les champs que l'on veut voir 
> apparaître, mais n'a pas d'impact sur leur ordre.
> Il n'est pas prévu de modifier les champs lors du prochain passage de 
> l'API en version 1 donc l'ordre des colonnes des réponses CSV devrait 
> rester stable. Il semble préférable tout de même de se baser sur 
> l'entête de colonne plutôt que sur le numéro de colonne...
> 
> Bien cordialement,
> Thierry
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>



Links:
------
[1] https://github.com/BRGM/hubeau/issues/119#issuecomment-1197817668
[2]
