### ISSUE TITLE
[API Indicateur de services] : pas de résultat 

### ISSUE THREAD

**Issue by nworr** [BRGM/hubeau#12]
Bonjour

Je réalise quelques tests sur l'API indicateur de services, mais le résultat est toujours vide 
https://hubeau.eaufrance.fr/api/v0/indicateurs_services/indicateurs?size=20&code_indicateur=P101.1
ou https://hubeau.eaufrance.fr/api/v0/indicateurs_services/services?code_commune=17300&size=3&

Question plus large : les données sont elles semblables à ce qu'on peut récupérer sur http://www.services.eaufrance.fr/donnees/telechargement
ou  http://www.data.eaufrance.fr/jdd/a8d7a630-b33d-4c0b-a865-ecbe20360de5
 (sachant que la page www.services.eaufrance.fr/donnees/telechargement indique une mise à jour hebdomadaire)

Merci 
Raphaël

**Comment by tvilmus** [comment]
Bonjour,

Effectivement, nous constatons un dysfonctionnement de notre API indicateurs de services. Nous travaillons à la résolution du problème et vous tiendrons informés.

Oui, les données proviennent de http://www.services.eaufrance.fr/donnees/telechargement

Bien cordialement,
Thierry

**Comment by MahdiSMIDA** [comment]
Bonjour, 
Le problème est résolu

Merci
Mahdi
