### ISSUE TITLE
API Hydrométrie : erreur 500 sur référentiel\stations

### ISSUE THREAD

**Issue by EmilieEPLoire** [BRGM/hubeau#120]
Bonjour,

je n'arrive plus à interroger le service référentiel sur un code station ou un code site : 
https://hubeau.eaufrance.fr/api/v1/hydrometrie/referentiel/stations?code_site=K5552300&format=geojson&size=2000
https://hubeau.eaufrance.fr/api/v1/hydrometrie/referentiel/stations?code_station=K555230001%20&format=geojson&size=2000

ça fonctionnait ce matin.
Merci d'avance,

Emilie

**Comment by tvilmus** [comment]
Bonjour,  
Merci pour le signalement. L'information a été transmise à l'équipe en charge de l'infra.  
Cordialement, 
Thierry

**Comment by tbesse-oeb** [comment]
Bonjour,

Je rencontre le même problème aujourd'hui : l'API répond bien pour les sites mais pas pour les stations...
