### ISSUE TITLE
API Hydrométrie : erreur 500 sur référentiel\stations (réouverture)

### ISSUE THREAD

**Issue by tbesse-oeb** [BRGM/hubeau#126]
Bonjour,

Je rencontre le même problème aujourd'hui : l'API répond bien pour les sites mais pas pour les stations...

_Originally posted by @tbesse-oeb in https://github.com/BRGM/hubeau/issues/120#issuecomment-1228341067_

**Comment by marqisoft** [comment]
Bonjour,

L'erreur 500 persiste.

En export CSV :
https://hubeau.eaufrance.fr/api/v1/hydrometrie/referentiel/stations.csv?code_station=K269821001&size=20
on obtient une "Whitelabel Error Page" :
<< There was an unexpected error (type=Internal Server Error, status=500). >>

OU en export JSON :
https://hubeau.eaufrance.fr/api/v1/hydrometrie/referentiel/stations?code_station=K269821001&format=json&size=20

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<ErrorResource>
<code>Internal server error</code>
<message/>
</ErrorResource>

Autre constat :
Avec l'interface web d'HubEau, quand on saisit plus d'une station, il génère une URL différente d'avant.
Maintenant, de type:
...?code_station=K338201001&code_station=P011501001&size=20 (AVEC le champ code_station qui se répète!)
Alors qu'avant, tous les codes se suivaient dans le même champ (codes séparés par une virgule), ex.:
...?code_station=K269821001,K277312001,K298191001,K322201001,K338201001,P011501001&size=5000
Je signale ce changement car ce pourrait être une cause, s'il n'est pas encore entièrement géré et intégré ?...

En espérant que ce problème peut être résolu facilement & rapidement,
A+

**Comment by EmilieEPLoire** [comment]
Bonjour,

erreur 500 constatée ce matin.

Emilie

**Comment by Supp-Hubeau** [comment]
Clôture du ticket. N'hésitez pas à le réouvrir si besoin.

Cordialement,
L'équipe Hub'eau
