### ISSUE TITLE
API qualité eau potable

### ISSUE THREAD

**Issue by BenjaminBULLE** [BRGM/hubeau#128]
Bonjour,

j'ai développé cette appli pour visualiser la qualité de l'eau potable à l'échelle d'un département (de son choix).

https://bullebenjamin.shinyapps.io/QualitAEP/?_ga=2.261022285.1962946082.1662969175-185703638.1662152799

Pour relier l'ensemble des communes desservies à la qualité de l'eau potable du captage analysé, je fais une jointure entre /vbeta/qualite_eau_potable/communes_udi et /vbeta/qualite_eau_potable/resultats_dis.

Mon problème est qu'il n'est pas possible d'appeler que les UDI du département choisi pour faire cette jointure (il n'y a pas de paramètre "nom_departement" ou "code_departement" pour /vbeta/qualite_eau_potable/communes_udi) je me retrouve donc à devoir télécharger toute les udi de France ce qui se limite à 20 000 lignes (soit jusqu'au département 38 max).

Je ne peux donc pas faire fonctionner mon appli pour tous les départements au delà de 38 (isère).

Serait il possible d'ajouter ce champ pour faire une requête?

merci

Benjamin

**Comment by BenjaminBULLE** [comment]
Accessoirement l'API qualité de l'eau potable renvoie un code erreur 500.

**Comment by antonio-andrade** [comment]
Les données ouvertes consommées par l'API (https://www.data.gouv.fr/fr/datasets/resultats-du-controle-sanitaire-de-leau-distribuee-commune-par-commune/) n'intègrent pas les code/libellé des départements d'implantation des unités de distribution (UDI)

Pour répondre à votre besoin, vous pouvez d'abord utiliser l'API Découpage Administratif - (API Geo) fournie par la DINUM (https://api.gouv.fr/les-api/api-geo) pour lister les communes d'un département. Par exemple, l'url https://geo.api.gouv.fr/departements/92/communes?limit=100 renvoie les communes du département des Hauts-de-Seine. La réponse de l'API fournit la liste des codes Insee d'un département. Cette liste peut être utilisée pour lister les UDI en interrogeant l'API Hub'Eau. Ainsi, la liste des UDI des Hauts-de-Seine en 2020 est obtenue via l'url https://hubeau.eaufrance.fr/api/vbeta/qualite_eau_potable/communes_udi?annee=2020&code_commune=92002,92004,92007,92009,92012,92014,92019,92020,92022,92023,92024,92025,92026,92032,92033,92035,92036,92040,92044,92046&size=100

Actuellement, la version beta de l'API Hub'Eau Qualité de l'eau potable limite le nombre de codes Insee du critère de recherche `code_commune` à 20 items. Nous allons étudier la possibilité d'augmenter cette limite pour la version stable de l'API.

**Comment by BenjaminBULLE** [comment]
Bonjour,

Je vous remercie pour votre réponse.

Effectivement, je peux avoir la liste des codes insee des communes où même
tout simplement faire une requête en demandant tous les codes communes
commençant par le code du département ciblé mais HUBeau limite à 20 le
nombre d'entrée là où il y a 400 communes par département.

Sur d'autre API comme celle de la qualité de l'eau, intègrent les code
départements, c'est pour ça que je demandais au cas où.


Cordialement.


Le mar. 4 oct. 2022 à 10:14, antonio-andrade ***@***.***> a
écrit :

**Comment by Supp-Hubeau** [comment]
Clôture du ticket. N'hésitez pas à le réouvrir si besoin.

Cordialement,
L'équipe Hub'eau
