### ISSUE TITLE
[API Hydrobiologie] observations dupliquées pour endpoint « taxons »

### ISSUE THREAD

**Issue by PascalIrz** [BRGM/hubeau#129]
Bonjour,

J’effectue des tests en vue d’ajouter au package R [{hubeau}](https://github.com/inrae/hubeau) la possibilité de requêter l’API « Hydrobiologie ».

Pour ce qui est des données sur les poissons, certains des enregistrements renvoyés par l'API semblent dupliqués. 

Exemple : échantillonnage sur la commune 35051, prélèvement n°04204300200706044, des anguilles (code_appel_taxon 2038) : 
[https://hubeau.eaufrance.fr/api/v1/hydrobio/taxons?code_appel_taxon=2038&code_commune=35051&code_prelevement=04204300200706044&code_support=4&format=json&size=20](https://hubeau.eaufrance.fr/api/v1/hydrobio/taxons?code_appel_taxon=2038&code_commune=35051&code_prelevement=04204300200706044&code_support=4&format=json&size=20)
renvoie deux éléments identiques, chacun indiquant "resultat_taxon": 13
Ces éléments permettent d’identifier le prélèvement correspondant dans la base d’origine Aspe ("libelle_liste_faune_flore": "pre_id16026"). Or, dans Aspe, pour ce numéro de prélèvement l’effectif capturé est de 13 anguilles, et non de 26.

Plus généralement, sur cette même commune
[https://hubeau.eaufrance.fr/api/v1/hydrobio/taxons?code_commune=35051&format=json&size=20](https://hubeau.eaufrance.fr/api/v1/hydrobio/taxons?code_commune=35051&format=json&size=20)
on obtient au total 3162 éléments. Tous ceux issus de la base Aspe semblent doublonnés. Il semble également que certains des éléments relatifs aux macrophytes sont quadruplés (Sur ce point je n’ai pas fait de vérifications poussées).

Merci pour votre travail sur ces API qui répondent à de nombreux besoins.

**Comment by antonio-andrade** [comment]
Bonjour Pascal,

Tout d'abord, merci pour ce signalement. L'API Hydrobiologie diffuse effectivement de faux doublons. Les taxons et les indices sont dupliqués dès lors qu'il existe des conditions environnementales associées à l'opération de prélèvement. Nous travaillons à la correction de cette anomalie dans les plus brefs délais.

**Comment by Supp-Hubeau** [comment]
Bonjour,

Une [nouvelle version de l'API Hydrobiologie](https://hubeau.eaufrance.fr/news/nouvelle-version-de-lapi-hydrobiologie) a été déployée.  
L'anomalie signalée ici fait partie de celles corrigées par cette version.  
A noter, la suppression des doublons entraine une diminution du volume de données diffusées (2 M d’observations de taxons en moins, 100 K indices en moins)

L'équipe Hub'eau

**Comment by PascalIrz** [comment]
Merci !
