### ISSUE TITLE
[API Piézométrie] fonction chronique

### ISSUE THREAD

**Issue by stephanecrepont** [BRGM/hubeau#130]
Bonjour,

J'avais codé une requête automatique de la piézométrie sur quelques piézomètres normands
Celle-ci a bien fonctionné tout l'été, mais plus depuis 1 ou 2 mois:
- requête sur 6 à 10 ouvrages
- profondeur de 2 mois max
- pas d'erreur retournée, seulement une requête vide
`https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques?code_bss=01252X0011/S1,01252X0011/S1,01805X0036/S1,01805X0036/S1,01801X0010/S1,01794X0035/S1,01515X2015/S1,01245X0010/S1,01487X0001/S1,01487X0001/S1,01487X0001/S1,01487X0001/S1,00773X0002/S1&date_debut_mesure=2022-09-30&date_fin_mesure=2022-12-20&fields=code_bss,date_mesure,niveau_nappe_eau&sort=asc&page=1&size=10000`
- la fonction marche très bien sur **une seule station**
`https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques?code_bss=01252X0011/S1&date_debut_mesure=2022-09-30&date_fin_mesure=2022-12-20&fields=code_bss,date_mesure,niveau_nappe_eau&sort=asc&page=1&size=10000`
J'ai essayé du coup la fonction chronique_tr à la place par curiosité, et celle-ci fonctionne bien même sur une liste de station donc ça ne viendrait a priori pas du code!

**Comment by Supp-Hubeau** [comment]
Traité dans le cadre de https://github.com/BRGM/hubeau/issues/132
Clôture du ticket. 

Cordialement,
L'équipe Hub'eau
