### ISSUE TITLE
API Hub'Eau - Piézométrie

### ISSUE THREAD

**Issue by rimyou22** [BRGM/hubeau#132]
Bonjour,
Nous voulons utiliser l'api pour lister les chroniques piézométriques avec plusieurs "**code_bss**" séparés par une virgule. Mais l'api ne renvoie pas de résultat.

Exemple :
https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques?code_bss=05068X0028/SP010,05068X0054/F&page=1&size=20 => KO

Par contre si on appelle l'api avec un seul "**code_bss**", l'api renvoi bien un résultat.
Exemple :
https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques?code_bss=05068X0028/SP010&page=1&size=20 => OK
https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques?code_bss=05068X0054/F&page=1&size=20 => OK

Est-ce que c'est une erreur ou si le fonctionnement normal?
Merci par avance

**Comment by EmilieEPLoire** [comment]
Bonjour,

je confirme le disfonctionnement. Pourtant, cela fonctionnait avant. Est-ce une mise à jour ? 
Merci,

Emilie BIGORNE

**Comment by abelhenriot** [comment]
Je confirme une nouvelle fois le changement de comportement de l'API.
@tvilmus : est ce que tu sais dire si le ticket pourrait être pris en compte ?
Abel

**Comment by b-lardeau** [comment]
Bonjour,

Ce comportement est lié à une migration technique réalisée en décembre.
Il s'agit effectivement d'une anomalie que nous allons corriger.

Pour l'heure, la seule solution de contournement consiste à itérer avec des valeurs unitaires.

Pour information, une anomalie du même type affecte le endpoint _analyses_ de l'API _qualité des nappes d'eau souterraines_.

B. Lardeau

**Comment by Supp-Hubeau** [comment]
Bonjour,

L'anomalie a été corrigée.  
La recherche avec plusieurs codes séparés par des virgules est de nouveau possible.
Merci pour votre patience.

L'équipe Hub'eau

**Comment by rimyou22** [comment]
Bonjour,
Merci @**Supp-Hubeau** pour votre réactivité.
La correction fonctionne très bien.
Y.Rimani
