### ISSUE TITLE
[API Hydrométrie] données élaborées en doublonnées au 1er de chaque mois

### ISSUE THREAD

**Issue by AnthonyDEBUR** [BRGM/hubeau#133]
Bonjour,

Lorsque j'exécute la requête suivante : https://hubeau.eaufrance.fr/api/v1/hydrometrie/obs_elab.csv?code_entite=J930061101&size=20000, la requête renvoi deux résultats avec des valeurs de débit journaliers différents pour les 1er de chaque mois.

Par ex. dans le résultat de requête, pour la date du 1er décembre 2022, on obtient un débit journalier de 61290 L/s pour la donnée élaborée (colonne date_prod) le 02/12/2022 et de 139672 L/s pour la donnée de la même date mais élaborée le 1er janvier 2023.

Cordialement,
Anthony

**Comment by tvilmus** [comment]
Bonjour,  

Attention l'opération obs_elab fournit 2 types de grandeurs hydrométriques : les débits moyens journaliers (QmJ) et mensuels (QmM).  Si vous ne filtrez pas la grandeur hydrométrique avec le paramètre grandeur_hydro_elab, vous recevez à la fois les paramètres QmJ et QmM :  
https://hubeau.eaufrance.fr/api/v1/hydrometrie/obs_elab?code_entite=J930061101&date_debut_obs_elab=2022-12-01&date_fin_obs_elab=2022-12-03&fields=grandeur_hydro_elab,date_obs_elab,resultat_obs_elab  

![image](https://user-images.githubusercontent.com/28749963/217228868-b4c3be8e-8d1e-4338-a522-7324859ca330.png)

Les QmM sont à la date du 1er de chaque mois.

**Comment by AnthonyDEBUR** [comment]
Merci,

Effectivement l'erreur vient de ma mauvaise lecture.
