### ISSUE TITLE
[API Qualité des cours d'eau] Erreur 500 sur `/v2/qualite_rivieres/analyse_pc`

### ISSUE THREAD

**Issue by bobeal** [BRGM/hubeau#134]
Bonjour,

Depuis quelques jours, nous avons des erreurs 500 lors des appels à l'API de liste des analyses physicochimiques.

Par exemple :

```
http https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/analyse_pc?code_station=06188930
```

Donne la réponse suivante :

```
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Origin: *
Connection: close
Content-Encoding: gzip
Content-Length: 78
Content-Type: application/json
Date: Mon, 13 Feb 2023 05:08:12 GMT
Server: Apache
Vary: Origin,Accept-Encoding,Access-Control-Request-Method,Access-Control-Request-Headers

{
    "code": "Internal server error",
    "field_errors": null,
    "message": ""
}
```

Également reproduit en passant directement par la console de l'API (https://hubeau.eaufrance.fr/page/api-qualite-cours-deau#/physicochimie/analyse_pc).

**Comment by b-lardeau** [comment]
Bonjour,

Merci pour votre message.  
L'API a effectivement rencontré une anomalie de fonctionnement ces derniers jours.  
Elle vient d'être relancée.

B. Lardeau

**Comment by bobeal** [comment]
Bonjour,

Effectivement, c'est de nouveau opérationnel, merci !
