### ISSUE TITLE
API Qualité des cours d'eau - signification des champs date_debut_maj date_fin_maj

### ISSUE THREAD

**Issue by AnthonyDEBUR** [BRGM/hubeau#135]
Bonjour,

Pouvez-vous préciser dans la notice la signification des champs date_debut_maj et date_fin_maj ?

J'avais cru comprendre qu'il s'agissait de filtres sur al date d'intégration des données sous Naïades mais date_debut_maj semble ne filtrer aucune données et date_fin_maj à l'inverse ne renvoie aucune donnée dès qu'on lui passe une valeur en argument.

Exemple  : 

https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/analyse_pc?code_parametre=1340&code_station=03174000&size=20 renvoie 1707 résultats avec des dates de prélèvements allant de 1971 à 2022

https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/analyse_pc?code_parametre=1340&code_station=03174000&date_debut_maj=2020-01-01&size=20 renvoi le même nombre de résultats (1707) 

https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/analyse_pc?code_parametre=1340&code_station=03174000&date_fin_maj=2020-01-01&size=20 ne renvoi aucun résultat

Merci pour vos éclairages.

**Comment by b-lardeau** [comment]
Bonjour,

Les filtres **date_debut_maj** et **date_fin_maj** s'appliquent sur le champ date_maj_analyse : 

Par exemple :  
https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/analyse_pc?code_parametre=1340&code_station=03174000&date_debut_maj=2022-08-01&size=20  
Retourne 7 valeurs réparties comme suit :   
- 2022-08-06 : 2
- 2022-09-04 : 3
- 2022-09-18 : 2

https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/analyse_pc?code_parametre=1340&code_station=03174000&date_debut_maj=2022-09-01&size=20  
N'en retourne plus que 5.

De la même manière :   
https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/analyse_pc?code_parametre=1340&code_station=03174000&date_fin_maj=2022-08-01&size=20   
Ne retourne plus que 1700 valeurs et non 1707.

Espérant avoir éclairci le sujet.  
Cordialement.

**Comment by antonio-andrade** [comment]
Bonjour,

`date_maj_analyse` correspond bien à la date d'import de l'analyse dans la base Naïades. Celle-ci est alimentée par annule et remplace de tout ou partie des données collectées par une Agence de l'eau ou un Office de l'eau. La majorité des agences/offices annulent et remplacent l'intégralité de leurs données à chaque alimentation. La date de maj est alors la même pour toutes les analyses importées. Seule l'agence Rhône-Méditerranée-Corse et, bientôt, Seine-Normandie et Loire-Bretagne, alimente Naïades avec les données modifiées tous les 15j. Les analyses collectées par cette agence ont ainsi des date de maj différentes.

Bien cordialement,

**Comment by AnthonyDEBUR** [comment]
Merci
