### ISSUE TITLE
[API Qualité des nappes d'eau souterraine] Nombre de résultats aléatoire

### ISSUE THREAD

**Issue by dchatry** [BRGM/hubeau#14]
Bonjour,

Je rencontre un problème lors de l'interrogation de l'API *Qualité des nappes d'eau souterraine*, le nombre de résultats attendus (attribut **count**) varie constamment pour les mêmes paramètres, par exemple : 
http://hubeau.eaufrance.fr/api/v1/qualite_nappes/analyses?code_param=1340&size=20&date_debut_prelevement=2017-01-01&date_fin_prelevement=2017-06-30

L'attribut **count** varie de 8831 à 8670.

![hubeau_issue](https://user-images.githubusercontent.com/5067998/49862284-24757c80-fdfe-11e8-8be5-055891894c5f.gif)

Pouvez-vous résoudre le problème ou me dire comment le contourner ?

Merci par avance.

**Comment by tvilmus** [comment]
Bonjour,

Merci de nous avoir signalé ce problème, que nous reproduisons.
Nous utilisons plusieurs copies des données pour augmenter la sécurité et les temps de réponse mais il semble y avoir une désynchronisation quelque part. Nous investiguons...

Bien cordialement,
Thierry

**Comment by tvilmus** [comment]
Bonjour,

Le problème de désynchronisation a été corrigé. La requête que vous citez en exemple renvoie maintenant toujours 11995 résultats.

Bien cordialement,
Thierry

**Comment by dchatry** [comment]
Bonjour,

Merci, effectivement le problème a l'air d'être résolu !
