### ISSUE TITLE
[API Ecoulement des cours d'eau] Passage en version stable

### ISSUE THREAD

**Issue by antonio-andrade** [BRGM/hubeau#142]
L'évolution de la version beta vers la version stable 1.0 de l'[API Ecoulement des cours d'eau](https://hubeau.eaufrance.fr/page/api-ecoulement) est planifiée le **mardi 23/05/2023 à la mi-journée**. La version beta restera disponible jusqu'au vendredi 26/05/2023.

Le moment venu, veillez à modifier le paramètre *version* présent dans les URL d'interrogation de l'API. En pratique,

L'URL actuelle ...
https://hubeau.eaufrance.fr/api/vbeta/ecoulement/observations?format=json&code_region=76&date_observation_min=2022-01-01&date_observation_max=2022-12-31&size=20

... doit évoluer vers ...
https://hubeau.eaufrance.fr/api/v1/ecoulement/observations?format=json&code_region=76&date_observation_min=2022-01-01&date_observation_max=2022-12-31&size=20

> L'équipe Hub'Eau

**Comment by Supp-Hubeau** [comment]
La version stable 1.0 de l'[API Ecoulement des cours d'eau](https://hubeau.eaufrance.fr/page/api-ecoulement) a bien été déployée ce jour.

Cordialement
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
La version bêta de l'[API Ecoulement des cours d'eau](https://hubeau.eaufrance.fr/page/api-ecoulement) n'est désormais plus accessible.

Cordialement
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Passage en version 1 terminé. Clôture.

Cordialement
L'équipe Hub'eau
