### ISSUE TITLE
[API Piézométrie] bug avec paramètre bbox ?

### ISSUE THREAD

**Issue by AnthonyDEBUR** [BRGM/hubeau#144]
Bonjour,

Quand j'exécute la requête suivante : https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/stations?size=10&bbox1=-3.03018376325782&bbox2=47.3232352809044&bbox3=-0.952777911547637&bbox4=48.4031769229588 je m'attends à récupérer les piézo de l'emprise du bassin de la Vilaine. Hors la requête semble renvoyer l'ensemble des données disponibles au niveau national.

Est-ce une mauvaise syntaxe de ma part ou un bug dans la fonctionnalité de l'API ?

Bien cordialement

**Comment by tvilmus** [comment]
Bonjour,  
La syntaxe correcte est :  
https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/stations?size=10&bbox=-3.03018376325782,47.3232352809044,-0.952777911547637,48.4031769229588  

Cordialement,
Thierry

**Comment by AnthonyDEBUR** [comment]
Merci
