### ISSUE TITLE
[API Poisson] Date de maj de données ASPE ?

### ISSUE THREAD

**Issue by JulienRtf** [BRGM/hubeau#148]
Bonjour,

Je travaille actuellement sur une remontée de données ASPE grâce à l'API Poisson v1.0.

Je constate qu'en 2023 je n'ai aucune donnée ASPE remontée alors que si je me connecte sur https://aspe.eaufrance.fr/, j'ai bien des données en 2023.

J'en conclue que l'API fonctionne sur une copie de la base ASPE ? Si oui, de quand date la dernière copie et quelle est la fréquence de maj de cette copie ?

Merci pour votre aide
Julien

**Comment by Supp-Hubeau** [comment]
Bonjour,

Les données ont été actualisées.

Cordialement
L'équipe Hub'eau

**Comment by JulienRtf** [comment]
Bonjour

Merci pour la réactivité. Requête passée ce matin et tout semble fonctionner !

Pour mon information, des maj automatisées régulières de cette base attaquée par l'API sont elles prévues ou est-ce uniquement manuel ?

Cordialement
Julien RAITIF

**Comment by Supp-Hubeau** [comment]
Bonjour,

Merci pour votre retour.
Une évolution de l'API est en cours de préparation (trois endpoints supplémentaires), la chaîne d'alimentation, sera améliorée à cette occasion.

Cordialement
L'équipe Hub'eau

**Comment by JulienRtf** [comment]
Très bien. Merci !
