### ISSUE TITLE
Tutoriel utilisation des API avec QGIS information #2 by tvilmus was closed on Jul 5, 2022

### ISSUE THREAD

**Issue by cesteve1904** [BRGM/hubeau#149]
Bonjour, 
J'aimerais utiliser les données Hub'eau dans mon projet QGIS. 
Je n'arrive pas à comprendre comment générer les URL des API. 
Un tutoriel est il disponible ? 

Merci d'avance de votre aide

**Comment by antonio-andrade** [comment]
Bonjour,
Vous pouvez utiliser les API Hub'Eau depuis QGIS en vous basant sur un échange sur georezo.net, https://georezo.net/forum/viewtopic.php?id=129011 Seules les données geojson diffusées par certaines API pourront être chargées dans QGIS. Sans automatisation des échanges de données, les couches seront limitées à 20000 entités.
Bien cordialement,

**Comment by cesteve1904** [comment]
> 

Oui j'ai bien vu cette page.
Quelque chose m'échappe surement, ou peut etre la complexité du site mais je ne comprends pas comment générer des lien geojson...

**Comment by Supp-Hubeau** [comment]
Bonjour,

La paramètre _format_ permet d'obtenir du GeoJSON

https://hubeau.eaufrance.fr/api/v1/qualite_nappes/stations?format=geojson&num_departement=23&size=20

Il se peut cependant que le format GeoJSON ne soit pas implémenté, dans ce cas cette syntaxe retour des données en JSON.

L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Bonjour,

Nous clôturons le ticket. N'hésitez pas à le réouvrir si besoin.

Cordialement,
L'équipe Hub'eau
