### ISSUE TITLE
[API Hydrométrie] Récupération données élaborées au niveau du site selon calendrier HydroPortail

### ISSUE THREAD

**Issue by francoistilmant** [BRGM/hubeau#150]
Bonjour,
Lorsque je fais une requête de données élaborées (QmJ) sur un site, l'API me retourne les données pour l'ensemble des stations du site. 

Ex : <https://hubeau.eaufrance.fr/api/v1/hydrometrie/obs_elab?code_entite=A1160030&size=20000&date_debut_obs_elab=2023-07-17&grandeur_hydro=QmJ&fields=code_site,code_station,date_obs_elab,resultat_obs_elab&sort=asc> me renvoie les données des stations A116003002 et A116003004.

Dans l'HydroPortail, le calendrier permet de donner une information sur la station à utiliser au niveau du site (Ex : <https://www.hydro.eaufrance.fr/sitehydro/A1160030/calendrier>). 

Est-il possible d'obtenir la chronique du site telle qu'émise par HydroPortail (sélection de la station à utiliser) à partir de l'API ?
Merci d'avance de votre retour.

**Comment by antonio-andrade** [comment]
Bonjour,

Vous pouvez renseigner un code site ou un code station pour le paramètre `code_entite` Ainsi, les données de la station `A116003002` peuvent être récupérées avec l'URL de téléchargement https://hubeau.eaufrance.fr/api/v1/hydrometrie/obs_elab?code_entite=A116003002&size=20000&date_debut_obs_elab=2023-07-17&grandeur_hydro=QmJ&fields=code_site,code_station,date_obs_elab,resultat_obs_elab&sort=asc 

Bien cordialement,

**Comment by francoistilmant** [comment]
Bonjour,
Merci du retour. J'avais bien noté cette possibilité.

Ma question concerne plutôt la sélection de la station à récupérer si je souhaite avoir l'information au niveau du site. 
Cette information est contenue dans le calendrier sur HydroPortail.
Est-il possible de consulter ce calendrier à partir de l'API ?
Bien cordialement

**Comment by antonio-andrade** [comment]
Le endpoint `stations` permet d'obtenir la description des stations d'un site. Cette description comprend la période d'ouverture de la station. Malheureusement, dans le cas présent, le site est associé à deux stations en service en 2023.

https://hubeau.eaufrance.fr/api/v1/hydrometrie/referentiel/stations?code_site=A1160030&format=json&size=20

**Comment by tvilmus** [comment]
Bonjour, 
L'API Hub'eau n'a pas connaissance des informations de calendrier... 
Les seules actions possibles sont celles décrites par Antonio.  
Cordialement,
Thierry

**Comment by Supp-Hubeau** [comment]
Bonjour,

Nous clôturons le ticket. N'hésitez pas à le réouvrir si besoin.

Cordialement,
L'équipe Hub'eau
