### ISSUE TITLE
API Hub'Eau - Qualité physico-chimique des cours d'eau

### ISSUE THREAD

**Issue by Essaadi93** [BRGM/hubeau#152]
Hello,

Je me permets de récuperer des données d'une journée depuis l'api "/v2/qualite_rivieres/analyse_pc.csv" mais ce dernier contient la notion du profondeur ( profondeur = size* page) qui ne dépasse pas 20000.
pour avoir la données d'une journée le response header retourne l'url next (la suite de la données page 2) mais il y a deux elements étrange: 

- la profendeur qui bloque la recherche de la données.
- quand je fait la comparaison entre la page 1 et page 2 en mettant le size 10000 dans la page 2 je constate qui il y a une duplication.

quelqu'un entre vous a rencontré ce genre de problème? ou il a pu reussir à récuperer de la données depuis cette API.

merci de me faire un retour.

**Comment by Supp-Hubeau** [comment]
Bonjour,

Pourriez-vous nous indiquer plus précisément l'URL utilisée pour votre extraction ?

Merci d'avance.

L'équipe Hub'eau

**Comment by Essaadi93** [comment]
Bonjour,

voila l'url : https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/analyse_pc.csv

Merci.

**Comment by Supp-Hubeau** [comment]
Bonjour,

Nous ne reproduisons pas le problème décrit.
Ci-dessous quelques exemples.

#### Sous la barre des 20 000 réponses

a. https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/analyse_pc.csv?code_station=01057000
Fichier avec entête + 1000 enregistrements
b. https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/analyse_pc.csv?code_station=01057000&size=10000
Fichier avec entête + 9642 enregistrements
c. https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/analyse_pc.csv?code_station=01057000&size=5000
Fichier avec entête + 5000 enregistrements
d. https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/analyse_pc.csv?code_station=01057000&size=5000&page=2
Fichier avec entête + 4642 enregistrements
e. https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/analyse_pc.csv?code_station=01057000&size=5000&page=3
Fichier vide

Lorsqu'on assemble c. et d. on retrouve bien le contenu de b.

#### Résultat avec plus de 20 000 enregistrements (99 581 réponses donc 50 pages de 2000 rép)
a. https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/analyse_pc.csv?code_station=01004000
Fichier avec entête + 1000 enregistrements
b. https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/analyse_pc.csv?code_station=01004000&size=2000
Fichier avec entête + 2000 enregistrements
c. https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/analyse_pc.csv?code_station=01004000&size=2000&page=2
Fichier avec entête + 2000 enregistrements
d. https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/analyse_pc.csv?code_station=01004000&size=2000&page=11
Erreur : ValidatePageDepth

Pour ce second cas, il devient nécessaire d’affiner la recherche par date, paramètre ou autre.
Le comportement obtenu est identique avec le format json.

Nous restons disponibles pour examiner un cas plus spécifique si besoin.

L'équipe Hub'eau

**Comment by Essaadi93** [comment]
Bonjour,

Merci de votre retour, mon besoin sera de récuperer la données d'une journée en se basant sur le code de station pour raffiner la requette avec un size de 1000 dans chaque iteration. 
je voulais savoir la periode à jour et qui contient de la données car des fois quand je test sur certaines dates je trouves pas de données et aussi sur quelle fréquence les données se mets à jour.

Merci.

**Comment by Supp-Hubeau** [comment]
Bonjour,

La fréquence de mise à jour n'est pas quotidienne et peut varier d'une station à l'autre.
l'API ne permet pas d'obtenir directement la liste des dates pour lesquelles des analyses existent. Une interrogation préalable sur une station donnée en retounant uniquement la date de prélèvement (fields=date_prelevement) peut permettre d'affiner les recherches moyennant d'isoler les valeurs distinctes dans le résultat fourni par l'API.

https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/analyse_pc?code_station=01004000&fields=date_prelevement&size=1000 

Cordialement,
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Bonjour,

Nous clôturons le ticket. N'hésitez pas à le réouvrir si besoin.

Cordialement,
L'équipe Hub'eau
