### ISSUE TITLE
[API Hydrométrie] Retards dans les données

### ISSUE THREAD

**Issue by franziskakis-hydrique** [BRGM/hubeau#153]
Bonjour,

Nous constatons que les données disponibles s'arrêtent au 19 août 2023. Pourtant, elles semblent disponibles sur la plateforme hydro.eaufrance.fr.

Exemple:
[https://hydro.eaufrance.fr/stationhydro/V041501001/series](https://hydro.eaufrance.fr/stationhydro/V041501001/series)

Connaissez-vous la cause du problème ?
Plus généralement, existe-t-il un moyen de connaître le status de la plateforme en cas de panne ?

**Comment by jeanluchier** [comment]
Même problème de notre côté, tout s'arrête au 19/08 sur nos plateformes EMI et info-sécheresse.

**Comment by Supp-Hubeau** [comment]
Bonjour,

Nous avons rencontré un incident technique sur l'API Hydrométrie.
Les endpoints sont de nouveau disponibles.

Merci pour votre patience.

L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Bonjour,

Suite à l'incident traité hier matin, les des données d'hydrométrie temps réel ont été rechargées de manière à combler la plage du 19/08 matin au 21/08 matin qui n'avait pas été alimentée correctement.

L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Bonjour,

Clôture suite au retour à la normale.

@franziskakis-hydrique : hors supervision propre il n'existe pour l'instant pas de moyen de connaître le statut de la plateforme en cas de panne mais cela fait partie des points qui alimentent les réflexions de l'équipe.

L'équipe Hub'eau
