### ISSUE TITLE
Pas de données renvoyées à partir du 2023-08-05 par l'API https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/analyse_pc.csv

### ISSUE THREAD

**Issue by aliaajli** [BRGM/hubeau#154]
Bonjour,

Depuis 2023-08-05 on n'a plus de données de l'API Hub'Eau Qualité physico-chimique des cours d'eau: https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/analyse_pc.csv

Voici l'url que je utilise: https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/analyse_pc.csv?code_parametre=&date_debut_prelevement=2023-08-05&date_fin_prelevement=2023-09-29&size=200

Pourriez-vous svp nous aider pour avoir les données de cette API depuis 2023-08-05 ?

Cordialement,
Ali AAJLI

**Comment by Supp-Hubeau** [comment]
Bonjour,

A l'heure actuelle ces données ne figurent pas dans la base Naïades utilisé comme source par Hub'eau.

En interrogeant [naiades.eaufrance.fr/acces-donnees#/physicochimie](https://naiades.eaufrance.fr/acces-donnees#/physicochimie) on constate bien une absence de données de physicochimie (quel que soit le paramètre ou le cours d'eau) à partir du 05/08/2023.

Cordialement
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Bonjour,

Les données Naïades ont été alimentées postérieurement au 04/08/2023.
Nous clôturons du ticket. N'hésitez pas à le réouvrir si besoin.

Cordialement,
L'équipe Hub'eau
