### ISSUE TITLE
Qualité des cours d'eau ,nomenclature des variables utilisées

### ISSUE THREAD

**Issue by marcan-dev** [BRGM/hubeau#156]
Bonjour,

Je n'ai pas trouvé le descriptif de chacune des variables utilisées.
Par exemple sur:
 https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/condition_environnementale_pc?&size=20000&pretty
il y a la variable "resultat", a quoi correspond elle ?
Il y a t-il une nomenclature de toutes les variables utilisées ?

**Comment by antonio-andrade** [comment]
Bonjour,

Les schémas des données diffusées par les API Hub'Eau sont décrits dans la section `Models` en bas de chaque page d'accueil d'une API. Dans votre cas, l'attribut `resultat` d'une condition environnementale est décrit par `Résultat de la mesure du paramètre environnemental (résultat direct si le paramètre est quantitatif ou code si le paramètre est qualitatif)`

![image](https://github.com/BRGM/hubeau/assets/63242934/14aebfcd-fdd6-420e-a8ca-394830679d28)

**Comment by Supp-Hubeau** [comment]
Bonjour,

Nous clôturons le ticket. N'hésitez pas à le réouvrir si besoin.

Cordialement,
L'équipe Hub'eau
