### ISSUE TITLE
[API Hydrométrie]

### ISSUE THREAD

**Issue by EmilieEPLoire** [BRGM/hubeau#157]
Bonjour,

nous n'arrivons pas à utiliser l'export xml de observations_tr. Que l'on saisisse des informations ou non, le messager d'erreur suivant apparait : _😱 Could not render _t, see the console._
Pouvez-vous nous dire si ce service est utilisable?
Merci

Emilie BIGORNE

**Comment by Supp-Hubeau** [comment]
Bonjour,

Nous ne notons pas de dysfonctionnement de ce endpoint.

Exemple d'URL d'appel fonctionnelle : https://hubeau.eaufrance.fr/api/v1/hydrometrie/observations_tr.xml?code_entite=K435001010&format=json&size=15 

Avec quelle URL et quelle navigateur le dysfonctionnement est-il constaté ?

Nous restons disponibles pour tout complément

L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
En complément : 
Une anomalie affecte bien la console qui permet de tester le comportement de ce endpoint.
Le dysfonctionnement a été diagnostiqué et sera corrigé lors d'une prochaine mise en production.

Merci d'avance pour votre patience.

L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Bonjour,

Nous clôturons le ticket. N'hésitez pas à le réouvrir si besoin.

Cordialement,
L'équipe Hub'eau
