### ISSUE TITLE
Qualité des cours d'eau

### ISSUE THREAD

**Issue by PBirchen** [BRGM/hubeau#158]
Bonjour,
je cherche à exporter les informations des prélèvements sur la région Pays de la Loire avec l'URL:
https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/operation_pc?code_region=52&code_support=3&date_debut_prelevement=2022-01-01&date_fin_prelevement=2022-12-31&exact_count=true&format=json&size=5000

Je constate que pour les millésimes 2021 et 2020, une chute spectaculaire du nombre de prélèvements:
- 3390 en 2022
- 464 en 2021
- 1371 en 2020 
- 4649 en 2019
- 5925 en 2018
- 5268 en 2017
Ces écarts me paraissent suspects.

**Comment by Supp-Hubeau** [comment]
Bonjour,

Un incident technique impacte la remontée des données de l’agence de l’eau Loire-Bretagne vers Naïades. Les données de certaines stations ne sont pas récupérées.
Les équipes travaillent à la résolution du problème. 

L'équipe Hub'eau

**Comment by PBirchen** [comment]
Merci, nous allons attendre la résolution de la panne.
