### ISSUE TITLE
[API Hydro] - Documentation api swagger erreur

### ISSUE THREAD

**Issue by GuillaumeDef** [BRGM/hubeau#16]
Bonjour, 

Pour information, il y a une erreur lors de la récupération de la documentation swagger à partir de cette adresse :

https://hubeau.eaufrance.fr/api/v1/hydrometrie/api-docs

L'accès via Swagger UI (https://petstore.swagger.io/) fonctionne, mais avec une petite erreur.

Bonne journée

**Comment by tvilmus** [comment]
Bonjour,

Effectivement, l'accès à la doc swagger n'est pas possible depuis un navigateur à cause d'un bug dans le composant springfox que nous utilisons, qui n'envoie pas le content-type. Nous n'avons pas actuellement la possibilité de corriger cette erreur...

Si vous appelez la doc swagger depuis une appli, il faut fournir le content type en header :
Accept application/json;charset=utf-8,*/*

Cordialement,
Thierry
