### ISSUE TITLE
[API Hydrométrie] Données indisponibles via l'API mais présentes sur l'Hydroportail

### ISSUE THREAD

**Issue by paumillet** [BRGM/hubeau#161]
Bonjour,

Je cherche à récupérer des données d'observations sur l'Oise, et je remarque qu'aucune des stations de hauteurs d'eau ne retourne de résultats.  
Par exemple, avec la station H227000102 :  
https://hubeau.eaufrance.fr/api/v1/hydrometrie/obs_elab?code_entite=H227000102&cursor=&size=20

Cependant, en consultant la page de la station H227000102 sur l'Hydroportail, celle-ci semble bien avoir des observations, même aujourd'hui !   
https://www.hydro.eaufrance.fr/stationhydro/H227000102/series

Comment se fait-il que je ne puisse pas avoir accès à ces observations ?

Je précise que je ne rencontre pas le même soucis avec les stations débimétriques.

Merci d'avance pour votre retour.

**Comment by Supp-Hubeau** [comment]
Bonjour,

Le endpoint _obs_elab_ de l'API hydrométrie retourne uniquement des valeurs de débit : les débits moyens journaliers (QmJ) ainsi que les débits moyens mensuels (QmM).
Le endpoint _observations_tr_ de cette même API retourne des valeurs de hauteur et de débit avec un pas de temps beaucoup plus faible mais une profondeur d'historique limitée à 30 jours.
https://hubeau.eaufrance.fr/api/v1/hydrometrie/observations_tr?code_entite=H227000102&format=json&size=50 

La récupération de données de hauteurs antérieures à J-30j nécessite effectivement de passer par l'[hydroportail](https://www.hydro.eaufrance.fr/). 

Cordialement
L'équipe Hub'eau

**Comment by paumillet** [comment]
Merci pour votre réponse, j'avais en effet eu une confusion entre les observations et les observations élaborées.
