### ISSUE TITLE
[API Hydrométrie] Absence des données élaborées depuis le 25 février 2024

### ISSUE THREAD

**Issue by PouPass** [BRGM/hubeau#167]
Bonjour,

Il semble que les données élaborées 'QmJ' ne soit plus distribuées depuis le 26 février 2024, la dernière mesure disponible étant datée du 25 février 2024.

Exemple avec les deux stations ci dessous, mais la majorité des stations semblent impactées.

```
https://hubeau.eaufrance.fr/api/v1/hydrometrie/obs_elab?code_entite=O723403001&date_debut_obs_elab=2024-02-20T00%3A05%3A01Z&grandeur_hydro_elab=QmJ&size=20
```

```
https://hubeau.eaufrance.fr/api/v1/hydrometrie/obs_elab?code_entite=V201201001&date_debut_obs_elab=2024-02-20T00%3A05%3A01Z&grandeur_hydro_elab=QmJ&size=20
```

Merci.

**Comment by Supp-Hubeau** [comment]
Bonjour,

Merci pour votre message.
Le problème a été remonté aux équipes techniques.
Nous faisons en sorte de rétablir la situation dans les meilleurs délais. 

Cordialement,
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Bonjour,

Un traitement de recalcul de masse est en cours sur la plate-forme HYDRO Centrale (PHyC), utilisée comme source pour les observations élaborées exposées par l'API Hydrométrie. Cette opération perturbe le process d'alimentation des données de débit moyen journalier.
Le recalcul doit se poursuivre jusqu’au 18/03/2024, les données seront de nouveau exposées par l’API après cette date.
Pendant cette période, les données temps réel restent disponibles via le endpoint _observations_tr_ de l’API Hydrométrie.

Merci pour votre compréhension.

Cordialement,
L'équipe Hub'eau

**Comment by PouPass** [comment]
Bonjour,

C'est bien noté, je vous remercie pour ces informations. Dans l'attente je bascule sur les données temps réel.

Cordialement,

**Comment by Supp-Hubeau** [comment]
Bonjour,

Le traitement de recalcul effectué sur la plate-forme HYDRO Centrale (PHyC) est terminé.
Les observations élaborées exposées par l'API Hydrométrie sont de nouveau alimentées depuis le 14/03.
Un rechargement complet des donnés a été effectué.
Retour à un fonctionnement nominal.

Cordialement,
L'équipe Hub'eau

**Comment by PouPass** [comment]
Bonjour,

Parfait, je vous remercie, je clos le ticket.

Cordialement,
