### ISSUE TITLE
[API Hydrométrie] Disponibilité durant les crues

### ISSUE THREAD

**Issue by franziskakis-hydrique** [BRGM/hubeau#168]
Bonjour,

Nous apprenons que le site [Hydroreel](https://www.rdbrmc.com/hydroreel2/index.php) fermera ses portes prochainement.
A priori cela ne nous pose pas de problème, nous importons déjà les mêmes données via l'API Hydrométrie.

Cependant, nous constatons sur plusieurs stations des problèmes de transmission de données, en particulier durant des crues.
Ci-dessous, on compare la donnée acquise en temps-réel sur Hydroreel (rouge) avec l'acquisition HubEau (bleue).
- code de station : `V131502001`
- période : du 22 au 28 février 2024 (autres exemples sur demande)
![image](https://github.com/BRGM/hubeau/assets/129161142/24672780-7c69-4060-b7e1-96ec88930e85)

Connaissez-vous la cause du problème ?
A disposition pour compléter l'information.

En vous remerciant d'avance.

**Comment by franziskakis-hydrique** [comment]
En regardant d'un peu plus près, on voit que les données ne sont pas fournies par l'API :
![image](https://github.com/BRGM/hubeau/assets/129161142/3a93290d-7c11-488d-b68f-8a6fc507d37d)

**Comment by Supp-Hubeau** [comment]
Bonjour,

Pour cette station, sur la période concernée les données sont absentes du système source à partir duquel l'API est alimentée (plate-forme HYDRO Centrale - PHyC).

On constate également cette anomalie sur Hydroportail : https://www.hydro.eaufrance.fr/stationhydro/V131502001/series 

![hydroportail_v131502001](https://github.com/BRGM/hubeau/assets/127056001/f5a9e212-adff-40e1-8bfc-a99098a5f1dd)


Cordialement
L'équipe Hub'eau

**Comment by franziskakis-hydrique** [comment]
Merci pour votre réponse rapide.

Certes la donnée n'est pas dans l'hydroportail, mais elle doit bien exister quelque part.
Pouvez-vous indiquer à quel niveau le dysfonctionnement pourrait avoir eu lieu ?
Avec l'abandon de Hydroreel, on perd donc pour le moment en fiabilité des données, c'est bien dommage !

Cordialement,

**Comment by Supp-Hubeau** [comment]
Pour l'API hydrométrie, la chaîne d'alimentation d'Hub'eau consomme les données disponibles dans la Phyc, nous n'avons aucune connaissance de ce qui se produit en amont (sélection, validation, correction...).
Pour en savoir plus il convient de vous rapprocher du Schapi ou plus directement du service producteur de la donnée.

Cordialement
L'équipe Hub'eau

**Comment by franziskakis-hydrique** [comment]
Bonjour,

Merci pour ces éléments.
J'ai pu contacter les services concernés : la panne était due à un changement de collecte de donnée peu avant l'événement. Les données sont corrigées et disponibles dans l'hydroportail.
Pas de problème de fiabilité de transfert en général donc.

![image](https://github.com/BRGM/hubeau/assets/129161142/db674f80-f37f-4531-b9bf-76bd17d6a79d)

Merci encore pour vos réponses.
