### ISSUE TITLE
[API Qualité des cours d'eau] - absence de données

### ISSUE THREAD

**Issue by Galdro45** [BRGM/hubeau#169]
Bonjour, 
nous avons remarqué que certaines données du bassin Loire-Bretagne ne remontent pas dans Naïades et Hub'Eau. 
Exemple sur la station 04670020 sur l'année 2021, producteur 20003408000065 (EPTB SN). 
Ces données sont pourtant bien disponibles à la source : 
https://services-sandre.eau-loire-bretagne.fr/Monitoring_2_1.svc?wsdl

<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:ns="http://xml.sandre.eaufrance.fr/wsdl/Monitoring/2.1">
   <soap:Header/>
   <soap:Body>
      <ns:getData>
         
         <ns:domain>3.1</ns:domain>
         
         <ns:sites>
            
            <ns:CdSite schemeAgencyID="1">04670020</ns:CdSite>
         </ns:sites>
         
         <ns:temporalConstraints>
            
            <ns:DateDebutDonnees>2021-01-01</ns:DateDebutDonnees>
            
            <ns:DateFinDonnees>2022-01-01</ns:DateFinDonnees>
         </ns:temporalConstraints>
         
         <ns:outputSchema>http://xml.sandre.eaufrance.fr/scenario/quesu/3.1/sandre_sc_quesu.xsd</ns:outputSchema>
         <ns:outputFormat>text/xml</ns:outputFormat>
      </ns:getData>
   </soap:Body>
</soap:Envelope>

Pouvez-vous nous dire pourquoi elles ne parviennent pas jusqu'à la cible? 
[04670020_2021.zip](https://github.com/BRGM/hubeau/files/14638934/04670020_2021.zip)

Merci d'avance.

**Comment by eptbsn-ariviere** [comment]
Je pense qu'il faudrait modifier le titre , cela concerne [API Qualité des cours d'eau].  
Ce problème semble se situer au niveau de Naïades, car la donnée 2021 est absente sur Naïades.  
Dans l'exemple suivant nous n'avons que les opérations de 2022 et pas celles de 2021):  
 - https://naiades.eaufrance.fr/acces-donnees#/physicochimie/operations?debut=01-01-2021&fin=31-12-2022&stations=04670020.  
J'ai déposé un message dans ce sens sur la plateforme de contact naïades (https://naiades.eaufrance.fr/formulaire/contact). 
Si l'équipe de Hubeau a les moyens de faire remonter le problème au niveau des gestionnaires de naïades, ce serait super.
Merci encore pour vos APIs.

**Comment by Galdro45** [comment]
Bonjour, 
en effet je confirme, le problème vient de l'AELB. 
Plus précisément le problème venait d’une table de log qui n’ pas été mise à jour au moment de l’initialisation de Naïades. 
le système de logs est prévu pour le différentiel et pour ne pas aspirer des millions de données à chaque fois. 
Il y a eu un souci au démarrage (initialisation des logs en base par requête sans que les logs ne soient branchés dans Lyxea Desktop, d’où le manque de données).
les logs n’ont pas été initialisés pour Naïades à la bonne date (par réinitialisation, j’entends que toutes les dates de mise à jour de prélèvements dans les logs sont réinsérées avec la date courante pour faire croire à Naïades que les données ont été modifiées car Naïades télécharge sauf exception par différentiel). En fait la requête d’initialisation avait été passée en 2022 mais pas à la bonne date.

Le problème concerne 56000 prélèvements pour environ 7 millions d’analyses. 
Nous avons passé une grosse requête pour insérer les lignes manquantes (insertion dans la table des logs des informations de tous les prélèvements PC ESU qui n’y sont pas) sans tout réinitialiser. 
Les données manquantes seront automatiquement aspirées lors du prochain moissonnage Naïades (il y aura beaucoup de données d'un coup). 
Cordialement, 
Gaël Dorso

**Comment by eptbsn-ariviere** [comment]
@Galdro45 
Afin de définir au mieux l'année à partir de laquelle nous allons devoir re-collecter les données de hub'eau dans notre SI, pour mettre à jour l'historique, avez vous une idée de l'étendu temporelle  des prélèvements impactées (années des opérations de prélèvements)?

**Comment by Galdro45** [comment]
Concernant les 56173 prélèvements ajoutés dans les logs , ceux-ci sont sur une période allant du 10/07/2006 au 15/06/2022.
Gaël Dorso

**Comment by Supp-Hubeau** [comment]
Bonjour,

AELB corrigé le dysfonctionnement du service web Sandre SOAP utilisé pour l’alimentation de Naïades.
Les données sont de nouveau disponibles.

Cordialement,
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Clôture du ticket. N'hésitez pas à le réouvrir si besoin.

Cordialement,
L'équipe Hub'eau
