### ISSUE TITLE
[API Hydro] - Problème de pagination

### ISSUE THREAD

**Issue by GuillaumeDef** [BRGM/hubeau#17]
Bonjour, 

En réalisant des tests sur l'API Hydro, il s'avère que le propriété next (lors de la pagination des appels) est remplie même si on arrive à la dernière page. 

Ex.: https://hubeau.eaufrance.fr/api/v1/hydrometrie/observations_tr?code_entite=J7803020&size=100&sort=asc&date_debut_obs=2018-12-17&date_fin_obs=2018-12-18

Bonne journée

**Comment by tvilmus** [comment]
Bonjour,

Merci de nous avoir signalé ce problème, que nous allons corriger.

Bien cordialement,
Thierry
