### ISSUE TITLE
[API Qualité de l'eau] bug sur les conformités

### ISSUE THREAD

**Issue by arnaudambro** [BRGM/hubeau#172]
Bonjour

Je pense qu'il existe un bug sur le report des conformités (`conformite_references_pc_prelevement`, `conformite_references_bact_prelevement`, `conformite_limites_pc_prelevement`, `conformite_limites_bact_prelevement`)

Par exemple: https://hubeau.eaufrance.fr/api/v1/qualite_eau_potable/resultats_dis?size=2&code_prelevement=00600245896

La réponse est: 
```
{
    "count": 18,
    "first": "https://hubeau.eaufrance.fr/api/v1/qualite_eau_potable/resultats_dis?code_prelevement=00600245896&page=1&size=2",
    "last": "https://hubeau.eaufrance.fr/api/v1/qualite_eau_potable/resultats_dis?code_prelevement=00600245896&page=9&size=2",
    "prev": null,
    "next": "https://hubeau.eaufrance.fr/api/v1/qualite_eau_potable/resultats_dis?code_prelevement=00600245896&page=2&size=2",
    "api_version": "v1",
    "data": [
        {
            "code_departement": "06",
            "nom_departement": "Alpes-Maritimes",
            "code_prelevement": "00600245896",
            "code_parametre": "1447",
            "code_parametre_se": "CTF",
            "code_parametre_cas": null,
            "libelle_parametre": "Bactéries coliformes /100ml-MS",
            "libelle_parametre_maj": "BACTÉRIES COLIFORMES /100ML-MS",
            "libelle_parametre_web": null,
            "code_type_parametre": "N",
            "code_lieu_analyse": "L",
            "resultat_alphanumerique": "1",
            "resultat_numerique": 1.0,
            "libelle_unite": "n/(100mL)",
            "code_unite": "226",
            "limite_qualite_parametre": null,
            "reference_qualite_parametre": "<=0 n/(100mL)",
            "code_commune": "06083",
            "nom_commune": "MENTON",
            "nom_uge": "CARF",
            "nom_distributeur": "ORFEO-VEOLIA",
            "nom_moa": "CARF DSP",
            "date_prelevement": "2023-08-11T15:52:00Z",
            "conclusion_conformite_prelevement": "Eau présentant des signes de dégradation bactériologique.",
            "conformite_limites_bact_prelevement": "C",
            "conformite_limites_pc_prelevement": "C",
            "conformite_references_bact_prelevement": "N",
            "conformite_references_pc_prelevement": "C",
            "reference_analyse": "00600245908",
            "code_installation_amont": null,
            "nom_installation_amont": null,
            "reseaux": [
                {
                    "code": "006000026",
                    "nom": "ROYA"
                }
            ]
        },
        {
            "code_departement": "06",
            "nom_departement": "Alpes-Maritimes",
            "code_prelevement": "00600245896",
            "code_parametre": "1301",
            "code_parametre_se": "TEAU",
            "code_parametre_cas": null,
            "libelle_parametre": "Température de l'eau",
            "libelle_parametre_maj": "TEMPÉRATURE DE L'EAU",
            "libelle_parametre_web": null,
            "code_type_parametre": "N",
            "code_lieu_analyse": "T",
            "resultat_alphanumerique": "23,1",
            "resultat_numerique": 23.1,
            "libelle_unite": "°C",
            "code_unite": "27",
            "limite_qualite_parametre": null,
            "reference_qualite_parametre": "<=25 °C",
            "code_commune": "06083",
            "nom_commune": "MENTON",
            "nom_uge": "CARF",
            "nom_distributeur": "ORFEO-VEOLIA",
            "nom_moa": "CARF DSP",
            "date_prelevement": "2023-08-11T15:52:00Z",
            "conclusion_conformite_prelevement": "Eau présentant des signes de dégradation bactériologique.",
            "conformite_limites_bact_prelevement": "C",
            "conformite_limites_pc_prelevement": "C",
            "conformite_references_bact_prelevement": "C",
            "conformite_references_pc_prelevement": "C",
            "reference_analyse": null,
            "code_installation_amont": null,
            "nom_installation_amont": null,
            "reseaux": [
                {
                    "code": "006000026",
                    "nom": "ROYA"
                }
            ]
        }
    ]
}
```

on constate que, pour le même prélèvement, `conformite_references_bact_prelevement` n'est pas le même pour chaque paramètre.

mon analyse est que ces champs là ont été extraits des fichiers sources ici: https://www.data.gouv.fr/fr/datasets/resultats-du-controle-sanitaire-de-leau-distribuee-commune-par-commune/
et donc devraient être tous identiques pour un prélèvement donné.

si mon analyse est correcte, alors il y a un bug quelque part probablement ?
si je me trompe dans mon analyse, quelle est donc la raison de cette différence ?

merci beauoup pour votre travail !

bonne journée,
Arnaud

**Comment by Supp-Hubeau** [comment]
Bonjour,

Merci pour ce signalement détaillé.
Cette situation semble en effet anormale. Nous allons investiguer.

Cordialement
L'équipe Hub'eau

**Comment by arnaudambro** [comment]
bonjour

merci pour votre réponse, avez-vous une idée de quand le bug sera résolu ?
pour savoir si je dois implémenter une mitigation de mon côté ou pas

je travaille sur le produit recosanté https://github.com/SocialGouv/recosante/blob/master/api-node/src/aggregators/drinking_water.ts et pour l'instant j'ai considéré prendre le pire cas - peut-être devrais-je considérer prendre le cas majoritaire, ou (encore mieux) peut-être devrais-je juste attendre que vous résolviez ce bug et ne pas faire de mitigation :) tout dépend de votre réponse.

merci !

**Comment by Supp-Hubeau** [comment]
Bonjour,

Nous n'allons pas pouvoir corriger ce problème dans l'immédiat.
Il semble préférable de prendre des dispositions de votre côté si possible.
Nous vous tiendrons informé.

Cordialement
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Bonjour @arnaudambro,

Avez-vous pu poursuivre vos travaux sur l'API Qualité de l'eau potable ?

Cordialement
L'équipe Hub'eau

**Comment by arnaudambro** [comment]
Bonjour

Oui, nous avons décidé de prendre le cas le pire - il faut que je mette en place finalement le cas le plus majoritaire je pense.

L'application est bientôt en production avec vos données :)

Merci et bonne chance pour la suite,
Arnaud

**Comment by Supp-Hubeau** [comment]
Bonjour,

Nous pensons avoir identifié l'origine de l'anomalie.
Elle devrait être corrigée lors du prochain traitement d'actualisation des données le 15/05.
Nous vous tiendrons informé.

Cordialement
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Bonjour,

Suite au rechargement (avec correction) effectué ces dernières heures, l'anomalie n'est pas reproduite.

Cordialement
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Clôture du ticket. N'hésitez pas à le réouvrir si besoin.

Cordialement,
L'équipe Hub'eau
