### ISSUE TITLE
[API Hydrométrie] erreur serveur (Internal server error)

### ISSUE THREAD

**Issue by franziskakis-hydrique** [BRGM/hubeau#173]
Bonjour,

Depuis ce matin 05:00, nous constatons des problèmes de connection sur le serveur.

Exemple d'URL:
`https://hubeau.eaufrance.fr/api/v1/hydrometrie/observations_tr?code_entite=U201203001&grandeur_hydro=Q&size=100&fields=code_station,date_obs,resultat_obs`
Nous recevons le code d'erreur 500 (internal server error).

Avez-vous plus d'informations ?

En vous remerciant d'avance pour votre analyse.

**Comment by Supp-Hubeau** [comment]
Bonjour,

Une anomalie affecte actuellement le endpoint _Observations temps réel_ de l'API _Hydrométrie_.
Les équipes techniques sont informées et s'emploient à relancer le service dans les meilleurs délais.
Merci pour votre compréhension.

Cordialement
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Le endpoint Observations temps réel de l'API Hydrométrie est à nouveau disponible.
https://hubeau.eaufrance.fr/api/v1/hydrometrie/observations_tr?code_entite=K435001010&format=json&size=10 
Merci pour votre patience.

Cordialement
L'équipe Hub'eau
