### ISSUE TITLE
[API : QUALITE EAU POTABLE] Erreur sur interrogation par réseau

### ISSUE THREAD

**Issue by AESN-DCP** [BRGM/hubeau#174]
Bonjour,

Lors de l'utilisation de la requête suivante dans R, j'obtiens pour certain réseau, le message d'erreur ci-dessous. Ce message n'apparait pas pour tous les réseaux.
Par ailleurs, est-il envisageable de disposer d'une requête remontant la description des réseaux d'eau potable avec les code et nom des UGE, des distributeurs et des MOA, voire également la géométrie spatiale de l'UDI associée ?

**REQUETE PROVOQUANT L'ERREUR :**
get_qualite_eau_potable_resultats_dis(code_reseau = "010000138",
                                                  code_parametre="1340",
                                                  date_min_prelevement = "2023-04-19",
                                                  date_max_prelevement = "2024-04-19")

**MESSAGE D'ERREUR**
Error in `map()`:
ℹ In index: 1.
Caused by error in `.f()`:
! Column names `reseaux.code` and `reseaux.nom` must not be duplicated.
Use `.name_repair` to specify repair.
Caused by error in `repaired_names()`:
! Names must be unique.
✖ These names are duplicated:
  * "reseaux.code" at locations 32 and 34.
  * "reseaux.nom" at locations 33 and 35.
Run `rlang::last_trace()` to see where the error occurred.

**Comment by Supp-Hubeau** [comment]
Bonjour,

D'après les informations fournies il semble que l'URL utilisée est la suivante : 
https://hubeau.eaufrance.fr/api/v1/qualite_eau_potable/resultats_dis?code_parametre=1340&code_reseau=010000138&date_max_prelevement=2024-04-19&date_min_prelevement=2023-04-19 

Appelée depuis un navigateur cette URL ne retourne pas d'anomalie. 
On peut cependant noter que dans cet exemple le champ réseau est multivalué. Plusieurs codes, noms et débits de réseaux peuvent apparaitre pour un même résultat. Le code R utilisé prévoit-il bien ce cas ? 

Pour ce qui est d'obtenir une description plus détaillées des réseaux, aucune évolution de l'API n'est prévue dans ce sens à court terme et l'équipe Hub'eau n'est pas en capacité de produire ce type d'extraction. 
Nous vous invitons à consulter les données brutes que nous utilisons comme source (https://www.data.gouv.fr/fr/datasets/5cf8d9ed8b4c4110294c841d) ou à contacter directement le service producteur de ces données.

Cordialement,
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Bonjour,

Après analyse, il semble que l’anomalie a pour origine le code du package R Hubeau.
Nous vous invitons à ouvrir une issue sur le projet correspondant : https://github.com/inrae/hubeau

Cordialement,
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Clôture du ticket. N'hésitez pas à le réouvrir si besoin.

Cordialement,
L'équipe Hub'eau
