### ISSUE TITLE
[API Surveillance des eaux littorales] Récupération des données Quadrige - Historique

### ISSUE THREAD

**Issue by sbarthon** [BRGM/hubeau#175]
Bonjour,

nous souhaitons utiliser l'API des eaux littorales (https://hubeau.eaufrance.fr/page/api-surveillance-littoral#/surveillance_littoral/lieux_surveillance) mais nous rencontrons des difficultés pour récupérer les historiques. Il semble que certaines analyses ne soient pas présentes. Par exemple pour l'identifiant 60007272 (https://surval.ifremer.fr/Donnees/Graphes-30140#/sensor/60007272), il existe des données de 1991 à 2011 (cf extraction en pièce jointe). Seulement l'API ne renvoie aucune donnée https://hubeau.eaufrance.fr/api/v1/surveillance_littoral/contaminants_chimiques?code_lieusurv=60007272

Est ce que les historiques ne sont pas tous présents ?

Merci d'avance
[output (2).csv](https://github.com/BRGM/hubeau/files/15487325/output.2.csv)

**Comment by Supp-Hubeau** [comment]
Bonjour,

Depuis quelques temps nous rencontrons des difficultés d’alimentation des données de l’API Surveillance des eaux littorales à partir de Quadrige. Un diagnostic est en cours avec l’équipe de l’Ifremer.
Nous vous informerons de l’évolution.

Cordialement
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Bonjour,

L'API Hub'eau ne diffuse actuellement qu'une partie des données de Quadrige : principalement la thématique Contaminants chimiques.

Les données associées au lieu que vous cherchez ne font pas parties de ce périmètre thématique et ne sont donc pas disponibles dans Hub'eau.

Vous pouvez le constater par l'absence de catégorie "Contaminants" dans les graphiques associés de Surval.

Pour accéder aux résultats de ce type de lieux, nous vous invitons à passer par les téléchargements de l'outil Surval.

Très bonne journée,
Equipe Quadrige, Ifremer

**Comment by Supp-Hubeau** [comment]
Clôture du ticket. N'hésitez pas à le réouvrir si besoin.

Cordialement,
L'équipe Hub'eau
