### ISSUE TITLE
[API Hydrométrie] erreur serveur (Internal server error)

### ISSUE THREAD

**Issue by ClementCossonHydrique** [BRGM/hubeau#177]
Bonjour,

Depuis hier (18.07) à 22h, nous constatons des problèmes de connection à votre serveur. Ce problème est similaire à celui mentionné ici: https://github.com/BRGM/hubeau/issues/173 

Exemple d'URL:
https://hubeau.eaufrance.fr/api/v1/hydrometrie/observations_tr?code_entite=U201203001&grandeur_hydro=Q&size=100&fields=code_station,date_obs,resultat_obs
Nous recevons le code d'erreur 500 (internal server error).

Avez-vous plus d'informations ?

En vous remerciant d'avance pour votre analyse.

**Comment by Supp-Hubeau** [comment]
Bonjour,

Le endpoint _Observations temps_ réel de l'API Hydrométrie retourne en effet une erreur 500 depuis hier soir 22h.
L’anomalie a été signalé eaux équipes techniques qui devraient traiter le problème dans la matinée.

Merci pour votre compréhension.

Cordialement
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Le endpoint _Observations temps réel_ de l'API Hydrométrie est à nouveau disponible.

Cordialement
L'équipe Hub'eau

**Comment by ClementCossonHydrique** [comment]
Effectivement, c'est réparé de notre côté.
Merci pour votre réaction rapide!
