### ISSUE TITLE
[API Piézométrie] Erreur dans le critère field 

### ISSUE THREAD

**Issue by tgrandje** [BRGM/hubeau#178]
Bonjour

Un bug repéré sur l'endpoint chroniques, vie à vis du critère expérimental "fields" :
* lancer [une requête](https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques?code_bss=07548X0009%2FF&fields=timestamp_mesure%2Cniveau_nappe_eau&size=20) avec "fields=timestamp_mesure,niveau_nappe_eau" retourne des timestamps nuls ;
* par contre, lancer [la même requête en ajoutant le champ date_mesure](https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques?code_bss=07548X0009%2FF&fields=timestamp_mesure%2Cniveau_nappe_eau%2Cdate_mesure&size=20) fait revenir des valeurs correctes pour les timestamps.

**Comment by Supp-Hubeau** [comment]
Bonjour,

Merci pour la précision des éléments fournis.
Un ticket a été ouvert en interne sur le sujet.

Cordialement,
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Bonjour,

Un correctif a été déployé.
Lors de l’utilisation du paramètre fields, le champ _timestamp_ est désormais valorisé indépendamment de la présence du champ _date_mesure_.

https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques?code_bss=04138X0083/PK19.0&fields=timestamp_mesure%2Cniveau_nappe_eau,statut&size=20

Cordialement,
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Clôture du ticket. N'hésitez pas à le réouvrir si besoin.

Cordialement,
L'équipe Hub'eau
