### ISSUE TITLE
[API TEMPERATURE] - horodatage AM PM erroné

### ISSUE THREAD

**Issue by laurentbre** [BRGM/hubeau#18]
L'horodatage des observations ne distingue pas AM et PM. Voir par ex. http://hubeau.eaufrance.fr/api/v1/temperature/chronique.csv?code_station=04051125&size=2&date_debut_mesure=2010-05-01&date_fin_mesure=2010-09-30
Les données d'origine dans Naiades sont correctes : http://www.naiades.eaufrance.fr/acces-donnees#/temperature/resultats?debut=01-05-2010&fin=02-05-2010&stations=04051125

**Comment by tvilmus** [comment]
Désolé pour cette réponse tardive, la mise à jour d'hier a corrigé ce bug d'horodatage AM/PM ainsi qu'un autre bug sur des années erronnées.

**Comment by tvilmus** [comment]
Un petit démonstrateur pour voir les stations et données disponibles:
http://www.nalguise.net/temperature/temperature.php

**Comment by tvilmus** [comment]
Une nouvelle mise à jour des données permet de bénéficier des données 2017 (1,3 millions de données), 2018 (1 million de données) et même quelques données 2019 (80 000 données, jusqu'au 11 juin).
