### ISSUE TITLE
Imprécision dans la documentation API Piézo / chroniques_tr

### ISSUE THREAD

**Issue by tgrandje** [BRGM/hubeau#180]
Concernant le code_bss, la documentation indique : 

> _code_bss_
> _Code(s) national de la station (anciens codes BSS), si interrogation de plusieurs points d'eau, séparer les codes par une virgule, le nombre maximum de codes est 200_
> _Default value : 07548X0009/F_

Le code_bss ne peut manifestement pas être fixé avec une valeur par défaut dans la mesure où il est également possible de fixer un bss_id dans la requête.

Par exemple, la requête https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques_tr?size=1 retourne un résultat sur un autre piézomètre (00035X0210/PZO1).

**Comment by Supp-Hubeau** [comment]
Cette valeur par défaut s'applique uniquement à la console et non à l'API en elle-même.

Si aucune valeur n'est saisie dans le formulaire de test, l'URL suivante est générée : 
https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques_tr?code_bss=07548X0009%2FF&size=20 

Si on saisit` bss_id=BSS000ACKJ` dans le formulaire de test, l'URL suivante est générée :
https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques_tr?bss_id=BSS000ACKJ&code_bss=07548X0009%2FF&size=20
Il incombe à l'utilisateur de retirer l'un des deux critères lors de ses tests.

L'API en elle-même ne fixe pas de valeur par défaut pour le code ou l'ID BSS.
Seul le paramètre _size_ est fixé par défaut (20 dans la console et 5000 au niveau de l'API).

Cordialement,
L'équipe Hub'eau
