### ISSUE TITLE
[API Poissons] Fréquence de moissonage de la base ASPE

### ISSUE THREAD

**Issue by AnthonyDEBUR** [BRGM/hubeau#181]
Bonjour,

Peut-on connaitre à quelle fréquence / quelles dates Hubeau moissonne la base ASPE ? Certaines opérations créées sous ASPE le 26 juillet ne sont pas disponibles ce jour (14 août) comme l'opération 91745.

Bien cordialement,
Anthony

**Comment by Supp-Hubeau** [comment]
Bonjour,

La mise à jour des données Hub'eau depuis la base Aspe est programmée quotidiennement.
Le traitement est cependant bloqué depuis quelques jours. Une demande est en cours pour rétablir la situation.

Nous vous tiendrons informé dès que possible.

Cordialement,
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Suite à la réexécution du traitement les données ont été actualisées.
Un certain nombre de nouvelles opérations sont désormais exposées parmi lesquelles 91769, 91767, 91770, 91760, 91759, 91758.

L’opération le plus récente est datée du 17/07/2024.
https://hubeau.eaufrance.fr/api/v1/etat_piscicole/operations?format=json&size=100&fields=code_operation,date_operation 

L'opération 91745 ne figure pas parmi celles exposées.

Cordialement,
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Bonjour,

Suite aux actualisations successives des données, l’opération le plus récente est désormais datée du 27/08/2024.
https://hubeau.eaufrance.fr/api/v1/etat_piscicole/operations?format=json&size=100&fields=code_operation,date_operation

Il semble que l'opération 91745 ne figure toujours pas parmi les résultats. Nous vous invitons à contacter le service gestionnaire pour de plus amples informations.

Cordialement,
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Bonjour,

Quelques précisions fournies par l'équipe Aspe : 

_Les données de certaines opérations sont soumises à des contrôles avant leur diffusion.
Ainsi, les données sous maîtrise d'ouvrage de l’agence de l’eau Loire-Bretagne doivent être validées niveau 2 ou datées de plus d'un an pour être diffusées. L'opération 91745 est sous maîtrise d’ouvrage AELB, validée niveau 1 et réalisée cette année. Elle fait donc l’objet d’un contrôle avant sa diffusion.
Pour un plus large partage de l’information, le périmètre des données Aspe diffusées va être précisé sur la page d’accueil de l’API._

Cordialement,
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Clôture du ticket. N'hésitez pas à le réouvrir si besoin.

Cordialement,
L'équipe Hub'eau
