### ISSUE TITLE
[API Hydrométrie] [API piézométrie] Erreur de connexion a hub'eau

### ISSUE THREAD

**Issue by JOSSELIN-BERTH** [BRGM/hubeau#184]
Bonjour,

Les API hydrométrie et piézométrie sont de nouveau indisponible depuis hier soir. Une erreur 500 est retourné a leur appel.

Serait-il possible de connaître l'origine du problème ?

Bien cordialement,

Josselin Berthelon

**Comment by Supp-Hubeau** [comment]
Bonjour,

Depuis cette nuit un dysfonctionnement affecte l’ensemble des API et les rend momentanément indisponibles.
Les équipes techniques sont à l’œuvre pour rétablir le service dans les meilleurs délais.

Merci pour votre compréhension.

Cordialement,
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Les API sont de nouveau disponibles.

Merci pour votre patience.

Cordialement,
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Clôture du ticket. N'hésitez pas à le réouvrir si besoin.

Cordialement,
L'équipe Hub'eau
