### ISSUE TITLE
API hydrométrie - problèmes de connections

### ISSUE THREAD

**Issue by ClementCossonHydrique** [BRGM/hubeau#187]
Bonjour,

Depuis hier à 2-3 h du matin, nous constatons que le temps nécessaire pour effectuer nos requêtes sur l'API Hydrométrie a fortement augmenté (de ~1min à 10-30min). Depuis ce matin à 3h, nous ne pouvons plus nous connecter à l'API.

Le format typique de nos requêtes: 
https://hubeau.eaufrance.fr/api/v1/hydrometrie/observations_tr?code_entite=::StationCode::&grandeur_hydro=::SensorCode::&size=30&fields=code_station,date_obs,resultat_obs"

Le code d'erreur: time-outs ou "The SSL connection could not be established, see inner exception."

Connaissez-vous la cause de cette situation? 

Cordialement,
C. Cosson

**Comment by Supp-Hubeau** [comment]
Bonjour,

Nos outils de suivi ne montrent pas d'indisponibilité complète du endpoint.
Cependant un volume inhabituel de sollicitations induit des temps de réponse dégradés qui pénalisent son utilisation.
Nous rencontrons occasionnellement ce type d'épisodes (d'une durée allant jusqu'à 48h) sans pouvoir en identifier l'origine de manière certaine.

Cordialement,
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Bonjour @ClementCossonHydrique,

D'après les éléments dont nous disposons les temps de réponse sont revenus à leur niveau habituel depuis le 20/09 23:00.
Est-ce également le cas de votre côté ?

Cordialement,
L'équipe Hub'eau

**Comment by ClementCossonHydrique** [comment]
Bonjour,

Oui, tout à fait. Merci pour vos explications.

Cordialement,
C. Cosson

**Comment by Supp-Hubeau** [comment]
Clôture du ticket. N'hésitez pas à le réouvrir si besoin.

Cordialement,
L'équipe Hub'eau
