### ISSUE TITLE
[API Hydrométrie] Problème données sur certaines stations hydrométriques

### ISSUE THREAD

**Issue by JOSSELIN-BERTH** [BRGM/hubeau#188]
Bonjour,
Certaines stations hydrométriques ne produisent plus données depuis le 04-10 à 6h : exemple O493101001 ou O866151002 mais pas seulement.
Il y a t'il une explication ?
Bien cordialement,

**Comment by Supp-Hubeau** [comment]
Bonjour,

Merci pour ce signalement.
Un dysfonctionnement est venu affecter le chaîne d’alimentation de l'API causant des manques de données pendant quelques jours.

Le mode de collecte nominal a été rétabli (sans comblement des données manquantes de la semaine écoulée).

Cordialement,
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Clôture du ticket. N'hésitez pas à le réouvrir si besoin.

Cordialement,
L'équipe Hub'eau
