### ISSUE TITLE
[API Hydrométrie] Message d'erreur serveur.

### ISSUE THREAD

**Issue by LilGL** [BRGM/hubeau#189]
Bonjour,

J'utilise l'API pour des relevés de niveaux du pont Morand à Lyon, mais je constate ce matin le message d'erreur suivant :

"Exception: Échec de la requête pour https://hubeau.eaufrance.fr. Code renvoyé : 500. Réponse tronquée du serveur : {"code":"Internal server error","message":"","field_errors":null} (Utilisez l'option muteHttpExceptions pour examiner la réponse entière.) (ligne 11, fichier 'Code')"

Est-ce dû à mon script ou s'agit-il d'un problème directement lié à l'API ? D'autres personnes rencontrent-elles le même problème ?

Merci pour votre retour.

Bonne journée.

**Comment by jbellier** [comment]
Idem. Nos requêtes se sont arrêté de fonctionner autour de minuit cette nuit

**Comment by Supp-Hubeau** [comment]
Bonjour,

Cette nuit une anomalie a effectivement touché l'infrastructure Hub'eau induisant une indisponibilité de l'API hydrométrie TR entre le 08/10 22h00 et le 09/10 10h45.

Le service est de nouveau disponible depuis ce matin 10h50.
Merci pour votre compréhension.

Cordialement
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Clôture du ticket. N'hésitez pas à le réouvrir si besoin.

Cordialement,
L'équipe Hub'eau

**Comment by LilGL** [comment]
Oui pardon, j’étais absent ces derniers jours.
Merci pour votre retour.

Cordialement.
