### ISSUE TITLE
[API Ecoulement des cours d'eau] Comment retrouver les ressources liées ?

### ISSUE THREAD

**Issue by deeluxe74** [BRGM/hubeau#194]
Sur une feature :
```
{
      "type": "Feature",
      "properties": {
        "code_cours_eau": "M1015000",
        "code_bassin": "04",
        "libelle_cours_eau": "la Foussarde",
        "code_commune": "28010",
        "uri_reseau": "http://id.eaufrance.fr/dc/0000000134",
        "coordonnee_y_station": 6799527.075834487,
        "code_reseau": "0000000134",
        "code_projection_station": "26",
        "code_region": "24",
        "coordonnee_x_station": 553229.8208085757,
        "date_observation": "2024-10-10",
        "libelle_departement": "Eure-et-Loir",
        "libelle_station": "La Foussarde à Argenvilliers",
        "code_departement": "28",
        "uri_station": "http://id.eaufrance.fr/SiteHydro/M1011611",
        "code_station": "M1011611",
        "libelle_reseau": "Onde OFB",
        "code_ecoulement": null,
        "libelle_bassin": "Loire-Bretagne",
        "libelle_projection_station": "RGF93 / Lambert 93",
        "libelle_ecoulement": null,
        "libelle_commune": "ARGENVILLIERS",
        "uri_cours_eau": "http://id.eaufrance.fr/CoursEau_Carthage2017/M1015000",
        "libelle_region": "Centre-Val de Loire",
        "code_campagne": "98902"
      },
      .....
```

L'on possèdent différents URI vers le site `id.eaufrance.fr`, si je prend l'exemple des cours d'eau.
Je peux naviguer sur [cette page](http://id.eaufrance.fr/CoursEau_Carthage2017/M1015000) et retrouver sont geojson.

Sur télécharger JSON, je peux accéder a l'uri direct, seulement voilà le chemin :
`https://services.sandre.eaufrance.fr/geo/sandre?SERVICE=WFS&REQUEST=getFeature&VERSION=2.0.0&TYPENAME=CoursEau_Carthage2017&OUTPUTFORMAT=application/json%3B%20subtype%3Dgeojson&FILTER=%3CFilter%3E%3CPropertyIsEqualTo%3E%3CPropertyName%3ECdEntiteHydrographique%3C/PropertyName%3E%3CLiteral%3EM1015000%3C/Literal%3E%3C/PropertyIsEqualTo%3E%3C/Filter%3E`

Je ne comprend pas, comment je suis censé pouvoir construire cette url, en particulier la query TYPENAME qui semble totalement dépendant par rapport au cours d'eau en question.

Merci de votre aide.

**Comment by Supp-Hubeau** [comment]
Bonjour,

`https://services.sandre.eaufrance.fr/geo/sandre?SERVICE=WFS&REQUEST=getFeature&VERSION=2.0.0&TYPENAME=CoursEau_Carthage2017&OUTPUTFORMAT=application/json; subtype=geojson&FILTER=<Filter><PropertyIsEqualTo><PropertyName>CdEntiteHydrographique</PropertyName><Literal>M1015000</Literal></PropertyIsEqualTo></Filter>`

Cette URL ne contient deux paramètres principaux : 
- **CoursEau_Carthage2017** : qui est le jeu de données de référence utilisé (ici la BD Carthage 2017 https://www.sandre.eaufrance.fr/atlas/srv/fre/catalog.search#/metadata/deafc1b2-0d2e-4552-ad22-0227ffd777b3) que l'on retrouve également dans le _champ uri_cours_eau_.
C'est le référentiel utilisé par Hub'eau pour toutes les stations (https://hubeau.eaufrance.fr/api/v1/ecoulement/stations?format=json&size=50&fields=code_station,code_cours_eau,uri_cours_eau)
- **M1015000** : _code_cours_eau_ retourné par Hub'eau

A noter, il s'agit ici de ressources Sandre. Pour plus d'informations nous vous invitons à vous rapprocher du support technique du Sandre : https://www.sandre.eaufrance.fr/v2/page/service-support-technique.

Cordialement,
L'équipe Hub'eau

**Comment by deeluxe74** [comment]
Effectivement si je peux conclure que votre api en second paramètre sur uri_cours_eau retourne toujours le TYPENAME c'est ok.

Merci 👍

**Comment by Supp-Hubeau** [comment]
Clôture du ticket. N'hésitez pas à le réouvrir si besoin.

Cordialement,
L'équipe Hub'eau
