### ISSUE TITLE
[API Hydrométrie] Disponibilité de l'api

### ISSUE THREAD

**Issue by michael-bcq** [BRGM/hubeau#196]
Bonjour,

Nous avons observé des coupures d'accès à l'api à ces horodates
04/11/2024 01:00:00
03/11/2024 01:00:00
29/10/2024 01:00:00
27/10/2024 01:00:00
26/10/2024 01:00:00

Le format typique des requêtes est le suivant : https://hubeau.eaufrance.fr/api/v1/hydrometrie/observations_tr.xml?code_entite={station}&grandeur_hydro=H

La coupure dure généralement quelques heures et redevient opérationnel dans la matinée.
Pourriez vous, s'il vous plait, m'indiquer si des indisponibilités ont été constatées de votre part à ces dates ?
Merci d'avance pour votre retour

**Comment by Supp-Hubeau** [comment]
Bonjour,

Nous n’avons pas connaissance d'interruptions de service survenues pendant les créneaux mentionnés.  La supervision externe du endpoint des observations hydrométriques temps réels v1 ne monte aucune interruption ni ralentissement.

Comment se traduit la coupure ?
Avez-vous un code d'erreur HTTP ou simplement une absence de nouvelles données ?

Cordialement,
L'équipe Hub'eau

**Comment by michael-bcq** [comment]
Merci pour votre retour.
Pas de code d'erreur HTTP, mais une erreur SSL.

The SSL connection could not be established ---> Unable to read data from the transport connection: Une connexion existante a dû être fermée par l’hôte distant.

Ces messages apparaissent ponctuellement et bloquent l'acquisition. 
Des que l'appel est de nouveau fonctionnel, le trou de données est comblé.

**Comment by Supp-Hubeau** [comment]
Merci pour ces précisions.
Le comportement observé a été signalé aux équipes techniques pour analyse.

Cordialement,
L'équipe Hub'eau

**Comment by michael-bcq** [comment]
Bonjour,
Merci pour votre retour.
Pour la journée du 5, la coupure a été observée à 1h du matin, les données sont arrivées à 3h
Pour la journée du 6, les données horodatées entre 00h et 12h sont arrivées à 13h. Sur la journée du 7 et 8 (aujourd'hui) pas de coupure observée.
Si cela aide à votre diagnostic, je regarde en particulier la donnée d'Ignon, identifiant U121504001, mesure hauteur et débit

**Comment by Supp-Hubeau** [comment]
Bonjour,

Merci pour ces précisions.
Pendant toutes les périodes d’indisponibilité des données l'erreur est systématiquement "The SSL connection could not be established" ? ou peut-il s'agir uniquement d'une absence de données sans erreur technique ? 

Cordialement,
L'équipe Hub'eau

**Comment by michael-bcq** [comment]
L'erreur de connexion SSL n'est observée qu'à 1h00 (nous requêtons les données toutes les 15 minutes)
Il peut effectivement s'agir d'une absence de données sans erreur technique pour les autres pas de temps

**Comment by Supp-Hubeau** [comment]
Lors de l'appel, passez-vous en paramètre une date pour ne collecter que les mesures récentes ou s'agit-il d'une récupération de l’ensemble des données de la station ?

Cordialement,
L'équipe Hub'eau

**Comment by michael-bcq** [comment]
Non, pas de paramètre de date dans la requete, uniquement l'identifiant de la station et le type de mesure (H/Q)

**Comment by Supp-Hubeau** [comment]
Bonjour,

Le retard de publication constaté semble lié à un problème ayant temporairement affecté un des modules d’échanges de données en amont de la PHyC.
Une méthode de contournement ayant été trouvée et étant semble-t-il efficace, sauf défaut de transmission de la station ou du réseau de collecte, les données doivent bien désormais arriver en PHyC au moins toutes les heures et être exposées par Hub'eau dans les minutes qui suivent.

Cordialement,
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Clôture du ticket. N'hésitez pas à le réouvrir si besoin.

Cordialement,
L'équipe Hub'eau
