### ISSUE TITLE
[API Hydrométrie] Problème d'accès aux données

### ISSUE THREAD

**Issue by franziskakis-hydrique** [BRGM/hubeau#197]
Bonjour,

Nous rencontrons des erreurs lors de l'accès à l'API hydrométrie: 
erreur 500 (internal server error)

Exemple d'URL utilisée:
https://hubeau.eaufrance.fr/api/v1/hydrometrie/observations_tr?code_entite=U201203001&grandeur_hydro=Q&size=30&fields=code_station,date_obs,resultat_obs

Les données semblent disponibles sur la plateforme eaufrance.fr

Connaissez-vous la cause du problème ?

Merci d'avance pour votre diagnostic

**Comment by Supp-Hubeau** [comment]
Bonjour,

Nous confirmons qu’il s'agit d'un dysfonctionnement de l'API.
Elle devrait pouvoir être remise en service par les équipes techniques en début de matinée.

Nous vous remercions pour cotre compréhension.

Cordialement
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Retour à la normale le 1232/11/2024 10:00

Cordialement
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Clôture du ticket. N'hésitez pas à le réouvrir si besoin.

Cordialement,
L'équipe Hub'eau
