### ISSUE TITLE
[API Qualité des cours d'eau]

### ISSUE THREAD

**Issue by rimyou22** [BRGM/hubeau#198]
Bonjour,

Rencontrez-vous actuellement un problème avec l’API Qualité des cours d’eau ? Nous ne parvenons pas à accéder aux services.

Voici l’erreur que nous recevons : **502 Proxy Error.**

Cordialement,

**Comment by Supp-Hubeau** [comment]
Bonjour,

API Qualité des cours d’eau semble très fortement sollicitée ce qui impact ses temps de réponse. 
Elle est de nouveau disponible.

Cordialement,
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Clôture du ticket. N'hésitez pas à le réouvrir si besoin.

Cordialement,
L'équipe Hub'eau
