### ISSUE TITLE
[API Qualité des cours d'eau] /v2/qualite_rivieres/condition_environnementale_pc

### ISSUE THREAD

**Issue by zie225** [BRGM/hubeau#199]
Bonjour,

 comme j'aimerais bien utiliser les données de '**API Hub'Eau - Qualité physico-chimique des cours d'eau** plus précisément  **_/v2/qualite_rivieres/condition_environnementale_pc_** pour la collecte de données des Hauteurs des précipitations, je ne trouve pas assez de données historique, j'ai eu que 51 résultats après la requête. J'aimerais savoir comment résoudre ce problème pour avoir plus de résultats des anciennes données historique.?   également, je suis confronté à un problème ici  **/v2/qualite_rivieres/condition_environnementale_pc.csv**, je n'arrive pas à avoir des résultats ici en csv, je pense qu'il y a un problème quand je fais appel à l'API pour mes requêtes. vous pouvez vérifier les résultats que j'ai obtenus en JSON ici: https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/condition_environnementale_pc?code_departement=29&code_parametre=1553&fields=resultat%2C%20mnemo_remarque%2C%20libelle_resultat%2Clibelle_station%2C%20symbole_unite%2C%20date_prelevement%2Clibelle_parametre%2Clibelle_resultat%2Cdate_mesure&size=20000 avec 51 résultats.

Et également le fichier https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/condition_environnementale_pc.csv?code_departement=29&code_parametre=1553&fields=resultat%2C%20mnemo_remarque%2C%20libelle_resultat%2C%20libelle_station%2C%20symbole_unite&size=20000 avec 0 résultats.

Cordialement,

**Comment by Supp-Hubeau** [comment]
Bonjour,

Pour ce qui est de l'existence et de la profondeur des données pour le paramètre 1553, l'API expose les données qui figurent dans Naïades. Nous allons nous rapprocher des experts métier pour vous avoir un complément de réponse. 

Concernant l'export CSV, une correction sur ce point est en cours de finalisation et devrait être publiée prochainement. 

Cordialement,
L'équipe Hub'eau

**Comment by zie225** [comment]
Bonjour,

Je suis patient pour le complètement de réponse.


Cordialement,

**Comment by Supp-Hubeau** [comment]
Bonjour,

Il faut bien noter que le endpoint Hub'eau interrogé retourne des données relatives aux conditions environnementale associées aux prélèvements.

https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/condition_environnementale_pc?code_parametre=1553&code_station=04174550 

Le paramètre 1553 ne fait pas l'objet d'analyses.

https://naiades.eaufrance.fr/acces-donnees#/physicochimie/fiche-operation?stations=04174550&date=10-12-2021&supports=3

![image](https://github.com/user-attachments/assets/60a19967-8a2e-4138-8cad-4b1dab156865)

Les hauteurs des précipitations ne seront donc valorisées que dans certains cas (experts interrogés sur le sujet).

Cordialement,
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Bonjour,

Nous venons de déployer le correctif en lien avec l'export csv.

L'URL ci-dessous permet bien de récupérer les 51 réponses dans un fichier csv (veiller à supprimer les espaces après les virgules) : 
https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/condition_environnementale_pc.csv?code_departement=29&code_parametre=1553&fields=resultat,mnemo_remarque,libelle_resultat,libelle_station,symbole_unite&size=20000 

Cordialement,
L'équipe Hub'eau
