### ISSUE TITLE
Tutoriel utilisation des API avec QGIS

### ISSUE THREAD

**Issue by tvilmus** [BRGM/hubeau#2]
Suite au Hackathon, AQUASYS a réalisé un tutoriel pour afficher des stations qualités dans QGIS. Vous pouvez y accéder à l'adresse suivante: https://youtu.be/vqD56x9XEK0 N'hésitez pas à le commenter ou à nous contacter pour tout renseignement complémentaire.

**Comment by QuentinStrappazzon** [comment]
Bonjour
quelle est la procédure pour pouvoir visionner le tutoriel vidéo ?
La vidéo est en effet inaccessible car indiquée comme privée
Merci d'avance

**Comment by tvilmus** [comment]
Bonjour,  
Cette vidéo, qui était devenue obsolète, n'est plus disponible.  
N'hésitez pas à nous solliciter ici ou envoyer un mail à newshubeau@brgm.fr pour toute question.

**Comment by 20-100LV** [comment]
Bonjour,
Y a t'il eu une nouvelle vidéo de démonstration de l'utilisation des APIS dans qgis ?
Merci
