### ISSUE TITLE
[API Qualité des cours d'eau] Recuperation de donnees au delà de 20.000 rows, objectif 1000000 rows.

### ISSUE THREAD

**Issue by zie225** [BRGM/hubeau#200]

**Comment by Supp-Hubeau** [comment]
Bonjour,

Il semble y avoir eu un problème avec le message précédent. Le contenu a été supprimé.

La limite de 20000 ne s'applique pas à la traille de la page mais à la taille du résultat retourné lors d'un interrogation, toutes pages cumulées. Si vous fixez la taille de la page à 20000, le résultat devra tenir sur une seule page.

Il convient donc de segmenter les interrogation suivant des critères géographiques, temporels... afin de rester sous la limite des 20000 enregistrements.

Si votre besoin consiste à initialiser une base locale en reprenant un historique important, le site Naïades propose des exports sans doute plus adaptés (https://naiades.eaufrance.fr/france-entiere#/). Les API Hub'eau permettant de collecter les données postérieures à l'import. 

Cordialement,
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Clôture du ticket. N'hésitez pas à le réouvrir si besoin.

Cordialement,
L'équipe Hub'eau
