### ISSUE TITLE
[API Hydrométrie] Plus de données depuis 2024-11-27T20:00:00Z

### ISSUE THREAD

**Issue by jbellier** [BRGM/hubeau#202]
Bonjour à l'équipe d'Hub'Eau

Nous constatons depuis quelques jours que l'API Hydrométrie (v2) ne renvoi plus de données postérieures à 2024-11-27T20:00:00Z. Ce problème s'observe sur les 14 stations pour lesquelles nous venons faire des requêtes (toutes les 5 min), et ces stations n'ont pas l'air d'avoir de problèmes particuliers. Nous avons donc fait l'hypothèse que le problème venait de plus haut. 

Avez-vous des informations concernant ce problème ?
Merci d'avance,

**Comment by Supp-Hubeau** [comment]
Bonjour,

Les traitements d’alimentation de de la version 2 de l'API ont effectivement été interrompus. Ils ont été relancés ce matin.
Les données restent disponibles au travers de la v1 de l'API dont l'alimentation n'a pas été interrompue.

Un diagnostic est en cours.
Merci pour votre compréhension.

Cordialement,
L'équipe Hub'eau

**Comment by jbellier** [comment]
Merci pour votre réponse rapide. 

Cependant, nous avions fait la bascule de la v1 à la v2 le 12 novembre dernier, la v1 ayant alors été coupée. Etait-ce alors une coupure temporaire ? 
Jusqu'à avril 2025 (date de coupure de la v1 indiquée sur votre site), conseillez-vous de rester sur la v1, ou bien de revenir à la v2 dès que le problème a été résolu ?

**Comment by Supp-Hubeau** [comment]
Nous préconisons de continuer à travailler avec la v2, la v1 pouvant être utilisée en complément si nécessaire (il est prévu qu'elle reste en ligne jusqu'au 30/04/2025).

Cordialement,
L'équipe Hub'eau

**Comment by Supp-Hubeau** [comment]
Clôture du ticket. N'hésitez pas à le réouvrir si besoin.

Cordialement,
L'équipe Hub'eau
