### ISSUE TITLE
[API température] Données incorrectes

### ISSUE THREAD

**Issue by Maxime-le-Goupil** [BRGM/hubeau#21]
Bonjour,

En faisant des test sur l'api température, j'ai trouvé des entrées avec une date en 2045/2046.
Il y a plus de 30 000 entrées incorrectes avec cet URL qui demande toutes les mesures après une date dans le futur:
[https://hubeau.eaufrance.fr/api/v1/temperature/chronique?size=50&date_debut_mesure=2019-03-09%2019%3A30](url)
Il semblerait que le problème viendrait de la station 03047445

Bonne journée

**Comment by tvilmus** [comment]
Bonjour,

Désolé pour cette réponse tardive... Ces erreurs ont été corrigées lors de la mise à jour des données du 27 avril dernier.

Bien cordialement,
Thierry
