### ISSUE TITLE
[API Hydro] données manquantes par rapport à ADES

### ISSUE THREAD

**Issue by MarcParm** [BRGM/hubeau#22]
Bonjour,

Il semble qu'il manque ponctuellement des données dans les imports hubeau par rapport aux données présentes sur ADES. Par exemple, le points d'eau 00271X0002/P2 au 02/01/2019, présent sur ADES:
https://ades.eaufrance.fr/Fiche/PtEau?Code=00271X0002/P2#mesures_tab_donnees
et absent de hubeau:
https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques.csv?code_bss=00271X0002%2FP2&date_debut_mesure=2019-01-01&date_fin_mesure=2019-01-10&sort=desc

A moins que j'ai fait une erreur quelque part ?

Cordialement,

**Comment by tvilmus** [comment]
Bonjour,
Le problème de mise à jour différée des collections Hub'Eau est résolu depuis le 23 avril dernier. Vous trouverez maintenant dans Hub'Eau l'intégralité des données piézométriques disponibles dans ADES, avec la même fréquence de mise à jour.
Bien cordialement,
Thierry
