### ISSUE TITLE
[API Qualité des cours d'eau ] - Erreur lors de la récupération des analyses 

### ISSUE THREAD

**Issue by GuillaumeDef** [BRGM/hubeau#23]
Bonjour, 

Il y a une station qui comporte 28865 analyses hors lorsque nous arrivons à cette URL dans l'attribut next : 
https://hubeau.eaufrance.fr/api/v1/qualite_rivieres/analyse_pc?format=json&code_station=04180100&fields=code_station,libelle_station,code_support,libelle_support,code_fraction,libelle_fraction,code_methode_analyse,nom_methode_analyse,code_methode_extraction,nom_methode_extraction,code_accreditation,mnemo_accreditation,code_parametre,libelle_parametre,date_analyse,heure_analyse,date_prelevement,heure_prelevement,resultat,code_unite,symbole_unite,code_remarque,mnemo_remarque,code_insitu,libelle_insitu,code_difficulte_analyse,mnemo_difficulte_analyse,limite_detection,limite_quantification,limite_saturation,agrement,code_statut,mnemo_statut,code_qualification,libelle_qualification,commentaires_analyse,commentaires_resultat_analyse,code_reseau,nom_reseau,code_producteur,nom_producteur,code_preleveur,nom_preleveur,code_laboratoire,nom_laboratoire&page=41&size=500

une erreur apparait ! 

`{
    "code": "InvalidRequest",
    "message": "Invalid analysePc request",
    "field_errors": [
        {
            "code": "ValidatePageDepth",
            "message": "Please refine your query. The multiplication of `page` * `size` parameters can not be more than 20000",
            "field": "page"
        }
    ]
}`

Comment peut-on résoudre ce problème ? 

Merci d'avance

DEFAY Guillaume

**Comment by labbev** [comment]
Bonjour,
Vous vous heurtez à la limite fixée de 20000 résultats maximum par requête (pagination comprise).
Pour contourner cette limite dans votre cas, je suggère de scinder la requête en 2, sur une base temporelle liée à la date de prélèvement.
Ainsi, cela donne, avec une date de coupure arbitrairement choisie au 2013-01-01 : 

1ere requête (retourne les 500 premiers résultats sur 18273 comptabilisés dont la date de prélèvement est plus récente que le 1er janvier 2013) :

https://hubeau.eaufrance.fr/api/v1/qualite_rivieres/analyse_pc?format=json&code_station=04180100&fields=code_station,libelle_station,code_support,libelle_support,code_fraction,libelle_fraction,code_methode_analyse,nom_methode_analyse,code_methode_extraction,nom_methode_extraction,code_accreditation,mnemo_accreditation,code_parametre,libelle_parametre,date_analyse,heure_analyse,date_prelevement,heure_prelevement,resultat,code_unite,symbole_unite,code_remarque,mnemo_remarque,code_insitu,libelle_insitu,code_difficulte_analyse,mnemo_difficulte_analyse,limite_detection,limite_quantification,limite_saturation,agrement,code_statut,mnemo_statut,code_qualification,libelle_qualification,commentaires_analyse,commentaires_resultat_analyse,code_reseau,nom_reseau,code_producteur,nom_producteur,code_preleveur,nom_preleveur,code_laboratoire,nom_laboratoire&page=1&size=500&date_debut_prelevement=2013-01-01

et la seconde requête (retourne les 500 premiers résultats sur 10592 comptabilisés dont la date de prélèvement est antérieur au 1er janvier 2013) :

https://hubeau.eaufrance.fr/api/v1/qualite_rivieres/analyse_pc?format=json&code_station=04180100&fields=code_station,libelle_station,code_support,libelle_support,code_fraction,libelle_fraction,code_methode_analyse,nom_methode_analyse,code_methode_extraction,nom_methode_extraction,code_accreditation,mnemo_accreditation,code_parametre,libelle_parametre,date_analyse,heure_analyse,date_prelevement,heure_prelevement,resultat,code_unite,symbole_unite,code_remarque,mnemo_remarque,code_insitu,libelle_insitu,code_difficulte_analyse,mnemo_difficulte_analyse,limite_detection,limite_quantification,limite_saturation,agrement,code_statut,mnemo_statut,code_qualification,libelle_qualification,commentaires_analyse,commentaires_resultat_analyse,code_reseau,nom_reseau,code_producteur,nom_producteur,code_preleveur,nom_preleveur,code_laboratoire,nom_laboratoire&page=1&size=500&date_fin_prelevement=2013-01-01

ce qui permet bien de ramener au final (après parcours des pages) les 28865 résultats attendus.

Cordialement

**Comment by GuillaumeDef** [comment]
Ok, merci pour votre rapidité de retour. 

Pour information, nous avons découpé les différents appels par année. 

Dans la description des objets en retour, ce serait assez intéressant d'avoir non pas 0 mais 0.0. En effet, pour les limites de détection, quantification et autre ... je ne sais pas si cela est possible ? Voulez-vous que je recrée un issue pour cette évolution ?

Cordialement

DEFAY Guillaume

**Comment by tvilmus** [comment]
Bonjour,
Oui, il vaut mieux créer une nouvelle issue pour votre demande d'évolution.
Merci !
