### ISSUE TITLE
[API Qualité des cours d'eau] - [condition_environnementale_pc] multiples résultats identiques 

### ISSUE THREAD

**Issue by eptbsn-ariviere** [BRGM/hubeau#24]
Bonjour,
Il semble qu'il y ait un problème avec le retour de l'appel suivant (pour une station à une date donnée) :
https://hubeau.eaufrance.fr/api/v1/qualite_rivieres/condition_environnementale_pc?code_station=04057000&date_debut_prelevement=2015-09-17&date_fin_prelevement=2015-09-17&format=json

La première page contient 26999 items dans data, et les mêmes paramètres qui sont répétées plus de 1000 fois (exemple : "code_parametre":"1418") .
En outre, le count annonce 1274 résultats, là aussi cela semble incohérent, le nombre de paramètres mesurés est rarement supérieur à 30 pour les conditions environnementales.
Merci de bien vouloir corriger cela.
Cordialement.

**Comment by eptbsn-ariviere** [comment]
Bonjour,
petit up, car le problème semble toujours persister.

**Comment by tvilmus** [comment]
Bonjour,
La v2 de l'API a résolu le problème : 
https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/condition_environnementale_pc?code_station=04057000&date_debut_prelevement=2015-09-17&date_fin_prelevement=2015-09-17&format=json  
renvoie 27 résultats.  
Confirmez-vous la résolution du problème ?

**Comment by tvilmus** [comment]
Je clôt le ticket, n'hésitez pas à le réouvrir si besoin.
