### ISSUE TITLE
[API Prélèvements en eau] - Erreur lors de la récupération des ouvrages

### ISSUE THREAD

**Issue by GuillaumeDef** [BRGM/hubeau#25]
Bonjour, 

Nous rencontrons un problème sur la récupération des ouvrages lorsque nous filtrons les "fields" de retour. Par exemple, cette URL fonctionne sans filtre :  https://hubeau.eaufrance.fr/api/vbeta/prelevements/referentiel/ouvrages?format=json&size=200&code_ouvrage=OPR0000065205

Si nous rajoutons le filtre des fields, il nous manque des informations pourtant présentent dans le premier appel (ex: longitude, latitude)

https://hubeau.eaufrance.fr/api/vbeta/prelevements/referentiel/ouvrages?format=json&size=200&fields=code_ouvrage,longitude,latitude&code_ouvrage=OPR0000065205

Bon courage

Bonne journée

DEFAY Guillaume

**Comment by tvilmus** [comment]
Bonjour,

Effectivement la propriété fields reste expérimentale et n'est pas entièrement stable : en particulier, comme vous l'avez constaté, les latitudes et longitudes passent à null. C'est un problème qui est identifié pour la plupart des APIs et qui est dans notre liste de bugs à corriger.

Dans l'attente, nous vous conseillons de récupérer l'ensemble des champs, donc sans utiliser le filtre "fields".

Bien cordialement,
Thierry

**Comment by tvilmus** [comment]
Bonjour,
L'API est passée en v1, ce qui a corrigé le problème et de nombreuses autres choses.  
https://hubeau.eaufrance.fr/api/v1/prelevements/referentiel/ouvrages?format=json&size=200&fields=code_ouvrage,longitude,latitude&code_ouvrage=OPR0000065205  

Voir  https://hubeau.eaufrance.fr/news/api-prelevements-en-eau-passage-en-v1
