### ISSUE TITLE
[API Prélèvement en eau] nom de l'ouvrage dans les chroniques

### ISSUE THREAD

**Issue by EmilieEPLoire** [BRGM/hubeau#26]
Pensez-vous qu'il soit possible d'avoir le nom de l'ouvrage dans l'API des chroniques ? Pour le reste, je n'ai rencontré aucune difficulté. J'attends d'avoir les coordonnées afin de pouvoir faire une sélection géographique directement via l'API.

Merci,

Emilie

**Comment by EmilieEPLoire** [comment]
Pensez-vous qu'il soit possible d'avoir le nom de l'ouvrage dans l'API des chroniques ? Pour le reste, je n'ai rencontré aucune difficulté. J'attends d'avoir les coordonnées afin de pouvoir faire une sélection géographique directement via l'API.

**Comment by tvilmus** [comment]
Bonjour,
et désolé pour ce délai de réponse si long !

L'API Prélèvements est restée au stade beta bien plus longtemps que prévu. Aujourd'hui, nous entamons les corrections pour un passage en production qui devrait avoir lieu vers avril-mai. 

L'opération chroniques comportera le nom de l'ouvrage de prélèvement comme vous l'avez demandé. 
Parmi les autres changements, il y aura : 
  - la mise à disposition des coordonnées pour les points de prélèvement et les ouvrages (floutés au centroïde de la commune pour les points et ouvrages AEP) ;
  - une simplification de la codification des usages ;
  - la correction d'un bug sur les codes des entités hydrogéologiques ;
  - l'ajout pour les ouvrages de l'identifiant local (code producteur), du point de prélèvement référent et des noms des plans d'eau hors BD Carthage.

Merci de nous avoir remonté votre besoin (à l'avenir nous répondrons plus vite :) !
Bien cordialement,
Thierry

**Comment by tvilmus** [comment]
Bonjour Emilie,  
  
Mieux vaut tard que jamais...  
L'API est (enfin) passée en v1.  
L'opération chroniques comprend désormais le nom de l'ouvrage de prélèvement et bien d'autres choses. Voir https://hubeau.eaufrance.fr/news/api-prelevements-en-eau-passage-en-v1  
  
Bien cordialement,  
Thierry

**Comment by EmilieEPLoire** [comment]
Bonjour Thierry,

super, merci beaucoup. J’ai adapté mon code, tout fonctionne.

Bien cordialement,

Emilie BIGORNE
-------------------------
Chargée de mission géomatique
Direction du développement et de la gestion territorialisée
Etablissement public Loire
Tel : 02 46 47 03 19
www.eptb-loire.fr<http://www.eptb-loire.fr/>



De : Thierry Vilmus ***@***.***>
Envoyé : mercredi 16 juin 2021 19:51
À : BRGM/hubeau ***@***.***>
Cc : emilie bigorne ***@***.***>; Author ***@***.***>
Objet : Re: [BRGM/hubeau] [API Prélèvement en eau] nom de l'ouvrage dans les chroniques (#26)


Bonjour Emilie,

Mieux vaut tard que jamais...
L'API est (enfin) passée en v1.
L'opération chroniques comprend désormais le nom de l'ouvrage de prélèvement et bien d'autres choses. Voir https://hubeau.eaufrance.fr/news/api-prelevements-en-eau-passage-en-v1

Bien cordialement,
Thierry
