### ISSUE TITLE
[API Prélèvements en eau] - Champs libelle_precision_coord toujours null

### ISSUE THREAD

**Issue by d-william** [BRGM/hubeau#27]
Bonjour,

Le champs "libelle_precision_coord" semble toujours valoir "null" pour l’opération /vbeta/prelevements/referentiel/points_prelevement malgré un code_precision_coord bien définit.

l’opération /vbeta/prelevements/referentiel/ouvrages n'a pas ce problème.

Merci

**Comment by tvilmus** [comment]
Bonjour,

Merci pour ce signalement. Le bug sera corrigé lors du passage de la version beta à la version de production (prévu pour avril-mai 2020). Dans la version beta actuelle, les champs "libelle_precision_coord" sont de toutes façons inutiles vu que toutes les coordonnées sont fictives.

Bien cordialement,
Thierry

**Comment by tvilmus** [comment]
Bonjour,  

L'API est passée en v1.  
Cette version v1 apporte la correction du bug que vous avez signalé, ainsi que bien d'autres choses. Voir https://hubeau.eaufrance.fr/news/api-prelevements-en-eau-passage-en-v1

Bien cordialement,
Thierry
