### ISSUE TITLE
[API Hydro] Calcul du débit journalier à partir des observations_tr?

### ISSUE THREAD

**Issue by francoistilmant** [BRGM/hubeau#28]
Bonjour, 
Nous développons actuellement une plateforme de prévision des étiages (projet PREMHYCE) et nous souhaiterions utiliser l'API Hydrométrie pour récupérer les observations de la dernière semaine écoulée au pas de temps journalier. 
Ceci nous permettra de corriger les erreurs de nos modèles hydrologiques sur les derniers pas de temps en assimilant la donnée observée.

Dans le ticket #9, vous parlez du paramètre timestep qui permet d'introduire une notion de pas de temps dans les requêtes. 
Comment ce paramètre fonctionne-t-il? 
Si timestep = 60, ne retient-on qu'une valeur par heure ou fait-on une moyenne horaire à partir d'une donnée à pas de temps plus fin (5 min par exemple)? 

Ce paramètre étant limité à 60, y a-t-il une routine permettant de passer d'un débit à pas de temps variable (ou fixe mais fin) à un débit journalier? 
Si oui, quelle est la convention temporelle retenue dans ce cas pour le calcul du débit journalier?
Merci d'avance de vos réponses.
 Bien cordialement
François

**Comment by tvilmus** [comment]
Bonjour,

Le paramètre timestep fonctionne selon votre première hypothèse : on retient une valeur toutes les <timestep> minutes. Nous regardons dans la journée s'il est possible d'augmenter la valeur maximale de ce paramètre à quelque chose comme 1440, pour permettre de ne retenir qu'une valeur par jour.

Il n'existe actuellement pas de routine permettant de calculer un débit moyen journalier. Cependant, nous avons repris les discussions à ce sujet avec le SCHAPI, et il est probable que nous mettions à disposition d'ici la fin de l'année un nouvel "endpoint" observations_elaborees qui permette de récupérer les débits moyens journaliers.

Bien cordialement,
Thierry

**Comment by paumillet** [comment]
Bonjour,

La mise à disposition de ce nouvel endpoint `observations_elaborees` est-elle toujours d'actualité ?
Si oui, quelles seraient les grandeurs élaborées à disposition ?

Merci !

**Comment by tvilmus** [comment]
Bonjour, 
Le endpoint obs_elab est disponible depuis le 24 novembre 2021. 
Les grandeurs élaborées disponibles sont les débits moyens journaliers (QmJ) et mensuels (QmM).
