### ISSUE TITLE
[API Piézométrie] - ajout des codes masses d'eau (requête et résultat)

### ISSUE THREAD

**Issue by tgrandje** [BRGM/hubeau#29]
Bonjour

Serait-il possible d'ajouter la liaison aux masses d'eau (état des lieux et rapportage) à l'API Piézométrie de la même manière que sur l'API "qualité des nappes" ?

Actuellement, seule la liaison avec les entités BD LISA est disponible (la liaison entre BDLISA et masses d'eau n'étant a priori faisable qu'à partir de l'état des lieux 2019, pas encore disponible).

Dans l'attente, j'ai trouvé une liaison entre masses d'eau "rapportage" et piézomètres dans les bases de données [waterbase quantity](https://www.eea.europa.eu/data-and-maps/data/waterbase-water-quantity-11) de l'EEA ; ce sont les données remontées par l'Etat français auprès de la commission européenne dans le cadre de la directive cadre sur l'eau.

Par exemple dans cette base de données :
`SELECT WB.waterBodyIdentifier, WB.monitoringSiteIdentifier FROM MonitoringSite_DerivedData AS WB WHERE WB.waterBodyIdentifier IS 'FRAG015'`
donne
```
waterBodyIdentifier monitoringSiteIdentifier
FRAG015 FR00143C0079-F1
FRAG015 FR00155C0017-F1
FRAG015 FR00143A0008-F1
```
ce qui permet ensuite d'accéder aux niveaux des piézomètres concernés.

Si l'on pouvait au moins intégrer cette table dans l'API, cela permettrait d'avoir un fonctionnement API "pur" pour lister et collecter les données recherchées.

Bien cordialement
Thomas Grandjean
Dreal HdF

**Comment by tvilmus** [comment]
Bonjour,

Mieux vaut tard que jamais !
Nous avons fait évoluer l'opération stations de l'API Piézométrie. Vous pouvez maintenant récupérer le code, le nom et l'URI de la masse d'eau captée (version état des lieux), ainsi que d'autres attributs :
http://hubeau.eaufrance.fr/actualites/informations-supplementaires-disponibles-piezometres
Bien cordialement,
Thierry Vilmus
