### ISSUE TITLE
[API Poisson] Code poisson BLN - nom_poisson

### ISSUE THREAD

**Issue by arnnow** [BRGM/hubeau#30]
Bonjour,

L'API poisson ne remonte pas de nom_cummun pour le code [BLN](http://hubeau.eaufrance.fr/api/v0/etat_piscicole/code_espece_poisson?code=BLN&pretty)

Elle remonte bien un nom_latin.
Le nom_commun semble être celui remonté par l'api  (api/v0/etat_piscicole/poissons)
```
    "code_espece_poisson" : "BLN",
    "nom_poisson" : "\"\"",
```

Est-il possible de l'ajouter ?

Arnaud

**Comment by tvilmus** [comment]
Bonjour, 

Les opérations code_espece_poisson et poissons comprennent en effet 8 codes espèces pour lequel le nom commun est vide : BLN (Blageon), LPX (Lamproie), ATH (Athérine), PHX (Vairon), COR (Corégone) et GOX, BBX et CAX qui correspondent à des genres dans les cas où on n'a pas pu déterminer l'espèce. 
Les noms des 5 espèces vont être intégrés dans les 2 opérations code_espece_poisson et poissons. Par contre les noms communs de GOX, BBX et CAX vont rester vides car s'agissant de genres, on emploie le nom latin.

Merci pour le signalement !
Bien cordialement,
Thierry

**Comment by tvilmus** [comment]
Les corrections sont maintenant effectives pour les opérations code_espece_poisson et poissons.
