### ISSUE TITLE
API Piézométrie: Chroniques et chroniqes_tr

### ISSUE THREAD

**Issue by sbarthon** [BRGM/hubeau#31]
Nous utilisons ces API pour alimenter des piézomètres de contrôles pour certains clients. Seulement, certains sites n'ont pas de suivis réguliers. Des ruptures sont présentes dans les coures et de nombreux points initiaux sont créés. Cette information n'est pas présente dans les retours des API ce qui fausse complètement la valorisation des chroniques. Voici un exemple avec rupture: 03514X0081/PZ
https://ades.eaufrance.fr/Fiche/PtEau?code=03514X0081/PZ#mesures_graphiques
et l'appel sur Hubeau:
https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques?code_bss=03514X0081%2FPZ&size=20&sort=desc

Merci d'avance d'ajouter cette information dans les retours Json

**Comment by tvilmus** [comment]
Bonjour,
L'information sur la continuité des courbes a été ajoutée à la méthode chroniques, ainsi que les informations sur le producteur, la nature de la mesure et la profondeur de l'eau par rapport au repère de mesure.

Bien cordialement,
Thierry Vilmus

**Comment by sbarthon** [comment]
Super! Merci pour cette modification. Ca fonctionne pour l'API chroniques. Très pratique pour nos solutions.

Pour info, dans le paragraphe "2. Récupérer la chronique piézométrique complète du piézomètre 06252X0063/PZ1 identifié à l'étape précédente", l'exemple ne correspond plus aux nouveaux champs ainsi que la liste des changements sur 2020.

**Comment by tvilmus** [comment]
Merci pour le signalement. Le site a été mis à jour.
