### ISSUE TITLE
Station qualité non trouvé sur l'API Qualité

### ISSUE THREAD

**Issue by sbarthon** [BRGM/hubeau#32]
Bonjour,
nous utilisons l'API Qualité des cours d'eau et nous avons quelques retours d'utilisateurs quant aux données disponibles. Par exemple, les 2 stations 04146850 et 06750945 sont bien disponibles sur le Sandre:
http://www.sandre.eaufrance.fr/urn.php?urn=urn:sandre:donnees:StationMesureEauxSurface:FRA:code:06750945:::::html
http://www.sandre.eaufrance.fr/urn.php?urn=urn:sandre:donnees:StationMesureEauxSurface:FRA:code:04146850:::::html

Mais nous n'en trouvons qu'une sur Hubeau. La station n'est pas disponible:
https://hubeau.eaufrance.fr/api/v1/qualite_rivieres/station_pc?code_station=06750945&size=20&exact_count=true&format=json

Est ce qu'il y a une raison ?

**Comment by tvilmus** [comment]
Bonjour,
Hub'Eau diffuse les données qui sont présentes dans [Naïades](http://naiades.eaufrance.fr/acces-donnees#/physicochimie) (avec un léger décalage de mise à jour). Or, la station 06750945 n'est pas présente dans Naïades...
Cordialement,
Thierry

**Comment by sbarthon** [comment]
Ok. Par contre, 2 remarques:
- 04146850: elle n'est pas sur Naiades et pourtant elle est sur Hubeau
- 06750945 et pourtant elle est sur le Sandre...

J'ai l'impression que le problème est donc plutôt sur Naiades mais il n'y a pas de lien pour poser une question.

**Comment by antonio-andrade** [comment]
Bonjour,

Par défaut, Naïades fixe les recherches de données sur les 3 dernières années de prélèvement ou mesure. Il n'y a pas de données sur cette période pour la station 04146850. En [recherchant les données collectées depuis le 1er jan. 1970](http://www.naiades.eaufrance.fr/acces-donnees#/physicochimie/resultats?debut=01-01-1970&fin=10-04-2020&stations=04146850), Naïades fournit des données pour la période 1994-1996.

La [station 06750945](http://id.eaufrance.fr/stq/06750945) est bien référencée par le Sandre. Néanmoins, aucune donnée de physicochimie n'est diffusée par Naïades. A noter, des [données sont disponibles](http://www.naiades.eaufrance.fr/acces-donnees#/physicochimie/resultats?debut=01-01-1970&fin=10-04-2020&stations=06750950) pour la station 06750950. Vous pouvez contacter l'agence de l'eau Rhône-Méditerranée-Corse pour tout info complémentaire sur les données disponibles.

Enfin, concernant Naïades, vous pouvez adresser vos questions via le [formulaire de contact](http://www.naiades.eaufrance.fr/formulaire/contact).

Cordialement,
Antonio Andrade
