### ISSUE TITLE
Récupération données poisson depuis son nom

### ISSUE THREAD

**Issue by JustineDgst** [BRGM/hubeau#33]
Bonjour,
Est-ce que quelqu'un saurait quelle requête nous devons effectuer pour récupérer les données d'un poisson, par exemple l'Ablette, en donnant seulement son nom ?
Pour le moment je n'arrive que à récupérer cela en fonction du code_espece_poisson avec la requête suivante :
[https://hubeau.eaufrance.fr/api/v0/etat_piscicole/poissons?code_espece_poisson=ABL&size=20](https://hubeau.eaufrance.fr/api/v0/etat_piscicole/poissons?code_espece_poisson=ABL&size=20
)
Merci par avance si vous arrivez à m'expliquer comment faire.
Cordialement
Justine Dugast

**Comment by tvilmus** [comment]
Bonjour,

Effectivement on ne peut appeler la méthode "**poissons**" qu'avec le code et pas par nom. Pour avoir la liste des codes, utilisez la méthode "**code_espece_poisson**" :
[https://hubeau.eaufrance.fr/api/v0/etat_piscicole/code_espece_poisson?size=200](https://hubeau.eaufrance.fr/api/v0/etat_piscicole/code_espece_poisson?size=200)
vous donnera les correspondances entre codes OFB et SANDRE ainsi que noms latins et français des 195 espèces de poissons répertoriées.
A noter que le code à utiliser ensuite dans la méthode "poissons" est le code OFB (champ "code") et non le code SANDRE (champ "code_taxon"). 
Pas très pratique j'en conviens ! Il serait mieux de pouvoir interroger directement par le nom, ce qui sera pôssible dans la future API Hydrobiologie prévue pour cette année. Outre les poissons, elle diffusera également les données sur les macroinvertébrés, les diatomées et les macrophytes.

Alternativement, vous pouvez utiliser l'API du SANDRE mais qui à ma connaissance n'est interrogeable qu'avec le nom latin. Par exemple : [https://api.sandre.eaufrance.fr/referentiels/v1/apt.json?filter=%3CFilter%3E%3CIS%3E%3CField%3ENomLatinAppelTaxon%3C%2FField%3E%3CValue%3EAlburnus+alburnus%3C%2FValue%3E%3C%2FIS%3E%3C%2FFilter%3E](https://api.sandre.eaufrance.fr/referentiels/v1/apt.json?filter=%3CFilter%3E%3CIS%3E%3CField%3ENomLatinAppelTaxon%3C%2FField%3E%3CValue%3EAlburnus+alburnus%3C%2FValue%3E%3C%2FIS%3E%3C%2FFilter%3E)
vous donnera le code OFB de l'Ablette. L'information est à lire sous CodeAlternatifAp, dans CdAlternatif là où OrgCdAlternatif="ASPE" (la base de données de l'OFB). Pas vraiment simple mais ça a le mérite d'exister !

Bien cordialement,
Thierry

**Comment by antonio-andrade** [comment]
Bonjour,

L'[API Référentiel du Sandre](http://www.sandre.eaufrance.fr/api-referentiel#) permet de rechercher un taxon à partir d'un nom commun sous réserve de renseignement de cette donnée facultative. En effet, le critère _filter_ accepte une expression XPath pour rechercher un ou plusieurs éléments dans le fichier XML associé à un référentiel Sandre. Dans votre exemple, les données de l'ablette peuvent être obtenues via l'URL suivante :

https://api.sandre.eaufrance.fr/referentiels/v1/apt.json?outputSchema=SANDREv3.1&filter=%3CFilter%3E%3CIS%3E%3CField%3E%2F%2FLbNomCommunAppelTaxon%3C%2FField%3E%3CValue%3EAblette%3C%2FValue%3E%3C%2FIS%3E%3C%2FFilter%3E

Le XPath _//LbNomCommunAppelTaxon_ permet ici d'interroger la valeur des éléments _LbNomCommunAppelTaxon_ quelque soit leur position dans l'arborescence XML.

Cordialement,
Antonio Andrade

**Comment by tvilmus** [comment]
Merci Antonio pour cette précision fort utile.
