### ISSUE TITLE
[Niveaux nappes] - Quelles unités ?

### ISSUE THREAD

**Issue by Campalo** [BRGM/hubeau#34]
Bonjour, 
Je découvre cette API, n'étant pas du métier j'aimerai connaître les unités concernant:
- niveau_nappe_eau
- profondeur_nappe

Pourriez-vous m'indiquer la documentation qui précise ces champs si elle existe?
Merci

**Comment by tvilmus** [comment]
Bonjour,
La documentation qui existe au niveau de la page de l'API https://hubeau.eaufrance.fr/page/api-piezometrie doit être complétée avec ces informations d'unités qui ne sont pour l'instant pas mentionnées.

- Les niveaux d'eau sont exprimés en mètres NGF selon le même système que les altitudes sur les cartes topographiques ; 
- Les profondeurs d'eau sont exprimées en mètres par rapport au repère de mesure. Le repère peut être le sol, le haut du tube piézométrique ou la margelle du puits par exemple.

**Comment by Campalo** [comment]
Bonjour, 
Merci pour votre explication. Je suis allez de nouveau consulter la page de l'API, les informations sur les unités sont maintenant accessibles. Merci. 

Si je prends un [exemple concret](https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques?code_bss=06252X0063%2FPZ1&size=1):
- `niveau_nappe_eau: 206.89` : l'unité étant le mètre NGF, cela veut-il dire que cette nappe d'eau est située à 206.89 mètres au-dessus du niveau de la mer ? 
- `profondeur_nappe: 7.11`:  la nappe d'eau a une profondeur de 7.11 mètres, mais quel est ici le repère de mesure ? Est-il nécessaire de connaître le repère de mesure, si oui où trouver cette information ?

**Comment by tvilmus** [comment]
Bonjour,  
  
oui pour niveau_nappe_eau.  
  
Vous n'avez pas vraiment besoin de connaître le repère de mesure, mais voici la marche à suivre si vous voulez le faire :  
Avec Hub'Eau, vous pouvez obtenir plus d'informations sur le piézomètre dans lequel est effectué la mesure, dont son altitude au sol avec  : https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/stations?code_bss=06252X0063%2FPZ1  
![ticket34_00](https://user-images.githubusercontent.com/28749963/78340692-ccd0c680-7596-11ea-8b80-ba4b6a77f19f.PNG)
Pour le piézomètre qui vous intéresse, on a altitude_station=214 m NGF.  
  
Pour encore plus d'informations vous pouvez suivre le lien qui est dans urn_bss : http://services.ades.eaufrance.fr/pointeau/06252X0063/PZ1  
Vous accédez alors à la fiche du point d'eau dans ADES, le portail national des données sur les eaux souterraines. Vous avez alors des informations détaillées sur le point de mesure. Pour des informations encore plus détaillées, cliquez sur le lien "Fiche BSSEAU" dans Renseignements complémentaires en bas à gauche de la fiche ADES. Dans la partie 4. Piézométrie de cette fiche, vous constatez dans le tableau Référence altimétrique que la cote du repère est à 214m comme l'altitude de la station, c'est à dire que le repère est au niveau du sol.  
![ticket34_01](https://user-images.githubusercontent.com/28749963/78338170-91cc9400-7592-11ea-9cf6-eff12f2dcd24.PNG)
Ce qui se confirme en constatant que on a bien profondeur_nappe = `altitude_station - niveau_nappe_eau` (214 - 206,89 = 7,11).  
Notez au passage que si la précision des mesures de profondeur d'eau est de l'ordre du cm, la précision sur les altitudes est seulement de l'ordre du mètre.  
  
Pour l'exemple, voici maintenant un cas où le repère n'est pas confondu avec le sol (et où en plus il change : en effet les repères peuvent changer avec le temps lors de travaux sur le piézomètre ou de changement d'organisme chargé des mesures) : le piézomètre 10306X0034/F3.  
On ouvre sa fiche ADES : http://services.ades.eaufrance.fr/pointeau/10306X0034/F3  
ADES affiche une altitude au sol arrondie de 228m NGF. 
Clic sur Fiche BSSEAU : on constate ici que la véritable altitude au sol non arrondie est de 227,6 m NGF.  Puis dans le tableau des références altimétriques, vous voyez l'historique des repères : 
![ticket34_02](https://user-images.githubusercontent.com/28749963/78337574-73b26400-7591-11ea-87f1-31c6f1c4e4ab.PNG)  
Le 21/05/1985, le repère était à 230,63m NGF puis le 01/03/2018 le repère a changé pour s'établir à 229,85m NGF (soit environ 2m au dessus du sol). En consultant le tableau d'historique des hauteurs de repère en dessous vous constatez que le 1er repère était le sommet du tube piézométrique qui dépasse du point de mesure. L'information n'est pas renseignée pour le 2nd repère...  
  
Comment tout ceci se matérialise en interrogeant Hub'Eau ?  
Regardons les premières mesures disponibles :  
https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques?code_bss=10306X0034/F3&sort=asc&size=5&fields=date_mesure,niveau_nappe_eau,profondeur_nappe  
`sort=asc` permet de classer les mesures par date croissante  
`size=5` permet de ne prendre que les 5 premières mesures  
`fields=date_mesure,niveau_nappe_eau,profondeur_nappe` permet de filtrer les champs retournés.  
Hub'Eau renvoie les résultats suivants : 
![ticket34_03](https://user-images.githubusercontent.com/28749963/78339278-811d1d80-7594-11ea-8e66-ab54ddf14c66.PNG)  
Vous pouvez vous amuser à reconstituer la cote NGF du repère en additionnant `niveau_nappe_eau` et `profondeur_nappe` : on trouve toujours 230,63.  
Si on regarde maintenant les dernières mesures avec https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques?code_bss=10306X0034/F3&sort=desc&size=5&fields=date_mesure,niveau_nappe_eau,profondeur_nappe :  
![ticket34_04](https://user-images.githubusercontent.com/28749963/78339667-21734200-7595-11ea-9f9d-e61a0de7a7a1.PNG)  
Cette fois la somme  `niveau_nappe_eau` + `profondeur_nappe` est égale à 229,85.  

En résumé, on a toujours `niveau_nappe_eau = altitude_repere - profondeur_nappe`. L'altitude de la station qui est donnée par Hub'Eau et ADES correspond à l'altitude du sol au niveau du piézomètre. Pour connaître l'altitude du repère, il faut consulter les fiches BSSEAU ou la calculer à l'aide de la formule précédente.  
  
NB. L'opération `chroniques_tr` de Hub'Eau qui délivre les données en quasi temps-réel fournit l'information sur la cote NGF du repère, mais tous les piézomètres ne disposent pas de données en temps réel.  
https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques_tr?code_bss=10306X0034/F3&sort=desc&size=1  :  
![ticket34_05](https://user-images.githubusercontent.com/28749963/78340395-5338d880-7596-11ea-8294-610ba3f7610b.PNG)

En espérant ne pas vous avoir plus embrouillée !

**Comment by Campalo** [comment]
Merci pour cette explication claire et détaillée. 
Au sein de mon projet je n'ai pas le besoin d'aller tant en profondeur dans les données cependant je suis sûre que ce sera très utile dans d'autres projets plus pointus. 
Hâte de voir les projets qui sortiront suite à l'ouverture de l'accès aux données sur l'eau en France!

**Comment by Campalo** [comment]
Bonjour @tvilmus, 

Un court post pour partager mon [projet](https://github.com/Campalo/FrenchWaters) finalisé utilisant l'api piézométrie de Hub'eau. 

Merci pour votre aide, et bonne continuation

**Comment by tvilmus** [comment]
Merci @Campalo  pour ce retour !
Nous allons référencer votre projet sur [la page des ré-utilisateurs de Hub'Eau](https://hubeau.eaufrance.fr/page/ils-nous-utilisent)
