### ISSUE TITLE
API référentiel stations hydro - Réseaux récupérés

### ISSUE THREAD

**Issue by sbarthon** [BRGM/hubeau#35]
Bonjour,

en utilisant l'API Hubeau pour récupérer une liste de stations (https://hubeau.eaufrance.fr/api/v1/hydrometrie/referentiel/stations.csv?code_departement=19), nous récupérons une liste de stations avec un champ "code_sandre_reseau_station". Il contient bien une liste de codes séparés par des ,. Par exemple pour la station "L0010610", nous récupérons les réseaux "POH013,POH049,POH114,POH902". Seulement, nous ne trouvons pas la définition de ces réseaux sur http://www.sandre.eaufrance.fr/Rechercher-une-donnee-d-un-jeu

Ou peut on retrouver la définition des réseaux ?

Merci d'avance

**Comment by antonio-andrade** [comment]
Bonjour,

Après avoir consulté le [SCHAPI](hydro3@developpement-durable.gouv.fr), service du ministère de l'environnement chargé de l'administration de la [banque HYDRO](http://www.hydro.eaufrance.fr/), il apparaît qu'une partie des réseaux de mesure n'est pas encore standardisé par le SANDRE. Il s'agit de réseaux propres à la problématique hydrométrie ou prévision des crues du réseaux Vigicrues et dont l'identifiant commence par POH (Plan d'Organisation de l'Hydrométrie) ou RIC (Règlement d'Information sur les Crues). La standardisation de ces codes sera évoquée lors d'un prochain comité de pilotage de la [banque HYDRO](http://www.hydro.eaufrance.fr/).

Par ailleurs, il vous faut ajouter un 0 au début des codes des réseaux Sandre (exemple : la station hydrométrique A276011001 est associée au [réseau Sandre 0100000009](http://id.eaufrance.fr/dc/0100000009) et non 100000009). Cette anomalie est en cours de correction. Sa prise en compte par Hub'eau pourrait réclamer plusieurs semaines ou mois.

Cordialement,

**Comment by sbarthon** [comment]
Bonjour,

merci pour ces retours.

Cordialement

[image: aQuasys] <https://www.aquasys.fr/>

[image: Pack aQuasys]
*Stéphane Barthon*
Président

stephane.barthon@aquasys.fr
33 (0)9 51 72 41 72   |   33 (0)6 70 75 41 97
2, rue de Nantes - 44170 Port-Saint-Père - France


Le mer. 29 avr. 2020 à 10:41, antonio-andrade <notifications@github.com> a
écrit :
