### ISSUE TITLE
[API Hydro] Appels successifs automatiques

### ISSUE THREAD

**Issue by jwijting** [BRGM/hubeau#36]
Bonjour,

Je fais appel à l'API hydro de manière automatique, en utilisant l'attribut next pour parcourir l'ensemble des données de la chronique, et finis par recevoir une erreur 500 au bout de quelques appels (nb variable, moins de 10 lors de mes derniers tests).
Est-ce une sécurité de votre côté ? Comment puis-je faire ? 

Merci,

J. Wijting

**Comment by axel584** [comment]
Bonjour,
Pouvez-vous nous fournir votre script/programme afin que nous puissions reproduire le problème de notre côté et tenter de le résoudre ? 
Vous pouvez l'envoyer à l'adresse : newshubeau@brgm.fr

En vous remerciant,

Axel Rousseau

**Comment by axel584** [comment]
Vous pouvez également utiliser GIST pour nous transmettre du code et le lier au ticket : https://gist.github.com/

**Comment by tvilmus** [comment]
Bonjour,

Je ne reproduis pas le problème avec mon script php qui appelle la station N100151010…
J’ai essayé avec size=1000 (défaut de mon script) et size=100 pour être dans les mêmes conditions que vous, ça passe à chaque fois…

Pouvez-vous essayer avec size=1000 (si ça ne pose pas de problème de traitement derrière pour vous) et sans sleep entre les requêtes svp ?

Cordialement,
Thierry Vilmus
