### ISSUE TITLE
[API Prélèvements] actualisation des données

### ISSUE THREAD

**Issue by TERMEPhilippe** [BRGM/hubeau#38]
Actuellement, les données de l'API semblent moins complètes en nombre et en millésime que les données disponibles sur http://www.data.eaufrance.fr/jdd/e315633f-0930-41e8-a1c4-61fb2303039c
A titre d'exemple sur la région Pays de la Loire, on trouvera 6872 ouvrages avec l'API contre 8508 sur data.eaufrance.
Les millésimes de chroniques de l'API s'arrêtent à 2016 alors que l'AELB fournit des données de 2019.
Est-ce lié à la version bêta ou retrouvera-t-on vraiment une cohérence des données disponibles en téléchargement ?

**Comment by tvilmus** [comment]
Bonjour,

Il est prévue que l'API passe de version beta à v1 stable au second semestre 2010. Les données seront actualisées lors de ce passage à la v1, qui apportera de plus notamment les coordonnées géographiques des ouvrages et points de prélèvement.

Cordialement,
Thierry

**Comment by TERMEPhilippe** [comment]
Bonjour, une nouvelle échéance est-elle prévue pour la version stable de l'API Prélèvement ?
Merci
Philippe

**Comment by tvilmus** [comment]
Bonjour Philippe,

Oui ! Une nouvelle année ( et un nouveau budget :) ) ont permis la reprise des développements qui seront finalisés au cours du présent trimestre.

Cordialement,
Thierry

**Comment by TERMEPhilippe** [comment]
Merci Thierry,
bravo pour ces initiatives en tout cas

/*Philippe Terme*/

/Chef de projet géomatique/

/Administrateur de Sigloire/

*DREAL Pays de la Loire / SCTE / DSIT*

tel : 02 72 74 74 83

/5 rue Françoise Giroud/

/CS 16326/

/44263 NANTES Cedex 2/

**Comment by tvilmus** [comment]
Bonsoir Philippe,  

L'API est (enfin) passée en v1.
Cette version v1 comporte les mêmes données que celles actuellement présentes dans la BNPE. La v1 apporte une mise à jour mensuelle des données, ainsi que bien d'autres choses. Voir https://hubeau.eaufrance.fr/news/api-prelevements-en-eau-passage-en-v1  

Bien cordialement,  
Thierry
