### ISSUE TITLE
[API Prélèvement] Suggestion d'association du code_bss à l'ouvrage plutôt qu'au point de prélèvement

### ISSUE THREAD

**Issue by TERMEPhilippe** [BRGM/hubeau#39]
Bonjour, on ne retrouve pas dans les résultats d'une interrogation OUVRAGE, le code_entite_hydrogeo normalement renseigné pour le type SOUT comme indiqué dans la documentation.
Exemple : https://hubeau.eaufrance.fr/api/vbeta/prelevements/referentiel/ouvrages?code_type_milieu=SOUT&code_departement=44
Par contre, on trouve dans les résultats d'un prélèvement une info dupliquée (?) code_zone_hydrogeo mais également le code_bss_point_eau. Cette dernière information ne pourrait-elle pas être remontée au niveau de l'ouvrage ?
Il faudrait donc que la doc https://hubeau.eaufrance.fr/page/api-prelevements-eau#/ et les résultats effectifs soient cohérents et que le code_bss_point_eau soit remonté au niveau de l'ouvrage plutôt que du point de prélèvement.
Merci

**Comment by tvilmus** [comment]
Bonjour,

Un ouvrage peut être composé de plusieurs points de prélèvements ayant chacun leur code BSS. Ce code ne peut donc pas être renvoyé au niveau de l'ouvrage car il n'est pas forcément unique.

Le champ code_entite_hydrogeo est effectivement mal renseigné dans la version beta. Ce problème sera corrigé dans la version définitive de l'API, à sortir avant la fin de l'année (si tout va bien).

Bien cordialement,
Thierry
