### ISSUE TITLE
requête hubeau partiellement considérée en php

### ISSUE THREAD

**Issue by gregoryhydro** [BRGM/hubeau#40]
Bonjour,

Dans un premier temps, j'affiche des valeurs de hauteur sur un graphique highcharts en utilisant l'API hydrométrie.
Afin de limiter la taille du fichier j'utilise la requête suivante:

https://hubeau.eaufrance.fr/api/v1/hydrometrie/observations_tr.csv?code_entite=Y9000001&ampfields=code_site,code_station,grandeur_hydro,date_obs,resultat_obs&ampgrandeur_hydro=H&amppage=3&ampsize=200

Lorsque j'utilise ce lien dans le navigateur j'obtiens une table avec les paramètre souhaités.Mais lorsque je l'utilise dans mon code (ci-dessous), j'obtiens une table complète avec tous les champs et de grande profondeur: bien trop gros pour mon graphique. 
Pourquoi la requête PHP ne tient pas compte de mes paramètres dans ma requête hubeau?

$url='https://hubeau.eaufrance.fr/api/v1/hydrometrie/observations_tr.csv?code_entite=Y9000001&ampfields=code_site,code_station,grandeur_hydro,date_obs,resultat_obs&ampgrandeur_hydro=H&amppage=3&ampsize=200'; //table allégée
$locationfile= $_SERVER['DOCUMENT_ROOT'].'/graph/'; // dossier de destination
	$hubeaufile=$locationfile.'hata.csv';//nom du fichier à sa localisation
	$file=fopen($url,'rb');
	if($file){
		$newf= fopen($hubeaufile,'a'); //écrase le file existant
		if ($newf)
			while(!feof($file))
			{ 
			fwrite($newf, fread($file, 800000),800000);
			}
	}
	if($file){
		fclose($file);
	}
	if($newf){
		fclose($newf);
	}
 ftp_close($conn_ftp);

En vous remerciant,

**Comment by axel584** [comment]
Bonjour,
votre code contient **&amp** pour séparer les paramètres au lieu d'un simple **&**
En utilisant :
`$url='https://hubeau.eaufrance.fr/api/v1/hydrometrie/observations_tr.csv?code_entite=Y9000001&fields=code_site,code_station,grandeur_hydro,date_obs,resultat_obs&grandeur_hydro=H&page=3&size=200'; //table allégée`
Vous devriez obtenir le bon résultat.
A noter que l'ouverture du fichier avec le paramètre 'a' n'écrase pas le fichier mais "ajoute" à la suite du fichier d'autres données.
Pour écraser le fichier, il faut utiliser 'w' : 
https://www.php.net/manual/fr/function.fopen.php

Enfin, j'obtiens une erreur sur la commande "ftp_close" qui ne semble pas exister.

Bonne journée,

Axel

**Comment by gregoryhydro** [comment]
Super, je vous remercie beaucoup pour votre réponse rapide et efficace. Effectivement c'est bien l'option 'a' qui posait problème.
Bonne journée à vous.

**Comment by axel584** [comment]
De rien.
N'hésitez pas à nous recontacter en cas de soucis.

Bonne journée,

Axel Rousseau

**Comment by gregoryhydro** [comment]
Bonjour,

Une question concernant le résultats des requêtes? est-il possible d'obtenir les [resltat_obs] Q et H dans deux colonnes distinctes (plutôt qu' une ligne sur deux)?
