### ISSUE TITLE
requêtes avec H et Q sur des colonnes distinctes?

### ISSUE THREAD

**Issue by gregoryhydro** [BRGM/hubeau#41]
Bonjour,

Une question concernant le résultats des requêtes? est-il possible d'obtenir les [resltat_obs] Q et H dans deux colonnes distinctes (plutôt qu' une ligne sur deux)?

En vous remerciant

**Comment by tvilmus** [comment]
Bonjour,
Il n'est pas possible d'obtenir à la fois H et Q pour le même enregistrement. Pour chaque couple site/date-heure ou station/date-heure, il y a souvent le cas où seulement H est disponible ou seulement Q.
