### ISSUE TITLE
[API Qualité Nappe]

### ISSUE THREAD

**Issue by nworr** [BRGM/hubeau#42]
Bonjour

Pour certaines stations la valeur du count change quand la parametre size est modifié : 
exemple : 
https://hubeau.eaufrance.fr/api/v1/qualite_nappes/analyses?bss_id=06103X0018%2FF24&code_param=1340&size=3 indique un count à 13
et https://hubeau.eaufrance.fr/api/v1/qualite_nappes/analyses?bss_id=06103X0018%2FF24&code_param=1340&size=20 indique un size à 19
Le bug semble être le même en utilisant un code bss nouveau (BSSXXXXXX)

**Comment by tvilmus** [comment]
Bonjour,

Nous dupliquons les données sur plusieurs serveurs pour garantir une tolérance aux pannes et accélérer les réponses. Cependant, avec cette méthode, il arrive que les index se dé-synchronisent d'un serveur à l'autre...
Nous relançons une indexation complète cette nuit ; vous devriez retrouver une situation normale demain matin.

**Comment by tvilmus** [comment]
re-bonjour,
Environ 75% des données ont pu être ré-indexées cette nuit et ne présentent plus de problème de désynchronisation.
Les 25% restants (dont fait partie le point que vous citez en exemple) seront ré-indexés cette nuit et disponibles demain matin.

**Comment by nworr** [comment]
Ok merci la réactivité, je ferme le ticket
