### ISSUE TITLE
Gestion des continuités pour l'API Piézométrie

### ISSUE THREAD

**Issue by sbarthon** [BRGM/hubeau#43]
Bonjour,

nous utilisons les API pour la récupération des chroniques et des chroniques temps réel et nous avons repéré un problème pour la récupération des informations de continuités. Voici un cas précis sur un piézo géré par la DR Bretagne: le 02465X0061/F.

Le 03/05/2012, il y a un point initial que l'on voit sur les chroniques ADES (image 1 - https://ades.eaufrance.fr/Fiche/PtEau?code=02465X0061/F#mesures_graphiques). 

Nous avons récupéré les chroniques via Hubeau et nous n'avons pas retrouvé cette indication ce qui génère une continuité dans la chronique. (image 2). 

De plus, en consultant le visualiseur en ligne, la continuité n'est pas présente (image 3 - https://hubeau.eaufrance.fr/sites/default/files/api/demo/piezo/piezo.htm?code_dpt=35&code_bss=03884X0021%2FTF1PR).

Pourriez vous regarder d'où vient le problème ?

Merci d'avance

![ADES image 1](https://user-images.githubusercontent.com/1764899/92594364-f3f89600-f2a2-11ea-850e-2aae2db647a8.png)
![Hubeau image 3](https://user-images.githubusercontent.com/1764899/92594366-f4912c80-f2a2-11ea-8304-f8f81e25df3a.png)
![myliaQ image 2](https://user-images.githubusercontent.com/1764899/92594367-f529c300-f2a2-11ea-9516-630d69885b52.png)

**Comment by tvilmus** [comment]
Bonjour,

Les informations de continuité sont mentionnées dans les champs code_continuite et nom_continuite.

La requête  
https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques?code_bss=02465X0061%2FF&size=50&fields=date_mesure,code_continuite,nom_continuite&date_debut_mesure=2012-03-16&date_fin_mesure=2012-05-05  
montre bien qu'il y a une rupture de continuité le 2012-05-03.  

_NB. Le démonstrateur Hub'Eau, ayant été développé avant la disponibilité de ces informations, ne gère pas la continuité._
