### ISSUE TITLE
Plantage de l'API cours d'eau

### ISSUE THREAD

**Issue by sbarthon** [BRGM/hubeau#44]
Bonjour,

la page de description et de test pour l'API cours d'eau des résultats PC ne fonctionne plus. Voici l'erreur pour la station 04204300 en limitant à un paramètre ou pour l'historique.

Merci
![api cours eau](https://user-images.githubusercontent.com/1764899/92925205-6ea7e980-f43a-11ea-8d87-92e6c8610666.png)

**Comment by tvilmus** [comment]
Bonjour, ca fonctionne de notre coté, avez-vous toujours le problème ?

**Comment by sbarthon** [comment]
C'est mieux effectivement. Il n'y a plus l'erreur et je récupère bien les données. Merci
