### ISSUE TITLE
[API HYDROBIOLOGIE]_données Naïades V0

### ISSUE THREAD

**Issue by StephanieRiom** [BRGM/hubeau#45]
L'API hydrobiologie ne semble pas interroger Naïade V0 qui contient les données hydrobiologie hors poisson.
ex https://hubeau.eaufrance.fr/api/vbeta/hydrobio/taxons?code_station_hydrobio=04004100

des données (brutes, formats d'échanges .csv et .xls) existent dans Naïade V0
http://naiadesv0.eaufrance.fr/donnees

mais sont absentes de la version en cours de Naïade
http://www.naiades.eaufrance.fr/acces-donnees#/hydrobiologie/resultats?debut=01-01-2001&fin=17-09-2020&stations=04004100

**Comment by tvilmus** [comment]
Bonjour,
Effectivement, Hub'Eau ne contient que les données de la version actuelle de Naïades (v1). Les données actuellement manquantes en V1 vont y être progressivement intégrées au fur et à mesure que les Agences de l'Eau LB et RM vont transmettre leurs données. Ces données seront alors automatiquement visibles dans Hub'Eau.
