### ISSUE TITLE
[API HYDROBIOLOGIE]_requête non fonctionnelle

### ISSUE THREAD

**Issue by StephanieRiom** [BRGM/hubeau#46]
La requête présentée en exemple:
Recherche de tous les indices biologiques concernant les diatomées (dont le code SANDRE support = 13) :
https://hubeau.eaufrance.fr/api/vbeta/hydrobio/indices?size=10&code_support=13
Le résultat concerne
- les indices invertébrés (code indice : 1000, libelle_indice: IBG Normalisé)
- très peu de stations

**Comment by tvilmus** [comment]
Bonjour,  
  
Merci d'avoir signalé ce problème.  
Pour interroger les diatomées, il faut utiliser le code support 10 mais vous avez raison, des résultats d'indices biologiques sont affectés d'un mauvais support (celà concerne un peu moins de 10% des données).  
Actuellement, en interrogeant tous les indices du support diatomées, on obtient 54376 réponses dont seules 49610 correspondent effectivement à des indices diatomiques.  
Les erreurs se situent au niveau des données sources transmises à Naïades et reprises par Hub'Eau, nous ne pouvons donc pas effectuer les corrections mais nous allons signaler les problèmes aux producteurs de données.  
![ticket46_01](https://user-images.githubusercontent.com/28749963/93785369-4edca680-fc2e-11ea-969d-b14a80376d1b.PNG)
(export Naïades)  
  
Pour contourner le problème, nous vous proposons d'indiquer les codes des indices diatomiques dans le paramètre code_indice. Par exemple, la requête suivante vous permet de ne récupérer que les indices effectivement relatifs aux diatomées :  
https://hubeau.eaufrance.fr/api/vbeta/hydrobio/indices?size=300&fields=libelle_indice,code_station_hydrobio,date_prelevement,resultat_indice&code_indice=5856,1022,1080,8059,8060,1692,6335  
Avec cette requête, vous éliminez les indices invertébrés assignés par erreur au support diatomées et vous récupérez quelques indices diatomiques assignés par erreur à d'autres codes supports.  
![ticket46_02](https://user-images.githubusercontent.com/28749963/93786595-c9f28c80-fc2f-11ea-8acf-6bf84c49bba4.PNG)
