### ISSUE TITLE
[API Hydrométrie] Actualisation des données

### ISSUE THREAD

**Issue by jeanremy** [BRGM/hubeau#47]
Bonjour,

Les données remontées sur la hauteur du cours d'eau de la Loire à Nantes ne semblent s'actualiser que par "paquet". Si les données sont prises toutes les 10 minutes, leur actualisation n'a pas la même fréquence. Par exemple, il est 09:24 ce jour, et les données les plus récentes ne datent que de 9h (soit deux itérations de retard).
Ex: https://hubeau.eaufrance.fr/api/v1/hydrometrie/observations_tr?code_entite=M800001010&grandeur_hydro=H&size=2
Une capture d'écran de mauvaise qualité pour illustrer mon propos
<img width="399" alt="Capture d’écran 2020-09-21 à 09 26 21" src="https://user-images.githubusercontent.com/3785695/93741388-9c382400-fbec-11ea-9a78-366f77e77d7f.png">

Le site Vigicrues a lui aussi ce décalage: https://www.vigicrues.gouv.fr/niv3-station.php?CdEntVigiCru=9&CdStationHydro=M800001010&GrdSerie=H&ZoomInitial=3

Peut-on y faire quelque chose ?
Merci !

**Comment by tvilmus** [comment]
Bonjour,  
Nous nous fournissons à la même source de données que le site Vigicrues (données Temps Réel du SCHAPI), nous n'aurons donc jamais de données plus "fraiches" qu'eux...

**Comment by jeanremy** [comment]
Bonjour,
Ok, merci pour l'info !

**Comment by paumillet** [comment]
Bonjour,

Je pose ma question ici car la thématique est liée : serait-il possible de connaître la fréquence d'actualisation des données de l'API ?

Merci
