### ISSUE TITLE
Liste des stations piézométriques

### ISSUE THREAD

**Issue by EmilieEPLoire** [BRGM/hubeau#50]
Bonjour,

je cherche à obtenir la liste des stations piézométriques sur une bbox en activité à deux dates différentes : le 21 juin 2020 et le 20 septembre 2020. La première requête me renvoi 311 résultats, la seconde 0. Pourquoi une telle différence à 3 mois d'écart ? Y a-t-il un délai de mise à jour de cette liste ? 
Voici les deux requêtes : 
1 : https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/stations?bbox=-0.53,44.55,4.66,48.42&date_recherche=2020-06-21&format=geojson&nb_mesures_piezo_min=5400&size=2000&srid=4326
2 : https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/stations?bbox=-0.53,44.55,4.66,48.42&date_recherche=2020-09-19&format=geojson&nb_mesures_piezo_min=5400&size=2000&srid=4326

Merci pour vos explications,

Emilie

**Comment by tvilmus** [comment]
Bonjour,

Désolé pour le délai de réponse...

Ces 2 requêtes donnent maintenant des résultats proches. Avez-vous toujours le même souci avec les données actuelles ?
L'information "période d'activité" des stations n'est pas rafraichie très fréquemment, ce qui explique sans doute l'absence de résultats quand la date d'activité recherchée est trop proche de la date actuelle. 
Nous allons regarder s'il est possible d'augmenter la fréquence de rafraichissement de cette information.

Cordialement,
Thierry Vilmus

**Comment by EmilieEPLoire** [comment]
Bonjour,

Les résultats sont assez proches jusqu'à une profondeur d'environ 1 mois par rapport à la date actuelle. Un délai de rafraichissement de un ou deux mois me convient.

Merci,

Emilie
