### ISSUE TITLE
API Qualité eau souterraine

### ISSUE THREAD

**Issue by sbarthon** [BRGM/hubeau#51]
bonjour,

nous utilisons l'API Qualité des eaux souterraines à la place du WS getData d'ADES qui est très lent et régulièrement en Timeout. Cependant, dans les attributs de sortie, nous ne trouvons par le laboratoire et le préleveur. De plus, nous ne trouvons pas le support de l'analyse. Est ce que ces champs sont prévus dans une évolution ou est ce que c'est voulu ?

Merci

**Comment by tvilmus** [comment]
Bonjour,
Les attributs laboratoire et préleveur ne sont pas prévus. 
Le code support n'est en effet pas renvoyé car d'une part vous pouvez le reconstituer à partir du code fraction (code fraction 3, 22, 23 -> code support 3), d'autre part il est a priori toujours égal à 3 (eau).
