### ISSUE TITLE
API Qualité eau souterraine

### ISSUE THREAD

**Issue by Pat-Ibulaire** [BRGM/hubeau#52]
Bonjour,
Nous utilisons l'API Hubeau Qualité afin de récupérer régulièrement les dernières données disponibles. Malheureusement, nous devons à chaque fois faire appel à tout l'historique uniquement pour récupérer les dernières données.

Serait t'il possible de rajouter deux filtres "date_debut_prelevement_min" et "date_debut_prelevement_max" afin de pouvoir filtrer les données reçues en fonction de la date de prélèvement ?

Il y'a bien les filtres "date_max_maj" et "date_min_maj", mais je n'ai pas l'impression qu'ils fassent référence à la date de prélèvement.

Merci beaucoup.
Titouan Pasquet

**Comment by guiattard** [comment]
Bonjour,

Je confirme que le problème est toujours persistant.

Cordialement,

Guillaume Attard

**Comment by tvilmus** [comment]
Bonjour,

Je pense que le filtre que vous cherchez est "date_debut_prelevement".

https://hubeau.eaufrance.fr/api/v1/qualite_nappes/analyses?bss_id=BSS000XUUM&date_debut_prelevement=2010-01-01&size=20
renvoie les 625 analyses postérieures au 01/01/2010

https://hubeau.eaufrance.fr/api/v1/qualite_nappes/analyses?bss_id=BSS000XUUM&date_debut_prelevement=2019-01-01&size=20
renvoie les 220 analyses postérieures au 01/01/2019.

Cordialement,
Thierry Vilmus

**Comment by Pat-Ibulaire** [comment]
Effectivement, cela marche bien. Je suis pourtant certain d'avoir testé le "date_debut_prelevement" en novembre, et me ramenait toutes les analyses dont la date de prélèvement était égale à la date données, et non pas les analyses postérieures.
En tout cas maintenant, c'est bon pour moi.
Merci
