### ISSUE TITLE
[Démonstrateur piézo] problème d'affichage

### ISSUE THREAD

**Issue by etot** [BRGM/hubeau#54]
Bonjour
https://hubeau.eaufrance.fr/sites/default/files/api/demo/piezo/_demo_tr/
je constate un problème d’affichage sur mon laptop, je ne parviens pas à scroller pour voir le détail du point de mesure sélectionné (testé sur FF et chrome). Ma résolution : 1366x768
Merci
Grégoire

**Comment by tvilmus** [comment]
Bonjour, 
Le graphique d'évolution a été supprimé pour permettre l'affichage du lien du détail du point de mesure sur les écrans de (très) faible définition
