### ISSUE TITLE
Accès aux données d'archive

### ISSUE THREAD

**Issue by claustres** [BRGM/hubeau#55]
Nous sommes utilisateurs de l'API Hydrométrie et nous demandions s'il existait un moyen d'accéder à des données archivées au-dela d'un mois pour réaliser des études ? Si non est-ce un service que vous prévoyez de mettre en place dans le futur ?

Merci

**Comment by tvilmus** [comment]
Bonjour,
Il n'y a actuellement pas moyen d'accéder aux données historiques. 
Celà fait plusieurs années que nous travaillons avec le SCHAPI pour mettre à disposition les données historiques. Dans un premier temps, vous aurez accès cette année à un endpoint "observations élaborées" qui permettront l'accès aux débits journaliers et mensuels sur une période plus longue.
Nous n'avons pas encore d'information côté SCHAPI sur les dates de disponibilité de la plateforme qu'interrogera Hub'Eau pour mettre à disposition l'ensemble des données historiques (contenues actuellement dans la banque Hydro). Nous savons seulement que ce ne sera pas pour cette année. Par contre, nous montons un groupe utilisateur de l'API Hydrométrie pour recueillir les besoins autour de ces données historique et étudier la faisabilité d'une telle API dans Hub'Eau. Souhaitez-vous faire partie de ce groupe ?

Cordialement,
Thierry Vilmus

**Comment by claustres** [comment]
Bonjour, oui nous sommes intéressés pour participer. Un exemple de travaux nécessitant des données historiques: https://github.com/kalisio/water-level-forecasting. Mais nous avons également d'autres cas d'usage comme le "rejeu" de situation de crises pour faire du REX. Nous pourrions mettre en place notre propre stratégie d'archivage sur un object storage par exemple, mais cela a tout de même un coût non négligeable. De plus, nous n'aurions pas accès à des données antérieures à 2021. D'où ma question et je pense la nécessité qu'une structure comme le BRGM épaule ce type d'usage.

Peut-on déjà accéder à des données de la banque Hydro via d'autres moyens à ce stade ?

**Comment by tvilmus** [comment]
Votre participation sera je pense très utile !

L'archivage des données de débit fournies par l'API Hydrométrie **Temps Réel** n'est pas forcément pertinent car ce sont des données Temps Réel (Brutes) qui ne bénéficient pas des éventuelles corrections apportées par les spécialistes.

Nous souhaitons depuis longtemps diffuser les données de la banque Hydro mais nous nous heurtons à la mise à disposition des données par le SCHAPI qui évoque des difficultés techniques.

Les données de la banque Hydro sont tout de même accessibles à l'adresse suivante : http://hydro.eaufrance.fr/
Il faut créer un compte pour télécharger et ensuite la procédure est peu conviviale...

Je me réjouis que vous puissiez participer au groupe de travail (auquel participent également le SCHAPI et quelques DREAL), ce qui permettra de montrer au SCHAPI l'importance des besoins vis à vis de la mise à disposition des données historiques. On devrait initialiser ce groupe de travail dans le courant du mois.

**Comment by ThomJea** [comment]
Bonjour, 
je suis ingé en bureau d'étude (Egis Eau), nous avons besoin au quotidien des données historiques de la banque hydro pour l'hydrologie de nos projets (pluies-débits, crues de projets, stat etc. les sujets habituels). Aujourd'hui hydro.eaufrance.fr n'est pas accessible.

j'ai développé un petit embryon de client sur votre API en python, et j'espère que les données historiques seront dispo un jour pour faire des scripts centralisés sur une seule API.

je me joins à la demande de Claustres, les présentations de PHyC sur le site de l'OFB sont prometteuses mais n'y a-t-il pas une continuité de services entre hydro 2 (la banque hydro) et hydro 3 ? où peut-on accéder à l'ajustement de Gumbel d'une station en ce moment par exemple ?

par ailleurs, en fouillant un peu j'ai trouvé ce module python : https://pyspc-doc.readthedocs.io/fr/latest/description.html, est-ce à partir de ces utilitaires que vous construisez votre API ? peut-on l'utiliser ? 

cdt

**Comment by tvilmus** [comment]
Bonjour,  
Les observations élaborées (débits moyens journaliers et mensuels) sont désormais disponibles pour tout l'historique : https://hubeau.eaufrance.fr/page/api-hydrometrie#/hydrometrie/observationsElaborees  

De plus, au second semestre 2022, nous allons mener des tests sur le endpoint observations_tr pour étudier la faisabilité d'une augmentation de la profondeur des données à 2 ou 3 mois.
