### ISSUE TITLE
[API Hydrométrie] Récupération des observations récemment modifiées

### ISSUE THREAD

**Issue by gpuck** [BRGM/hubeau#60]
Bonjour,

Nous sommes utilisateurs de l'API Hydrométrie ; afin de pouvoir réaliser nos analyses nous avons besoin des dernières données brutes (l'API répond pleinement à nos besoins, merci :-)) mais également de pouvoir récupérer les données plus anciennes qui ont éventuellement été expertisées et mises à jour récemment.

Pour ce deuxième point, afin de ne pas avoir à systématiquement redemander l'ensemble des données régulièrement (et économiser des ressources), nous nous demandions si il était possible de rajouter un nouveau paramètre de filtre 'date_modification' ou un nouveau service pour ne récupérer que les observations modifiées depuis cette date 'date_modification' ?

Merci,
Grégory

**Comment by tvilmus** [comment]
Bonjour,

Nous ne gérons pas les dates de modification.  
En théorie, une donnée corrigée ou expertisée ne doit plus avoir un statut_serie de 4 (donnée brute) mais égal à 8 (donnée corrigée), 12 (donnée pré-validée) ou 16 (donnée validée).  
Le problème c'est qu'il n'est actuellement pas possible de requêter par statut_serie actuellement dans Hub'Eau mais nous ajoutons votre demande à la liste des points à discuter avec le SCHAPI.  

Bien cordialement,  
Thierry

**Comment by AmelieEPIDOR** [comment]
Bonjour, 
j'aimerais savoir si la requête par statut_serie est désormais disponible ? merci 
Amélie

**Comment by Supp-Hubeau** [comment]
Bonjour,

La version 2 de l'API permet désormais de filtrer sur le code_statut.
[hubeau.eaufrance.fr/api/v2/hydrometrie/observations_tr?code_entite=K435001010&format=json&size=15&code_statut=12](https://hubeau.eaufrance.fr/api/v2/hydrometrie/observations_tr?code_entite=K435001010&format=json&size=15&code_statut=12)

Cordialement,
Le support Hub’eau

**Comment by Supp-Hubeau** [comment]
Clôture du ticket. N'hésitez pas à le réouvrir si besoin.

Cordialement,
L'équipe Hub'eau
