### ISSUE TITLE
[API Piezométrie] Blocage d’une requête multiorigines (Cross-Origin Request)

### ISSUE THREAD

**Issue by AlexanderAbdelilah** [BRGM/hubeau#61]
Bonjour,
tout d'abord merci pour cette API fort pratique et bien conçue ! 
Je développe une application qui utilise ces données (chronique du niveau des nappes, notamment) et mes requêtes (via un fetch() en JS) sont régulièrement bloquées, car un en-tête "Allow Origin Request" serait manquant de votre côté. 
J'arrive à les contourner, mais j'aimerais savoir s'il est possible d'en savoir plus sur ce problème et la manière de le résoudre de manière pérenne ? À ma connaissance, ce header ne peut être modifié que côté serveur ?
Par avance merci !
Alexander

**Comment by tvilmus** [comment]
Bonjour,

Les requêtes Hub'Eau permettent l'accès Cross-Origin, nous venons de le re-tester :  
https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Fhubeau.eaufrance.fr%2Fapi%2Fv1%2Fniveaux_nappes%2Fstations%3Fcode_commune%3D71270%26format%3Djson%26size%3D20%26pretty&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote  
ou  
https://cors-test.codehappy.dev/?url=http%3A%2F%2Fhubeau.eaufrance.fr%2Fapi%2Fv1%2Fniveaux_nappes%2Fstations%3Fcode_commune%3D71270%26format%3Djson%26size%3D20%26pretty&method=get
  
These are the response headers received when making the request.

> access-control-allow-origin: *
> cf-cache-status: DYNAMIC
> cf-ray: 65c0b48876e01e9d-AMS
> cf-request-id: 0a8c4f294c00001e9d13bdc000000001
> connection: keep-alive
> content-type: application/json
> date: Tue, 08 Jun 2021 08:21:11 GMT
> expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> link: ; rel="first"
> server: cloudflare
> transfer-encoding: chunked
> vary: Origin,Accept-Encoding,Access-Control-Request-Method,Access-Control-Request-Headers
  
De même, des scripts de test hébergés sur un serveur externe ne génèrent pas d'erreur...  

Ou alors nous ne parlons pas de la même chose ?  
Cordialement,  
Thierry

**Comment by AlexanderAbdelilah** [comment]
Bonjour,
merci pour l'information, je vais structurer mon code différemment dans ce cas, ça doit être lié à une exécution asynchrone de mes différents composants.
Bien cordialement
