### ISSUE TITLE
Utilisation de l'API dans R / Package dédié ?

### ISSUE THREAD

**Issue by tbesse-oeb** [BRGM/hubeau#62]
Je me demandais si parmi les utilisateurs de l'API certains utilisaient R pour extraire les données et faire leurs analyses ou leurs traitements de données.

Je me disais que le développement d'un package R dédié à l'interrogation des API serait utile, à moins que ce soit déjà le cas ?

Peut-être que d'autres seraient intéressés par le partage de "recettes" de codes ou par le développement d'un package ?

**Comment by tvilmus** [comment]
Bonjour,  
Nous exposons un exemple très simple d'appel Hub'Eau avec R :  

https://github.com/BRGM/hubeau/blob/master/code_examples/Trac%C3%A9%20d'une%20chronique%20pi%C3%A9zom%C3%A9trique%20avec%20R.ipynb  

Au BRGM, nos hydrogéologues sont plusieurs à voir développé des routines R autour de Hub'Eau. Ces routines ne sont pour l'instant pas publiables en l'état mais nous travaillons sur la production de 2-3 exemples R partageables et utilisables par tous, que nous publierons sur la page https://github.com/BRGM/hubeau/tree/master/code_examples

**Comment by DDorch** [comment]
J'ai commencé à écrire un package pour interroger les APIs Hub'eau. Il est composé d'une fonction générique d'interrogation valable quelque soit l'API et l'opération et une fonction par API x operation qui met en forme le résultat sous forme de data.frame.

Le dépôt est ici: https://gitlab.irstea.fr/in-wop/hubeau

Une site de documentation du package est automatiquement mis à jour ici: http://in-wop.g-eau.fr/hubeau/

Pour l'instant, je ne me suis attaqué qu'aux API "Prélèvements en eau" et "Indicateurs des services". Je peux prioriser l'implémentation d'autres API et opération en fonction de la demande. Si vous voulez participer activement au développement du package, je peux aussi envisager de migrer le dépôt sur le compte github de mon institut: https://github.com/inrae

**Comment by DDorch** [comment]
Le développement du package avance vite... Malgré quelques bugs de l'API ()

J'ai créé un miroir sur https://github.com/inrae/hubeau et la documentation est désormais hébergée sur https://inrae.github.io/hubeau/

La liste des API et opérations associées actuellement gérées par le package sont listées ici: https://inrae.github.io/hubeau/reference/hubeau.html

**Comment by tbesse-oeb** [comment]
Bravo pour ce travail, je suis intéressé pour contribuer à ce package. N'hésitez pas à me dire ce qui vous serait utile (développement, tests ?). Je vais commencer par le tester de mon côté.

**Comment by DDorch** [comment]
> N'hésitez pas à me dire ce qui vous serait utile (développement, tests ?).

Merci! Dans un premier temps, ce serait bien d'avoir un retour sur "l'expérience utilisateur" pour savoir si la documentation est assez claire et si les messages d'erreur sont assez clairs pour qu'un utilisateur lambda puisse l'utiliser. 

N'hésitez pas à poster des tickets sur le dépôt github du package.
