### ISSUE TITLE
[API Piezométrie] Ajout d'un filtre par code réseau de mesure

### ISSUE THREAD

**Issue by tbesse-oeb** [BRGM/hubeau#63]
Bonjour,

La base ADES permet de consulter et d'extraire les données par code réseau. Ces réseaux ont également une fiche consultable sur le site public. Nous intégrons régulièrement les données du réseau n°0400000020 / Réseau de surveillance de l'état quantitatif des eaux souterraines de la région Bretagne (MO BRGM): https://ades.eaufrance.fr/Fiche/Reseau?Code=0400000020

Serait-ce possible d'ajouter le code réseau parmi les paramètres de l'API Piezométrie, pour la récupération de l'information sur les stations de mesure et pour la récupération des chroniques ? Eventuellement l'information du code et l'adresse de la page web pourraient être utiles dans les données collectées, quels que soient les paramètres de sélection des piezomètres, afin d'accéder à l'information du réseau de mesure correspondant.

Merci pour votre travail

Cordialement

Timothée Besse
Observatoire de l'Environnement en Bretagne

**Comment by tvilmus** [comment]
Bonjour Timothée, 

Des informations concernant les réseaux de mesure sont déjà présentes dans l'index qu'interroge Hub'Eau (code, mnémo et nom), par exemple pour le point BSS000SZAF (02394X0019/F)  :   

>  "liste_code_reseau": [
>           "0000000029",
>           "0400000002",
>           "0400000020",
>           "0400000127",
>           "0000000073",
>           "0000000070"
>         ],
>         "liste_mnemo_reseau": [
>           "RNESP",
>           "RBESOUPLB",
>           "RRESOUPBRE",
>           "FRGSOP",
>           "RNESOUPMOBRGM",
>           "FR_SOP"
>         ],
>         "liste_nom_reseau": [
>           "Réseau patrimonial national de suivi quantitatif des eaux souterraines",
>           "Méta réseau de suivi quantitatif des eaux souterraines du bassin Loire-Bretagne",
>           "Réseau de surveillance de l'état quantitatif des eaux souterraines de la région Bretagne (MO BRGM)",
>           "Surveillance de l'état quantitatif des eaux souterraines du bassin Loire, cours d'eau côtiers vendéens  et bretons",
>           "Réseau national de suivi quantitatif des eaux souterraines sous MO BRGM",
>           "Surveillance de l'état quantitatif des eaux souterraines de la France"
>         ],
  
L'ajout de ces informations dans Hub'Eau est donc envisageable, mais nous ne promettons pas une action rapide, car les développements portent actuellement sur d'autres thématiques.  
  
Cordialement,  
Thierry

**Comment by tbesse-oeb** [comment]
Très bien, merci pour votre réponse. Pour l'instant, le réseau étant stable, je passe par une liste de codes BSS donc pas de pb pour attendre la mise à jour de l'API.

**Comment by tbesse-oeb** [comment]
Bonjour,

S'il est possible d'associer ces modifications, le code_reseau est également absent de l'API "Qualité des nappes d'eau souterraines" pour la requête "stations" (elle est bien présente pour la requête "analyses"), mais il est possible d'interroger par "nom_reseau". Une requête par code serait plus pratique, si possible. 

Cordialement

Timothée
