### ISSUE TITLE
[API Piezometrie] Une réutilisation à référencer

### ISSUE THREAD

**Issue by tbesse-oeb** [BRGM/hubeau#64]
Bonjour,

Je découvre une utilisation de l'API Piezometrie que vous voudrez peut-être référencer sur la page "Ils nous utilisent" ?
https://frenchwaters.netlify.app/
Page GitHub : https://github.com/Campalo/FrenchWaters
Autrice : Camille @Campalo https://github.com/Campalo

**Comment by tvilmus** [comment]
Merci pour cette suggestion, nous avons déjà en fait référencé cette utilisation sur la page des ré-utilisations Github : https://github.com/BRGM/hubeau/tree/master/re-utilisations

**Comment by tbesse-oeb** [comment]
Au temps pour moi, je n'avais pas vu cette rubrique GitHub, seulement la page du site web https://hubeau.eaufrance.fr/page/ils-nous-utilisent

Merci, bonne journée !
