### ISSUE TITLE
[API Surveillance du littoral]

### ISSUE THREAD

**Issue by tbesse-oeb** [BRGM/hubeau#65]
Bonjour,

Serais-ce possible d'avoir des précisions sur les données contenues dans l'API Surveillance du Littoral ? 

J'ai compris que l'API était en version beta mais j'obtiens des données récentes (2021) associées au réseau [0000000020 Réseau National d'Observation de la qualité du milieu marin (RNO) - Matière vivante ](https://id.eaufrance.fr/dc/0000000020) qui est pourtant interrompu **depuis 2008** et remplacé par le réseau [0800000025 Réseau d’Observation de la Contamination Chimique du milieu marin (ROCCH)](https://id.eaufrance.fr/dc/0800000025). Le code 0800000025 est obsolète et doit être remplacé par les codes SANDRE 0000000105 (pour le volet Sédiments) et 0000000104 pour le volet Eau.

Merci d'avance

**Comment by antonio-andrade** [comment]
Bonjour,

Il semble effectivement étonnant que l'API diffuse les données du réseau RNO. Nous investiguons le sujet et revenons vers vous dès que possible.

Merci,

**Comment by tvilmus** [comment]
Bonjour,

Les données de Hub'Eau ont été mises à jour, ce qui permet de ne plus avoir de données associées au réseau 0000000020. 
Par ailleurs, sur les indication de l'IFREMER, les données de contaminants chimiques comprennent dorénavant les données du réseau 0000000178 correspondant au Réseau d'Observation de la Contamination Chimique du milieu marin (ROCCH) - Volet Matière vivante.  
Merci pour votre patience...
