### ISSUE TITLE
[API prélèvements] Aucune donnée dans la réponse de la requête "ouvrages" ?

### ISSUE THREAD

**Issue by tbesse-oeb** [BRGM/hubeau#71]
Bonjour,

Je n'obtiens aucune donnée lors du test de la requête par ouvrage sur la page de l'API. La requête https://hubeau.eaufrance.fr/api/v1/prelevements/referentiel/ouvrages?format=json&size=20
donne un count 0

Merci pour votre aide

Cordialement

**Comment by tvilmus** [comment]
Bonjour,  
Merci pour le signalement, c'est maintenant réparé.
