### ISSUE TITLE
[API indicateurs_services] operation "indicateurs" statut 206 sur la dernière page

### ISSUE THREAD

**Issue by DDorch** [BRGM/hubeau#72]
La requête suivante 
https://hubeau.eaufrance.fr/api/v0/indicateurs_services/indicateurs?code_indicateur=D102.0&annee=2012
renvoie 5471 résultats par paquets de 5000.

La requête de la deuxième et dernière page est: https://hubeau.eaufrance.fr/api/v0/indicateurs_services/indicateurs?code_indicateur=D102.0&annee=2012&page=2&size=5000

Cette requête renvoie un code de statut 206 mais la balise "next" est vide. Elle devrait, sauf erreur de ma part, renvoyer un code 200.

**Comment by tvilmus** [comment]
Bonjour,
Merci pour le signalement. Effectivement la requête devrait renvoyer un code de statut 200

**Comment by tvilmus** [comment]
Bonjour,  
En fait, le code 206 Partial Content doit toujours être renvoyé si le nombre d'éléments renvoyé est inférieur au nombre d'éléments disponibles.  
En revanche, une requête avec un size à 6000 va renvoyer un code 200 car on affiche bien l'ensemble des éléments disponibles.  
https://blog.octo.com/designer-une-api-rest/#pagination  
  
C'est bien la valeur de la balise "next" qui permet de savoir si on est sur la dernière page.
