### ISSUE TITLE
utilisation logo de hub-eau

### ISSUE THREAD

**Issue by vcloarec** [BRGM/hubeau#80]
Bonjour,
Dans le cadre de l’implémentation d'un client de l'API hydrométrie dans ce projet : https://github.com/vcloarec/ReosProject, je voudrais savoir si il est possible d'utiliser librement le logo hub-eau.

Ci-dessous l'outil en action:

![hubeau](https://user-images.githubusercontent.com/7416892/140252619-97e92bd2-991b-42bf-ba10-23fcb52e0b5f.gif)

L'icone est situé en haut à droite de la fenêtre de l'hydrogramme/station.

**Comment by tvilmus** [comment]
Bonjour,

Oui vous pouvez utiliser librement le logo Hub’Eau.
Si vous le souhaitez, nous pouvons également référencer votre outil sur notre page https://hubeau.eaufrance.fr/page/ils-nous-utilisent
Bien cordialement,
Thierry Vilmus

**Comment by vcloarec** [comment]
> Si vous le souhaitez, nous pouvons également référencer votre outil sur notre page

Ok, je prend note, je vous fais signe quand la version avec le client hub-eau sort.

**Comment by vcloarec** [comment]
Bonjour,
Je viens de sortir la version utilisant Hubeau. Je suis donc preneur pour une référence.
Qu'est ce qu'il vaut faut ?
Bien à vous.

**Comment by tvilmus** [comment]
Bonjour, afin de référencer votre site, j’aurai besoin pour la **vignette** :

- du logo de votre organisme ou de votre appli (je peux utiliser le logo de votre signature)
- du nom de l’appli : ReosProject ou un autre nom
- d’une description courte qui puisse tenir sur 3 à 5 lignes dans le corps de la vignette
- d’une copie d’écran : à vous de me fournir celle que vous préférez ou alors je peux utiliser celle de votre commentaire du 4 novembre
 
Et pour la page de description : 

- d’une description longue contenant le lien vers votre appli et éventuellement d’autres copies d’écran + aussi d’autres liens si nécessaires.


Bien cordialement,
Thierry
