### ISSUE TITLE
[API Hydrobiologie] Erreur lorsqu'une date de fin ou un de début de prélèvement est indiquée

### ISSUE THREAD

**Issue by tbesse-oeb** [BRGM/hubeau#81]
Bonjour,

Je constate un bug lorsqu'on indique une date de début ou une date de fin de prélèvement dans l'API Hydrobiologie :
exemple:  https://hubeau.eaufrance.fr/api/vbeta/hydrobio/indices?date_debut_prelevement=2018-01-01&date_fin_prelevement=2019-01-01&format=json&size=20

`{
  "code": "Internal server error",
  "message": "",
  "field_errors": null
}`

**Comment by AnthonyDEBUR** [comment]
Je rencontre le même problème que Timothée.
Quand on fait tourner l'API **pour les indices hydrobiologiques**  sans renseigner les dates, le résultat nous renvoie une date de prélèvement au format date/heure et pas date seule. Peut être est-ce un élément de réponse.

ex : https://hubeau.eaufrance.fr/api/vbeta/hydrobio/indices?size=10&code_support=13
![image](https://user-images.githubusercontent.com/66001626/153154045-c3e168ff-47d2-44c1-8192-f845e3328d9b.png)

**Comment by tvilmus** [comment]
Merci pour ces signalements.
Lié au ticket #107. Dans le courant du mois de juillet, nous passerons l'API en v1 et corrigerons ce bug.
