### ISSUE TITLE
Erreur en utilisant l'API d'hydrométrie pour récupérer les stations du référentiel

### ISSUE THREAD

**Issue by claustres** [BRGM/hubeau#83]
GET https://hubeau.eaufrance.fr/api/v1/hydrometrie/referentiel/stations?format=json&size=20 produit l'erreur suivante depuis plusieurs jours:
```
{
  "code": "Internal server error",
  "message": "",
  "field_errors": null
}
```

**Comment by tvilmus** [comment]
Merci pour le signalement, le problème est maintenant résolu
