### ISSUE TITLE
/vbeta/qualite_eau_potable/resultats_dis dernière mesure par paramètre

### ISSUE THREAD

**Issue by neo-64** [BRGM/hubeau#84]
Bonjour,

Bravo et merci pour cette API ! 

Je souhaiterai l'utiliser pour récupérer la dernière mesure sur un (ou plusieurs) paramètre SISE-Eaux. N'ayant pas cette possibilité via l'API je suis obligé de faire une requêtes sur 1 an et de filtrer. Je pense que c'est dommage car on génère du traffic pour rien...

Merci et j'espère qu'un jour cette API nous permettra d'avoir des informations plus "fraiches" issues de : https://solidarites-sante.gouv.fr/sante-et-environnement/eaux/eau

**Comment by tvilmus** [comment]
Bonjour,

Pour récupérer uniquement la dernière mesure, ajoutez à votre requête les paramètres sort=desc et size=1

Concernant la fraîcheur des données, dans quelques années le Ministère de la Santé devrait mettre à disposition des webservices qui permettront à Hub'Eau de diffuser les données les plus fraîches possibles.

Cordialement,
Thierry

**Comment by neo-64** [comment]
Bonjour,

Merci d'avoir pris le temps de me répondre. Effectivement la solution proposée peut faire l'affaire. Il faut dans ce cas multiplier les requêtes, par exemple si je veux la dernière mesure de SO4 et de PH de TARNOS, je ne peux pas m'en sortir avec une seule requête (ex : https://hubeau.eaufrance.fr/api/vbeta/qualite_eau_potable/resultats_dis?code_parametre_se=SO4&code_parametre_se=PH&nom_commune=TARNOS&nom_commune=&size=2&sort=desc)

Comme l'API est en béta je voulais juste vous exposer ce "besoin" que j'ai mais je peux effectivement très bien faire une requête pour chaque élément.

Merci pour la deuxième information, j'espère que ce sera dans quelques mois plutôt que dans quelques années mais la démarche est en route et c'est bien là l'essentiel !

David

**Comment by tvilmus** [comment]
Bonjour,

Vous êtes effectivement complétement dans le vrai par rapport à la béta : nous recherchons vos expressions de besoins et vous remercions pour celui que vous avez exprimé !

Cordialement,
Thierry
