### ISSUE TITLE
Erreur en utilisant l'API d'hydrométrie pour récupérer les stations du référentiel

### ISSUE THREAD

**Issue by claustres** [BRGM/hubeau#85]
Probable retour de https://github.com/BRGM/hubeau/issues/83.

**Comment by tvilmus** [comment]
Bonjour,
Effectivement, un retour de ce bug qui est maintenant corrigé

**Comment by DDorch** [comment]
> un retour de ce bug qui est maintenant corrigé

Pardon, juste pour être sûr: ce bug n'est pas corrigé, le problème subsiste:

https://hubeau.eaufrance.fr/api/v1/hydrometrie/referentiel/stations?code_departement=10&format=json&size=20

```json
{
  "code": "Internal server error",
  "message": "",
  "field_errors": null
}
```

**Comment by axel584** [comment]
Bonjour,
Ce bug est très étrange. Il semble disparaitre quand je redémarre le service, mais revenir au bout de quelques jours.
Je viens de redémarrer le service et les choses semblent fonctionner en ce moment.
Je verrai après les fêtes pour trouver une réponse plus pérenne à ce problème;
En attendant, je vous souhaite de bonnes fêtes.

**Comment by tvilmus** [comment]
Actuellement j'ai une réponse correcte...
