### ISSUE TITLE
Absence d'observations depuis le 14/12 via l'API d'hydrométrie

### ISSUE THREAD

**Issue by claustres** [BRGM/hubeau#86]
Example de requête ne fournissant plus de données postérieures au 14/12:  https://hubeau.eaufrance.fr/api/v1/hydrometrie/observations_tr?code_entite=Y142203001&grandeur_hydro=Q&size=20000&sort=desc&fields=date_obs,resultat_obs.

Mais cela semble global à toutes les stations.

**Comment by tvilmus** [comment]
Bonjour,
Effectivement, l’alimentation des observations temps réel dans Hub’Eau a été stoppée le 14/12 vers 17:45 suite à la découverte d’une faille de sécurité majeure. 
La reprise du service est espérée le 20/12.
En attendant, nous allons tenter de mettre en œuvre une procédure manuelle pour au moins rattraper les données entre le 14/12 et le 17/12.
En nous excusant pour la gêne occasionnée,
Thierry Vilmus

**Comment by tvilmus** [comment]
Bonjour,
L'alimentation des hauteurs et des débits temps réel a repris aujourd'hui à 11h. 
Le trou des données entre le 14/12 et le 20/12 a été comblé pour les débits. C'est en cours pour les hauteurs. 
Les opérations de maintenance ne sont pas encore tout à fait terminées, l'API peut être instable.
