### ISSUE TITLE
[API Hydrometrie] grandeur_hydro "H" et "Q" résultats inversés

### ISSUE THREAD

**Issue by christophe77** [BRGM/hubeau#87]
/v1/hydrometrie/observations_tr

Lorsque je fais un appel avec grandeur_hydro="Q" la valeur de retour de resultat_obs correspond à une valeur de hauteur.
Lorsque je fais un appel avec grandeur_hydro="H" la valeur de retour de resultat_obs correspond à une valeur de débit.
https://hubeau.eaufrance.fr/api/v1/hydrometrie//observations_tr?&code_entite=K4000010&grandeur_hydro=Q&size=1
https://hubeau.eaufrance.fr/api/v1/hydrometrie//observations_tr?&code_entite=K4000010&grandeur_hydro=H&size=1

**Comment by tvilmus** [comment]
Bonjour,
Après vérification, les données dans Hub'Eau sont les mêmes que celles que nous recevons du SCHAPI.
De plus elles paraissent cohérentes avec ce qu'affiche le site Vigicrues : https://www.vigicrues.gouv.fr/niv3-station.php?CdEntVigiCru=10&CdStationHydro=K400001010&GrdSerie=Q&ZoomInitial=3
Qu'est ce qui vous fait dire que hauteurs et débits sont inversés ?

**Comment by christophe77** [comment]
Peut être fermé ça venait d'une incompréhension de ma part.
