### ISSUE TITLE
Mettre les API sur github

### ISSUE THREAD

**Issue by christophe77** [BRGM/hubeau#89]
Ca serait intéressant de mettre une ou plusieurs API sur github. 
Je pense que la détection et la correction des bugs seraient plus dynamiques. De nouvelles fonctionnalités peuvent également émerger de personnes extérieures au projet.

**Comment by tvilmus** [comment]
Bonjour, 
Il n'est actuellement pas prévu de partager le code des APIs de Hub'Eau :)
