### ISSUE TITLE
gérer le pas de temps ?

### ISSUE THREAD

**Issue by malotruFR** [BRGM/hubeau#9]
Bonjour,
serait il possible d'intégrer dans le requêtage de l'API _observations_tr_ un notion de pas de temps de la données que nous souhaiterions télécharger?
En effet, les données peuvent être vite volumineuse au pas 5mn si le nb de code_station est important.
La limite de 20 000 est vite atteinte, surtout quand on récupère l'ensemble des stations ...
Mon étude est au pas 30mn donc il y a 6 fois trop de données dans mon JSON 
Je pourrais être plus efficace dans mon appel à l'API et en diminuer le nombre de requêtes.
Merci et m'avoir lu !
Bonne journée
Mathieu (edf)

**Comment by labbev** [comment]
Bonjour,
Merci de votre intérêt pour Hub'eau.

Concernant les **observations_tr** sachez que la limite des 20 000 résultats s'applique uniquement par page.  Ce comportement est différent des API **stations** et **sites** pour lesquels la limite des 20000 concerne effectivement l'ensemble des résultats potentiellement récupérables. 
Vous pouvez ainsi obtenir autant d'observations que possible/souhaité en faisant défiler les pages, grâce à l'utilisation de l'URL contenue dans le champ "next" du corps de la réponse courante.

Concernant la possibilité de paramétrer un pas de temps spécifique, cela fait partie des fonctionnalités que nous prévoyons d'ajouter à court ou moyen terme. 

Cordialement,

Vincent

**Comment by malotruFR** [comment]
Bonjour
et merci de votre réponse rapide.
Je ne me servais pas de **next**, merci d'avoir attiré mon attention sur le sujet.
A noter qu'en faisant quelques tests, j'ai pu voir que si **size** dépassait les 2000 (3000 par exemple), j'avais un message "internal error". Je n'ai pas déterminé exactement à partir de quel chiffre j'avais l'erreur
Merci et bonne journée
Mathieu

 "first" : "http://hubeau.eaufrance.fr/api/vbeta/hydrometrie/observations_tr?code_entite=*&pretty&grandeur_hydro=H&fields=code_station,date_debut_serie,date_fin_serie,date_obs,resultat_obs,continuite_obs_hydro&cursor=&size=3000", **>>> OK**
  "prev" : null,
  "next" : "http://hubeau.eaufrance.fr/api/vbeta/hydrometrie/observations_tr?code_entite=*&pretty&grandeur_hydro=H&fields=code_station,date_debut_serie,date_fin_serie,date_obs,resultat_obs,continuite_obs_hydro&cursor=AoUIP4AAACpBMDYxMDA1MDUxIUhwtKmE7+UCPwxBMDYxMDA1MF9BMDYxMDA1MDUxX0hfNF8yMDE4LTA5LTE1VDE2OjMwOjAw&size=3000"  **>>> KO**

**Comment by labbev** [comment]
Bonjour,

Nous observons effectivement un problème sur le mécanisme de pagination par curseur de cette API. Nous sommes en train de le résoudre, ça devrait rentrer dans l'ordre rapidement.

Pour info, le problème est indépendant du nombre de résultats/page demandé. C'est le caractère "+" parfois présent dans la valeur du curseur (paramètre de l'URL next) qui pose problème. 

En attendant que notre solution soit déployée (la semaine prochaine probablement), vous pouvez contourner ce problème en remplaçant le caractère "+" lorsqu'il apparait dans la valeur du curseur, par la séquence "%2B" (sans les "" bien sûr).

Application à votre exemple d'URL KO : http://hubeau.eaufrance.fr/api/vbeta/hydrometrie/observations_tr?code_entite=*&pretty&grandeur_hydro=H&fields=code_station,date_debut_serie,date_fin_serie,date_obs,resultat_obs,continuite_obs_hydro&cursor=AoUIP4AAACpBMDYxMDA1MDUxIUhwtKmE7%2BUCPwxBMDYxMDA1MF9BMDYxMDA1MDUxX0hfNF8yMDE4LTA5LTE1VDE2OjMwOjAw&size=3000

Cordialement,

Vincent

**Comment by malotruFR** [comment]
Merci ! Effectivement ma boucle while marche mieux désormais
je fais une autre issue, je suis très interessé par vos données alors je fais de multiples tests
Cordialement,
Mathieu

**Comment by tvilmus** [comment]
Bonjour,
Merci pour votre intérêt ! De notre côté, nous sommes très intéressés par les résultats de vos tests.
Le problème concernant les caractères "+" dans les URL est maintenant réglé.
Cordialement,
Thierry

**Comment by tvilmus** [comment]
Bonjour,
Nous sommes heureux de vous dire que nous avons inclus un paramètre timestep aux endpoints observations_tr, qui vous permet d'introduire une notion de pas de temps dans vos requêtes.
Cordialement,
Thierry

**Comment by MathieuGia** [comment]
Bonjour,
je vous remercie, je vais pouvoir alléger mes requêtes sur votre site, je vous remercie !
Cordialement,
Mathieu -Edf-
