### ISSUE TITLE
[API QUALITÉ DE L'EAU POTABLE] - date des données

### ISSUE THREAD

**Issue by LYZOFR** [BRGM/hubeau#90]
Bonjour,
Afin de connaitre facilement la date (mois/année) de la dernière alimentation des données, est ce possible d'ajouter cette date sur le site Internet de cet API ?
Exemple de requête que j'utilise actuellement pour avoir cette info :
https://hubeau.eaufrance.fr/api/vbeta/qualite_eau_potable/resultats_dis?fields=date_prelevement&size=1&sort=desc

Autrement, avez vous une date approximative de la fin de la phase béta ?

Merci
Cordialement
C.LEDRU

**Comment by christophe77** [comment]
L'idéal serait d'avoir un champs "date_dernier_prelevement" dans chaque réseau récupéré avec "communes_udi". Comme ça on peut appeler "resultats_dis" avec cette date ou la chercher dans les résultats.

**Comment by tvilmus** [comment]
Bonjour,   
Nous ajoutons la date de dernière ingestion des données sur la page du site internet de l'API : https://hubeau.eaufrance.fr/page/api-qualite-eau-potable  
Les alimentations ont lieu tous les 15 du mois. Les dernières données concernent le mois N-2.

**Comment by LYZOFR** [comment]
Bonjour Thierry,

Merci pour cette bonne nouvelle.

Cordialement

Cyril LEDRU

Le 2022-07-05 17:38, Thierry Vilmus a écrit :

> D'autre part, nous passerons l'API en v1 pour le mois d'août. La v1 
> aura le même périmètre fonctionnel que la version béta
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>



Links:
------
[1] https://github.com/BRGM/hubeau/issues/90#issuecomment-1175204030
[2]
