### ISSUE TITLE
Internal server error avec l'API hydrométrie

### ISSUE THREAD

**Issue by vcloarec** [BRGM/hubeau#92]
Bonjour,
L'opération `referentiel/stations` conduit à une erreur 500 (Internal server Error) depuis le 26 décembre en cours de journée. pas de problème en début de journée, et puis en fin de journée, cette erreur est systématique.
Pour reproduire: les liens de cette page https://hubeau.eaufrance.fr/page/api-hydrometrie#console conduisent à cette erreur.

**Comment by vcloarec** [comment]
Après investigation, l'erreur apparaît lorsqu'il n'y a pas le paramètres `fields`

**Comment by claustres** [comment]
Probable doublon de https://github.com/BRGM/hubeau/issues/85.

**Comment by tvilmus** [comment]
Oui, même erreur que #85 et #83, actuellement fonctionnement normal avec ou sans fields

**Comment by vcloarec** [comment]
ok, merci. 
Finalement je fais toujours avec les fields, plus sûr...
