### ISSUE TITLE
API des observations hydrométriques dysfonctionnelle

### ISSUE THREAD

**Issue by claustres** [BRGM/hubeau#94]
La requête suiante retourne un code 503: https://hubeau.eaufrance.fr/api/v1/hydrometrie/observations_tr?code_entite=Y142203001&grandeur_hydro=Q&size=20000&sort=desc&fields=date_obs,resultat_obs.

Une requête sur le référentiel semble par contre fonctionner correctement.

**Comment by tvilmus** [comment]
Bonjour,

Merci pour les signalements.
La forte sollicitation de l’API a fait tomber successivement le endpoint stations puis le endpoint observations_tr. Les problèmes sont maintenant résolus mais on constate que le endpoint stations est « fragile » et se déconnecte de temps en temps.
Nous cherchons à renforcer la stabilité de ces endpoints.
Toutes nos excuses pour ces dysfonctionnements.

Bien cordialement,
Thierry

**Comment by claustres** [comment]
Cette erreur semble de retour.

**Comment by tvilmus** [comment]
le service est reparti...

**Comment by claustres** [comment]
Nous recevons à nouveau des code 500 ou 503 sur les deux poins d'entrée.

**Comment by tvilmus** [comment]
Effectivement...
je vais finir par croire à la malédiction du dimanche soir...
Nous relançons les serveurs lundi matin

**Comment by tvilmus** [comment]
Bonjour,
C'est reparti depuis 10h10. 
Toutes nos excuses à nouveau...

**Comment by claustres** [comment]
La malédiction semble de retour, erreurs 503 sur les deux points d'accès.

**Comment by claustres** [comment]
`Internal server error` sur les deux points d'accès depuis cette nuit.

**Comment by claustres** [comment]
Le problème semble à nouveau survenir sur les stations.

**Comment by claustres** [comment]
@tvilmus Cela fait maintenant plusieurs mois que les services de l'API hydrométrie rencontre des problèmes récurrents de disponibilité. La cause de ces problèmes sont-elles déjà identifiées ? Y a-t-il des actions en cours pour pallier à ces problèmes à court-terme ou moyen-terme ? 

Merci pour votre transparence sur le sujet.
