### ISSUE TITLE
Bug: Doublon de donnée en H et Q au même pas de temps pour des stations d'hydrométrie

### ISSUE THREAD

**Issue by P-YV** [BRGM/hubeau#95]
Bonjour, 

Je viens de me rendre compte d'un problèmes de données sur Hub'eau pour certaines stations hydrométriques que nous gérons: 

Sur la station de Caissarges sur le Vistre (Y351 4005 01 : Le Vieux Vistre à Caissargues) à la date du 01/01/2022 à 23:50, il y a deux valeurs de hauteur affichées (360 et 904 mm) alors que dans la PHYC il n'y a bien sur qu'une seule valeur pour ce pas de temps : 904 mm. De début décembre au 3 janvier  ce problème est apparu régulièrement. Il semble avoir disparu depuis le 3 janvier sur cette station. 

Ce bug est aussi apparu pour les données de débit d'au moins une autre station : Bernis (Y351402001) par exemple le 27/12 à 13h35 où Hub'eau renvoi 2 valeurs (2.11 m3/s et 2.31 m3/s) pour une valeur en PHYC de 2.31 m3/s

Merci de me confirmer que ce bug et bien corrigé car nous envisageons de conseiller à un de nos partenaire GEMAPIEN qui souhaite récupérer la donnée en temps réel pour sa gestion de crise d'utiliser Hub'eau sur les stations du Vistre.

Cordialement 

Pierre-Yves Valantin 
Responsable du pôle Hydrométrie Prévision des crues Grand delta

**Comment by tvilmus** [comment]
Bonsoir,

Merci pour ce signalement.
Prenez-bien garde au **statut** de la donnée (champ statut_serie) :  
https://hubeau.eaufrance.fr/api/v1/hydrometrie/observations_tr?code_entite=Y351400501&grandeur_hydro=H&size=5&sort=asc&fields=date_obs,resultat_obs,statut_serie&date_debut_obs=2022-01-01T23:45:00Z
renvoie
![image](https://user-images.githubusercontent.com/28749963/148808811-69799b6b-fc68-4134-a00a-6e790d2cc7d7.png)

Le 01/01 à 23:50 il y a une donnée de statut 4 (brute) et une de statut 12 (donnée pré-validée). Ce qui est étrange c'est que c'est la donnée pré-validée qui semble fausse par rapport à l'ensemble des valeurs brutes environnantes...

Nous nous rapprochons du SCHAPI pour comprendre pourquoi ces données de statut 12 apparaissent...

Cordialement,
Thierry Vilmus

**Comment by P-YV** [comment]
Merci pour votre réponse rapide, 

Je n'avais pas fait attention au statu de la donnée. Du coup le problème vient de d'une mauvaise utilisation dans Hub'eau des différents statuts de validité de la donnée
En tant que producteur je pense pouvoir vous répondre à votre question. Quand nous bancarisons des données pré-validées ou validées, nous lissons la courbe pour ne garder que les variations signifiante et filtrer le batillage. La nouvelle série de donnée ainsi créer "annule et remplace" la série de validité inférieure même si celle-ci reste toujours consultable dans la PHYC. Du coup il ne faut surtout pas mélanger dans une même série (sur un même graphique dans le visualiseur par exemple) des données avec des niveaux de validité différents. Sinon on a comme actuellement des saut incohérents entre la donnée brute et la donnée validée (par exemple si il y a eu une correction suite à un recalage du capteur) et on obtient des trait verticaux aux pas de temps ou il y a 2 données entre la donnée brute et la validée.

Dans la réponse de l'API c'est peut-être un peu moins gênant puisque en théorie l'utilisateur pourrait filtrer les données pour ne garder que le code qui lui convient, mais  pour cela il faudrait que ce soit très clairement expliqué. Le plus simple serait sans doute de d'offrir à l'utilisateur la possibilité de préciser le code de validité qu'il souhaite récupérer et en l'absence de code de fournir la donnée brute qui reste la plus utile pour le temps réel.

Cordialement
Pierre-Yves Valantin

**Comment by tvilmus** [comment]
Bonjour, 
Merci pour cette réponse très détaillée. 
En concertation avec le SCHAPI, nous avons prévu cette année de modifier la réponse de Hub'Eau pour ne diffuser que **les séries de données de meilleur statut**.
