### ISSUE TITLE
Profondeur temporelle des données piézométriques

### ISSUE THREAD

**Issue by paumillet** [BRGM/hubeau#96]
Bonjour,

À l'instar de l'API hydrométrie, je souhaitais savoir si l'API piézométrie avait également une profondeur temporelle limitée à 1 mois pour les données transmises en temps réel ? Ces données peuvent-elles profiter de corrections suite à leur publication ?

Merci pour votre retour,
Pauline

**Comment by tvilmus** [comment]
Bonsoir, 

Les données "temps réel" diffusées par l''API piézométrie sont réellement des données brutes en provenance directe des capteurs. Elles ne sont pas corrigées.  
Leur profondeur temporelle n'est actuellement pas limitée mais nous envisageons de la limiter à 1 an. 

Cordialement,
Thierry

**Comment by paumillet** [comment]
Merci de votre réponse.
Peut-on alors considérer que les chroniques (de l'API https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques) sont des données corrigées ?
Quelle est la fréquence de mise à jour de ces données ? Je vois que les dernières données disponibles remontent au 3 janvier (exemple avec la station code BSS 03567X0041/PZ4 (ancienne version)).

**Comment by tvilmus** [comment]
Oui les données du endpoint "chroniques" sont d'une part des données agrégées et qui peuvent être corrigées (si dérive d'un capteur, si nouveau nivellement du repère de mesure, ...) 

Ce sont les producteurs des données qui réalisent ces opérations puis transmettent leurs données à la banque ADES, qui est la source des données alimentant le endpoint "chroniques" de l'API Piézométrie de Hub'Eau . Les données sont agrégées sur une journée, c'est généralement la valeur maximale du niveau NGF (valeur minimale de la profondeur) qui est retenue, mais ça peut varier en fonction des points d'eau.

Hub'Eau se synchronise une fois par jour avec ADES. Par contre, les différents producteurs de données ne remontent pas toujours leurs données rapidement dans ADES. On peut toutefois avoir des données récentes, comme pour le point de code 05432X0003/FF : 
https://hubeau.eaufrance.fr/api/v1/niveaux_nappes/chroniques?code_bss=05432X0003%2FF&size=20&sort=desc  
renvoie une donnée pour hier 27/01/2022.

**Comment by paumillet** [comment]
Merci pour toutes ces précisions !
