### ISSUE TITLE
[hydrobio] coquille dans un des exemples

### ISSUE THREAD

**Issue by AnthonyDEBUR** [BRGM/hubeau#97]
Bonjour,

Petite erreur dans les exemples de l'API hydrobio : 

```
Recherche de tous les indices biologiques concernant les **diatomées** (dont le code SANDRE support = 13) :
https://hubeau.eaufrance.fr/api/vbeta/hydrobio/indices?size=10&code_support=13
```

Le code support 13 correspond aux macroinvertébrés et non aux diatomées (qui correspond au code support 10).

Bien cordialement

**Comment by tvilmus** [comment]
Bonjour,
Merci pour ce signalement. 
La coquille a été corrigée.
Bien cordialement,
Thierry
