### ISSUE TITLE
[API-Hydrobiologie] Ajouter la référence de l'opération aux exports

### ISSUE THREAD

**Issue by AnthonyDEBUR** [BRGM/hubeau#99]
Dans l'ensemble des opérations de l'API Hydrobiologie, il conviendrait d'ajouter le champs disponible dans les exports Naïades : RefOperationPrelBio

Ce champs permet de différencier les résultats si 2 opérations ont été faites le même jour sur la même station (cas rarissime mais qui est déjà arrivé).

**Comment by AnthonyDEBUR** [comment]
Même remarque pour les listes taxonomiques. Sans le champs RefOperationPrelBio on ne sait pas avec certitude rattacher la liste à l'opération correspondant.

Dans la description des données des exports Naïades il est précisé pour ce champs : 

> Référence de l’opération de prélèvement dans la
> banque de référence
> Champ permettant d’effectuer une jointure
> a v e c l e s f i c h i e r s O p e r a t i o n s
> ResultatsBiologiques et ListesFauneFlore.

**Comment by tvilmus** [comment]
Bonjour, 
Dans le courant du mois de juillet, nous passerons l'API en v1 et ajouterons les champs code_banque_reference et code_operation à la réponse de l'API pour les endpoints indices et taxons. De plus, ces champs seront requêtables.
